### ISSUE TITLE
Some guide/help import third-part libraries/ assets and customization new module

### ISSUE THREAD

**Issue by nutrimax1987** [sysgears/apollo-universal-starter-kit#1034]
Hello guys , i',m switching from Angular to react development and found this template useful .
I ask your help here due to missing guide how to customize generated components and import to it global variables.. 
For instance i have overridden ant-design variables with my own 'theme.less' and then the question is 
1. How to import my 'theme.less' to react  'MyCompoment.less' ?
2. What the right way to add assets to this template , like fonts ,images and etc..?
3. How do we add moment.js for instance to be it common for all packages?

**Comment by vlasenko** [comment]
@nutrimax1987 This is a webpack-based projects. General approach for webpack-based projects of dealing with assets and/or dependencies is to install dependency from `npm` (note you should use `yarn` to do it) and then `import` relevant files from this dependency. There are `npm` packages for `moment.js` as well as for `fonts`, `images`, etc. In case if you want to add custom image, or custom font, for which there is no `npm` package exists, you can check how `modules/favicon` do it.

**Comment by nutrimax1987** [comment]
Thank you for reply !!! And how to resolve this , the first question i asked ..? 
![screen shot 2019-02-18 at 21 12 39](https://user-images.githubusercontent.com/13996110/52971952-fbef9d00-33c1-11e9-8f06-f44b12fc4b3a.png)

**Comment by nutrimax1987** [comment]
?

**Comment by nutrimax1987** [comment]
> @nutrimax1987 This is a webpack-based project. The general approach for webpack-based projects for dealing with assets and/or JS dependencies is to install dependency from `npm` (note you should use `yarn` to do it) and then `import` relevant files from this dependency. There are `npm` packages for `moment.js` as well as for `fonts`, `images`, etc. In case if you want to add custom image, or custom font, for which there is no `npm` package exists, you can check how `modules/favicon` do it.

Please response to next comment?

**Comment by vlasenko** [comment]
@nutrimax1987 The `webpack.config.js` in-memory by `spinjs`: 
you can view it by passing `-v` option:
https://github.com/sysgears/spinjs/blob/master/docs/scripts.md#running-spinjs-commands-with-options
and you can amend generated `webpack.config.js`:
https://github.com/sysgears/spinjs/blob/master/docs/configuration.md#toolnameconfig

**Comment by vlasenko** [comment]
@nutrimax1987 Cross-module less file imports are tricky, because `less-loader` do not resolve symlinks, hence to figure out proper relative path you should look into `node_modules/@gqlapp` with file manager.
You will see that correct relative path would be:
```
@import '../../look-client-react/ui-antd/styles/styles.less';
```
You can use absolute imports however, they will be hopefully more straightforward:
```
@import '~@gqlapp/look-client-react/ui-antd/styles/styles.less';
```
