### ISSUE TITLE
How to set db.js and .env for postgres in local for dev and postrges on heroku for prod

### ISSUE THREAD

**Issue by ilostit** [sysgears/apollo-universal-starter-kit#1035]
Hi,

I would like to link my app to my postgres plan on heroku when i deployed. But i don't know how to configure that to keep my local configuration and my configuration for prod. 

here my configuration working well on local in my .env :

DB_CLIENT: 'pg',
DB_HOST: 'localhost',
DB_SOCKET_PATH: '',
DB_USER: 'postgres',
DB_PASSWORD: '',
DB_DATABASE: 'postgres',
DB_PORT: '5432',

I will use the DATABASE_URL for heroku when i deployed in prod but i don't know how to setup that properly?

DB_CLIENT_PROD: 'pg',
DB_HOST_PROD: '',
DB_SOCKET_PATH_PROD: '',
DB_USER_PROD: '',
DB_PASSWORD_PROD: '',
DB_DATABASE_PROD: DATABASE_URL',
DB_PORT_PROD: '5432',

Thanks for help

**Comment by vlasenko** [comment]
@ilostit 
https://stackoverflow.com/questions/40119964/how-to-set-environment-variables-on-heroku-for-nodes-app-and-connect-to-the-post

**Comment by ilostit** [comment]
Great, it seems to be ok but have an issue, logs of heroku say  : server: Error: connect ECONNREFUSED 127.0.0.1:5432 when i deployed... any idea ?

**Comment by ilostit** [comment]
i add a variable DB_HOST in heroku with the host of the postgres db, it's fixed, thanks for ur help
