### ISSUE TITLE
Integrate `react-apollo-hooks` into the kit, to allow the use of Apollo Hooks

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-universal-starter-kit#1043]
With parts of the kit being converted to use Reach Hooks #1027, maybe we could add https://github.com/trojanowski/react-apollo-hooks, to be able to use `useQuery ` and `useMutation`, instead of `Query` and `Mutation` components.

We could also wait for https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-mid-2019-the-one-with-suspense-for-data-fetching to be implemented in React and then probably Apollo will integrate similar functionality into the core library as well.

Will create a PR for this when I find time, or someone else can take a stab at it as well.

**Comment by vlasenko** [comment]
We are integrating `react-apollo` version 3 now, it supersedes `react-apollo-hooks`
