### ISSUE TITLE
best approach to return postList from the currentUser

### ISSUE THREAD

**Issue by ilostit** [sysgears/apollo-universal-starter-kit#1044]
Hi,
what's the best approach to return postList from the currentUser ?

Cheers and thanks for this great ressource

**Comment by MassivDash** [comment]
There is a number of things you need to do to accomplish this: 

1. You need to alter the sql database, so posts table include a field like the owner/user 

2. Alter / Add the post knex query so it returns post by user 
```
.where('user', '=', user)
```
3. Alter the server resolver so it takes in additional user argument and passes it on to the knex query

4. Finally, alter the client graphql posts query so it passes the additional argument of user to the resolver.

Things to consider: 
- Special resolver or knex query for admin user. 
- If you plan on showing only posts belonging to user, you need to alter "Get Total" posts query as well, as it will disrupt the "load more function"/ pagination  
- Special query for non-signed in users.

**Comment by ilostit** [comment]
Hi, 

thanks, that's what I thought !
But how knex query know the 'currentUser' when u do the .where('user', '=', user) ? 
And i suppose is the same if i use the  .where('id', '=', user_id), but same question how knex query know the currentUser.id ?

**Comment by MassivDash** [comment]
The kit has built-in, "currentUserQuery" graphql query, after someone logs in, it returns the user ID, name and other dara. Its used to check if you are an admin in the user module, or profile section for example.

**Comment by ilostit** [comment]
thanks @MassivDash , i close the issue, i have all the info 👍
