### ISSUE TITLE
Unable to start stable branch

### ISSUE THREAD

**Issue by trusinaj** [sysgears/apollo-universal-starter-kit#1046]
After pulling and installing packages Im unable to start apollo starter kit 

**To Reproduce**
1. Clone stable branch
2. yarn
3. yarn seed / yarn watch 

**Expected behavior**
Project should start without any errors

**Screenshots**
yarn seed
![image](https://user-images.githubusercontent.com/26432590/54597705-574f9200-4a37-11e9-8ee9-c7e0286bf83b.png)

When I try yarn watch, project wont run, I know I should seed sample data to the database first, but any of errors listed bellow doesnt seem to corelate with missing datababe seed, or am I wrong?
![image](https://user-images.githubusercontent.com/26432590/54598087-14da8500-4a38-11e9-955b-192adc81c461.png)

![image](https://user-images.githubusercontent.com/26432590/54598363-a518ca00-4a38-11e9-85bb-d8cf13c2e2fa.png)

It seemd to me that postcss.config.js is missing in root, When I created one, error changed to
![image](https://user-images.githubusercontent.com/26432590/54598909-d5ad3380-4a39-11e9-8743-f55e9f826a6b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Node: 10.15.3
 - Yarn: 1.15.2

**Comment by vlasenko** [comment]
@trusinaj We are relying on working symlinks. Under Windows 10 they do not work out of the box in `node`, please google how to configure and enable them

**Comment by trusinaj** [comment]
Ahh ok, I see, thanks for quick reply

**Comment by trusinaj** [comment]
Ok, fix for this problem seems to be pretty straightforward. For any windows 10 user:

1. Use the shortcut Windows-I to open the Settings application.
2. Navigate to Update & Security > For Developers.
3. Switch to "Developer Mode"

This will enable symlinks.
BUT there was still issue with missing PostCss config (see screenshots above for yarn watch).

This issue is solved by creating postcss.config.js in root of project. I simply copied postcss.config.js from ./packages/client to root. 

Hopefuly this helps out, cheers
