### ISSUE TITLE
Native: i18Next seems to be not working on the production

### ISSUE THREAD

**Issue by MassivDash** [sysgears/apollo-universal-starter-kit#1064]
**Describe the bug**

The official expo demo app is not working properly. 
It seems that i18Next is not included in the production app.

I have discovered this when tried to publish my build of this starter.
This is the error I have in the expo published app:  
"Uncaught Error: (0, d.translate) is not a function (In '(0,d.translate)("event")', (0,d.translate)' is undefined. 

('event') is a extra module I have installed via cli. 

I hope this is related to the same bug that's present in the official app.

**Screenshots**

![Screenshot_20190424-225643](https://user-images.githubusercontent.com/26141530/56697037-ef533200-66ed-11e9-8b40-8eede766ae9e.png)

**Smartphone (please complete the following information):**
- Native production for iOS and Android

**Additional context**

Tried to upgrade the i18next to the latest build packages and i18next-react to 9.0.10. 
No effect on the error.

**Comment by vlasenko** [comment]
Confirmed, this is a minification issue.
