### ISSUE TITLE
ReactNative Forgot Password form on infinite loop call.   

### ISSUE THREAD

**Issue by MassivDash** [sysgears/apollo-universal-starter-kit#1066]
**Describe the bug**

ForgotPassword section for ReactNative is on an infinite loop with calls to database with zero input. 

**To Reproduce**
Go to forogot password section on iOS or Android

**Expected behavior**
Get the form to send a recovery email.

**Smartphone (please complete the following information):**
iOS and Android

**Additional context**
Preparing PR for this bug

**Comment by vlasenko** [comment]
Fixed via #1067
