### ISSUE TITLE
error client-angular@1.0.0: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by eric-burel** [sysgears/apollo-universal-starter-kit#1073]
**Describe the bug**
Hi, I get the following error on install:
```
error client-angular@1.0.0: The engine "node" is incompatible with this module. Expected version ">= 6.11.1 <= 10". Got "11.0.0"
```
Quick fix is to use Node 10.0.0. However I did not intend to use Angular so I am surprised by this bug.

**To Reproduce**
Install Node 11 and run `yarn` on a fresh `stable` clone.

**Expected behavior**
Either not this bug, or at least avoid the installation of `client-angular` as a default?

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Node 11

**Comment by vlasenko** [comment]
Yep, we should remove `engines -> node` from `packages/client-angular/package.json`

**Comment by vlasenko** [comment]
Engines removed in `master` branch
