### ISSUE TITLE
On the stable branch yarn cli choosestack breaks yarn seed & yarn watch

### ISSUE THREAD

**Issue by strefethen** [sysgears/apollo-universal-starter-kit#1087]
**Describe the bug**
After cloning the stable branch and using the CLI to choose react & react native stack yarn seed fails.

**To Reproduce**
1. Follow the README to download the stable branch
2. Issue yarn to install packages
3. Use yarn seed

Resulting error:

>➜  vxrcloud-apollo git:(stable) yarn cli choosestack
yarn run v1.15.2
$ node tools/cli choosestack
? Choose your technology stack or stacks react & react native
✨  Done in 4.07s.
➜  vxrcloud-apollo git:(stable) ✗ yarn seed
➜  vxrcloud-apollo git:(stable) ✗ yarn seed
yarn run v1.15.2
$ lerna run --scope=server seed --stream
lerna notice cli v3.13.4
lerna info versioning independent
lerna info filter [ 'server' ]
lerna ERR! EFILTER No packages remain after filtering [ 'server' ]
error Command failed with exit code 1.`

**Expected behavior**
yarn seed should complete successfully.

**Desktop (please complete the following information):**
 - OS: osx
 - Version: 10.14.4
- Node v10.15.3
- yarn v1.15.2

**Comment by strefethen** [comment]
@BaloPhilip any update on this?

**Comment by vlasenko** [comment]
@strefethen `yarn seed` initializes database using migration and seed files located in `server` modules. Since you have deleted `server` you have no longer seeds and migrations.
