### ISSUE TITLE
Fix typo in configuration.md DB_TYPE should be DB_CLIENT

### ISSUE THREAD

**Issue by strefethen** [sysgears/apollo-universal-starter-kit#1090]
**Describe the bug**
In ./docs/configuration.md the Database section mentions setting DB_TYPE when it should be DB_CLIENT.  The typo needs fixing.

**To Reproduce**
1. Open ./docs/configuration.md
2. Refer to the Database section
// Note "DB_TYPE" which should read DB_CLIENT.

**Additional context**
Sorry for not creating a PR, before I can submit a PR I need approval from my employer and that process is working it's way through the system.

**Comment by vlasenko** [comment]
@strefethen Thank you, the approach with describing problem and solution in the Issue works great too! Fixed
