### ISSUE TITLE
Error: Cannot find module '@ant-design/colors'

### ISSUE THREAD

**Issue by neneji** [sysgears/apollo-universal-starter-kit#1114]
**Describe the bug**
server: Error: Cannot find module '@ant-design/colors'
server:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
server:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
server:     at Module.require (internal/modules/cjs/loader.js:637:17)
server:     at require (internal/modules/cjs/helpers.js:22:18)
server:     at Object.<anonymous> (/Users/haozheyu/Dev/exps/apollo-universal-starter-kit/node_modules/@ant-design/icons-react/lib/utils.js:27:15)
server:     at Module._compile (internal/modules/cjs/loader.js:689:30)
server:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
server:     at Module.load (internal/modules/cjs/loader.js:599:32)
server:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
server:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
server: [nodemon] app crashed - waiting for file changes before starting...

**To Reproduce**
after clone, i changed the `modules/look/client-react/look.ts` to load `ui-antd` 
then `yarn && yarn seed && yarn watch`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser Chrome
 - Version 74.0.3729.169

**Comment by H1net** [comment]
I had similar issues @neneji and think it is related to the resolution in the root package.json

You'll need better advice for deployment, as I ran into other issues there with heroku (or on new git clones) but manually adding the package to node_modules should work for your development environment - or I worked around it by adding @ant-design/colors to the client package.json as follows:
```
cd packages/client
yarn add @ant-design/colors
```

For devs, doing the above results in this on my production build to heroku:
> warning Pattern ["@ant-design/colors@^3.1.0"] is trying to unpack in the same destination "/tmp/yarncache.E0arK/v4/npm-ant-design-palettes-3.1.0-b7e2cc61a4e86d3d109494034acfb1222dacaa3c/node_modules/ant-design-palettes" as pattern ["ant-design-palettes@npm:@ant-design/colors"]. This could result in non-deterministic behavior, skipping.
And then a cascade of follow-up issues as it cannot find ant-design.

**Comment by vlasenko** [comment]
@H1net @neneji Have you tried to remove `"ant-design-palettes": "npm:@ant-design/colors"` from root `package.json -> resolutions` ?

**Comment by H1net** [comment]
> remove `"ant-design-palettes": "npm:@ant-design/colors"` from root `package.json -> resolutions`

Solved
