### ISSUE TITLE
Custom Module Namespaces

### ISSUE THREAD

**Issue by verdverm** [sysgears/apollo-universal-starter-kit#1115]
@vlasenko I found a spot in the client-react webpack where we need to do something similar to #1111 on the server side.

https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/client/webpack.config.js#L89

It would be ideal to have one ENV_VAR to support both server / client. Currently we setup the ENV_VAR in server to mean the whole regexp. The client has a different format, just the @gqlapp, rather than a number. My thought was to move to an ENV_VAR that is only the extra namespaces. This would enable using the same ENV_VAR for both server and client.

Thoughts?

**Comment by vlasenko** [comment]
@verdverm Yes, lets move to one ENV_VAR for extra namespaces

**Comment by vlasenko** [comment]
Should be fixed via #1116
