### ISSUE TITLE
Updating cache called twice after the mutation

### ISSUE THREAD

**Issue by zirho** [sysgears/apollo-universal-starter-kit#1117]
https://www.apollographql.com/docs/react/essentials/mutations/#updating-the-cache

After the mutation call, update function gets called twice.

**To Reproduce**
I forked the latest master and reproduced it here. (I removed optimistic response just to make sure)
https://github.com/zirho/apollo-universal-starter-kit

![image](https://user-images.githubusercontent.com/1251296/60215677-fcd78600-981c-11e9-9e67-95c1fa8efd53.png)
![image](https://user-images.githubusercontent.com/1251296/60215692-02cd6700-981d-11e9-999b-952960852a10.png)

**Expected behavior**
Refer the example that I tried on this example
(I tried the same versions of packages that may related to the issue such as react-apollo and graphql)
https://github.com/zirho/graphql-yoga/tree/master/examples/fullstack

update function gets called once
![image](https://user-images.githubusercontent.com/1251296/60215250-14623f00-981c-11e9-8c0f-09c4e9d2ff72.png)

**Comment by vlasenko** [comment]
@zirho We are using two Apollo Caches in the kit. One cache for Apollo Link state queries/mutations/subscriptions and another one for server queries/mutations/subscriptions. This lets us selectively reset one of these caches and retain another. For example when user signs in we reset server cache, but keep Apollo Link state cache untouched. This is just demo of how one can reset parts of Apollo Cache. This is something Apollo do not allow at the moment via official API. There is a price for this feature - the mutation update callbacks are being called multiple times. If you don't want this feature you can replace these lines:
```
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/modules/core/common/createApolloClient.ts#L35-L57
```
via
```
const cache = new InMemoryCache();
```

**Comment by zirho** [comment]
Thank you for the explanation.
Let me go through some apollo docs to understand better on Link state cache and server cache.

Thanks!

**Comment by vlasenko** [comment]
@zirho This is not in Apollo docs. I have implemented multiple Apollo cache usage here:
https://github.com/sysgears/apollo-cache-router/blob/master/src/index.ts
