### ISSUE TITLE
undefined is not an object(panresponder panhandlers)

### ISSUE THREAD

**Issue by canercak** [sysgears/apollo-universal-starter-kit#1138]
**Describe the bug**
After cloning the repo and seeding, I try to run the ios app in expo. I get "undefined is not an object(panresponder panhandlers)" error when I click "Posts". Expo is the latest version in ios.

**To Reproduce**
1. yarn
2. yarn seed
3. yarn watch:ios
4. Run on expo client app,
5 .Click "Posts"

**Expected behavior**
Posts has to work like in web mode

**Screenshots**
attached
**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: Latest
 - Browser 
 - Version 

**Additional context**
![image1](https://user-images.githubusercontent.com/2890782/63275042-8483c300-c2a9-11e9-9c21-3e79b75eef5e.png)

> mobile: [18:01:01] frontend debug loading <= serverCounterQuery
> server: backend debug read session { csrfToken: '93e42f84eaeea8a3c8e09dd88bc36e32', id: 1 }
> server: backend debug {"data":{"serverCounter":{"amount":5,"__typename":"Counter"}}} <= undefined
> server: backend debug {"data":{"currentUser":{"id":1,"username":"admin","role":"admin","isActive":true,"email":"admin@example.com","profile":{"firstName":null,"lastName":null,"fullName":null,"__typename":"UserProfile"},"auth":{"certificate":null,"facebook":null,"google":null,"github":null,"linkedin":null,"__typename":"UserAuth"},"__typename":"User"}}} <= undefined
> mobile: [18:01:01] frontend debug {"data":{"currentUser":{"id":1,"username":"admin","role":"admin","isActive":true,"email":"admin@example.com","profile":{"firstName":null,"lastName":null,"fullName":null,"__typename":"UserProfile"},"auth":{"certificate":null,"facebook":null,"google":null,"github":null,"linkedin":null,"__typename":"UserAuth"},"__typename":"User"}}} <= currentUser
> mobile: [18:01:01] frontend debug {"data":{"serverCounter":{"amount":5,"__typename":"Counter"}}} <= serverCounterQuery
> mobile: [18:02:08] frontend debug loading <= posts({"limit":10,"after":0})
> server: backend debug read session { csrfToken: '93e42f84eaeea8a3c8e09dd88bc36e32', id: 1 }
> server: backend debug {"data":{"posts":{"totalCount":20,"edges":[{"cursor":0,"node":{"id":20,"title":"Post title 20","content":"Post content 20","__typename":"Post"},"__typename":"PostEdges"},{"cursor":1,"node":{"id":19,"title":"Post title 19","content":"Post content 19","__typename":"Post"},"__typename":"PostEdges"},{"cursor":2,"node":{"id":18,"title":"Post title 18","content":"Post content 18","__typename":"Post"},"__typename":"PostEdges"},{"cursor":3,"node":{"id":17,"title":"Post title 17","content":"Post content 17","__typename":"Post"},"__typename":"PostEdges"},{"cursor":4,"node":{"id":16,"title":"Post title 16","content":"Post content 16","__typename":"Post"},"__typename":"PostEdges"},{"cursor":5,"node":{"id":15,"title":"Post title 15","content":"Post content 15","__typename":"Post"},"__typename":"PostEdges"},{"cursor":6,"node":{"id":14,"title":"Post title 14","content":"Post content 14","__typename":"Post"},"__typename":"PostEdges"},{"cursor":7,"node":{"id":13,"title":"Post title 13","content":"Post content 13","__typename":"Post"},"__typename":"PostEdges"},{"cursor":8,"node":{"id":12,"title":"Post title 12","content":"Post content 12","__typename":"Post"},"__typename":"PostEdges"},{"cursor":9,"node":{"id":11,"title":"Post title 11","content":"Post content 11","__typename":"Post"},"__typename":"PostEdges"}],"pageInfo":{"endCursor":9,"hasNextPage":true,"__typename":"PostPageInfo"},"__typename":"Posts"}}} <= undefined
> mobile: [18:02:09] frontend debug {"data":{"posts":{"totalCount":20,"edges":[{"cursor":0,"node":{"id":20,"title":"Post title 20","content":"Post content 20","__typename":"Post"},"__typename":"PostEdges"},{"cursor":1,"node":{"id":19,"title":"Post title 19","content":"Post content 19","__typename":"Post"},"__typename":"PostEdges"},{"cursor":2,"node":{"id":18,"title":"Post title 18","content":"Post content 18","__typename":"Post"},"__typename":"PostEdges"},{"cursor":3,"node":{"id":17,"title":"Post title 17","content":"Post content 17","__typename":"Post"},"__typename":"PostEdges"},{"cursor":4,"node":{"id":16,"title":"Post title 16","content":"Post content 16","__typename":"Post"},"__typename":"PostEdges"},{"cursor":5,"node":{"id":15,"title":"Post title 15","content":"Post content 15","__typename":"Post"},"__typename":"PostEdges"},{"cursor":6,"node":{"id":14,"title":"Post title 14","content":"Post content 14","__typename":"Post"},"__typename":"PostEdges"},{"cursor":7,"node":{"id":13,"title":"Post title 13","content":"Post content 13","__typename":"Post"},"__typename":"PostEdges"},{"cursor":8,"node":{"id":12,"title":"Post title 12","content":"Post content 12","__typename":"Post"},"__typename":"PostEdges"},{"cursor":9,"node":{"id":11,"title":"Post title 11","content":"Post content 11","__typename":"Post"},"__typename":"PostEdges"}],"pageInfo":{"endCursor":9,"hasNextPage":true,"__typename":"PostPageInfo"},"__typename":"Posts"}}} <= posts({"limit":10,"after":0})
> mobile: [18:02:29] TypeError: TypeError: undefined is not an object (evaluating 'this._panResponder.panHandlers')

**Comment by vlasenko** [comment]
@canercak This is an upstream problem with native-base, please monitor issue resolution there:
https://github.com/GeekyAnts/NativeBase/pull/2840

**Comment by vlasenko** [comment]
The situation is actually worser than I thought. They are not going to "fix" this issue:
https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.0
They deprecate ListView altogether.  We should probably consider utilising:
https://github.com/jemise111/react-native-swipe-list-view
instead...

**Comment by canercak** [comment]
it works now. thank you.
