### ISSUE TITLE
Styles Flash on Rehydration

### ISSUE THREAD

**Issue by lgants** [sysgears/apollo-universal-starter-kit#1174]
**Describe the bug**
Application styles are briefly flashing on rehydration.

**To Reproduce**
1. Go to any page
2. Perform a hard refresh (i.e. on a Mac: cmd + shift + r)
3. The initial paint is correct
4. During hydration, the page flashes with unstyled HTML elements before applying styles

**Expected behavior**
The page shouldn't flash with unstyled components.

**Screenshots**
![2019-12-17 23-09-43 2019-12-17 23_10_39](https://user-images.githubusercontent.com/18373573/71055272-f7e7f500-2122-11ea-9fd9-3ff7f554ac41.gif)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 78

**Smartphone (please complete the following information):**

**Additional context**
I’ve spent a few hours this week on the issue experimenting with ChunkExtractor. Nothing is immediately jumping out at me. I’m still in the process of re-familiarizing myself with the project. And, I’ve got a few more hours I can devote to it this week but, any suggestions would be greatly appreciated.

**Comment by larixer** [comment]
@lgants I assume this happens in development mode, not in production, right? I remember it was a problem of `style-loader` with `sourceMaps` turned on + Safari. You can disable `sourceMaps` for styles, make all `sourceMap: false` there:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/client/webpack.config.js#L63-L86
and check whether this fixes problem for you. 
Also I haven't checked, maybe they finally fixed it in recent `style-loader`, it is worth to try to upgrade it.

**Comment by lgants** [comment]
@larixer thanks for the quick response. you are correct both about this occurring in dev and that bumping  style-loader to 1.0.2 fixes this issue. More info is available here: https://github.com/webpack-contrib/css-loader/issues/613#issuecomment-331754481. Would you like me to create a PR?

**Comment by larixer** [comment]
@lgants Yep, PR would be great, thank you!

**Comment by lgants** [comment]
Whoops. I should've closed this issue when the PR that bumped the dep was merged. Apologies.
