### ISSUE TITLE
Multi Config Setup

### ISSUE THREAD

**Issue by patsa** [sysgears/apollo-universal-starter-kit#1194]
Hey everyone,

I just looked into this awesome repo with an project in mind, which involves using a monorepo with structurally similar (but not identical) apps, which could heavily rely on using the same modules, as is represented in this repo.
But when it comes to define the differences in using the same modules between the different apps with the config, I could not figure out how this could be done in this setup.

The current setup looks like this:
We have the client, server etc. and could possibly duplicate them and create new clients and servers on the base of some of the same modules and some others. But the config is currently not divided between the different instances. Instead it represents a global config, that is applicable for all apps/services.

To talk about a case, which came to my mind directly:
One of the planned apps includes social logins, the other doesn't. I could possibly create a structure within config, that would resemble the structure of modules, where each app/service has it's own subdirectory, but that would just lead to enormous micromanagement, because each setting-file would need to have a subdirectory for each app/service. But that's not the end. I would also have to duplicate the modules to load my app specific settings.

Now the big question: 
Is there a way to inject the settings through the app / service directly instead of duplicating the config files and the correlated modules as well or is there any other way, to handle this problem within the frame of this repo?

Thanks in advance for your help!

Best regards, 
 Patrick

**Comment by larixer** [comment]
@patsa Hi

What about using good old env variables, like it is done for this variable for example in config:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/config/auth.js#L29
?

**Comment by patsa** [comment]
@larixer Well, yeah of course that would be possible. The features could be enabled and disabled by setting env variables. Sometimes the easiest solution is the last thing that comes to your mind.

I would say that is a feasible solution and I will set this to closed.
Thanks @larixer ! 👍
