### ISSUE TITLE
Plans to upgrade to webpack 5

### ISSUE THREAD

**Issue by veeramarni** [sysgears/apollo-universal-starter-kit#1210]
- [ ] I'd be willing to implement this feature

**Is your feature request related to a problem? Please describe.**

Is there a roadmap to upgrade to webpack 5?

**Comment by larixer** [comment]
Nope

**Comment by AlfredOdling** [comment]
> Nope

What's the plan for this repo?

**Comment by larixer** [comment]
| What's the plan for this repo?

@AlfredOdling  We work on the PRs that matter to us: #1203, but we are open to contributions
