### ISSUE TITLE
Why don't we include yarn.lock?

### ISSUE THREAD

**Issue by zirho** [sysgears/apollo-universal-starter-kit#123]
Is there any reason for that?

**Comment by vlasenko** [comment]
@zirho The only reason that people might not use `yarn` and just plain old `npm` and wouldn't need this `yarn.lock` file. But maybe this doesn't make much sense.

**Comment by zirho** [comment]
I see. I think including the `yarn.lock` makes sense when you advise to use yarn in installation instructions. You would not want to mention `yarn` at all if you don't want this file in your repo because they will see yarn.lock change, every time they do `yarn` command. 
I guess adding it to `.gitignore` is not an option, since it will differ dependency versions in deploying process.

**Comment by vlasenko** [comment]
@zirho I don't like the idea of including generated files of various tools into source code. `yarn.lock` is a big generated file of `yarn` tool. Yes, we support `yarn` and `npm`, we support IntelliJ, Eclipse, vi and Atom in the same sense, but we are not going to include the generated files of these tools.

**Comment by zirho** [comment]
I have a different opinion on that, but it would be more like preference. 

Look at these most popular Open-source projects.
https://github.com/facebook/react
https://github.com/reactjs/redux
I'm not telling you those two includes all kinds of config or preference files in their repo.

My reasoning is this.
Open-source project is made for anyone who use all kinds of different editors, IDEs or platforms.
To mitigate the pain to setup a development environment on every different setups, those file are needed.

So if you insist not to include yarn.lock, you would want to drop the yarn instruction in README.md because anyone who makes a PR with yarn installed setup, will probably include yarn.lock in their commits.

**Comment by langpavel** [comment]
yarn.lock is not needed for yarn. This file only guarantee package versions in production. I'm sure it have it's role in development too.
When some package breaks it's semver versioning, all dependants are affected. yarn.lock is one protection against this more rarely situations over time. Just for clarification.

Including yarn lockfile is recommended by yarn for good reason. You can at every time check if you are using different deps and if you fall back to ones where everything works, you can blame yourself cleanly..

**Comment by vlasenko** [comment]
@langpavel Thanks for clarifications Pavel. Do you think it was a good decision to include `yarn.lock` into your starter kit, did it has visible benefit? :)

**Comment by vlasenko** [comment]
@zirho Lets try it. I will try to include `yarn.lock` over weekend, I suspect that it might affect Travis and Heroku setup, so I will need time to check that they work as before. After that we will see how it feels to have `yarn.lock` in the repo and what are the pros and cons of this approach

**Comment by vlasenko** [comment]
@zirho @langpavel Okay, I took first look at including `yarn.lock` and the problem is including `yarn.lock` will break Travis builds of Greenkeeper for this repo. Please see this issue:
https://github.com/greenkeeperio/greenkeeper/issues/314
We need to wait until that issue will be resolved. 

Working Greenkeeper is more important than `yarn.lock`, because `yarn.lock` tries to `freeze` package versions to prevent semver versioning breakage, whereas Greenkeeper actually REVEALS if this breakage happens in any package we are using and immediately reports this to us.
