### ISSUE TITLE
Demo app link on the readme file not working

### ISSUE THREAD

**Issue by erandakarachchi** [sysgears/apollo-universal-starter-kit#1233]
**Describe the bug**
Demo app link used in the readme file is not working.

**To Reproduce**
1. Click on the link of the demo application link on readme file.
2. Go to the web and see the demo app is not working.

**Expected behavior**
Demo app should be working.

**Screenshots**
![image](https://github.com/sysgears/apollo-universal-starter-kit/assets/60935597/bbdac7c4-222e-4f81-bef4-c27448311757)
![image](https://github.com/sysgears/apollo-universal-starter-kit/assets/60935597/da81792a-ca40-46cb-89c8-5fd65cb90e9a)

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser: Microsoft Edge 
 - Version: Version 113.0.1774.57 (Official build) (64-bit)

**Comment by larixer** [comment]
Unfortunately, Heroku has removed free plan that this starter kit relied upon for demo app:
https://blog.heroku.com/next-chapter
We need to seek alternative solution in order to host the demo...

**Comment by larixer** [comment]
@erandakarachchi This is fixed now via:
https://github.com/sysgears/apollo-universal-starter-kit/commit/c9b0e81a07f9d729df19fca1b64fdc7ce3720d92
The demo app is published on https://render.com/ at:
https://ausk.onrender.com

**Comment by erandakarachchi** [comment]
Thanks and great work @larixer
