### ISSUE TITLE
Add various tests to the kit

### ISSUE THREAD

**Issue by vlasenko** [sysgears/apollo-universal-starter-kit#139]
Add React component tests, database access tests, etc so that users of the kit have opportunity to start covering their own applications with tests easier by looking on examples.

**Comment by mitjade** [comment]
I meant to do this for the post example, but if anyone else is willing to help out with this, would really appreciate it.

**Comment by vlasenko** [comment]
Implemented fast integration tests for Counter:
https://github.com/sysgears/apollo-fullstack-starter-kit/pull/143

**Comment by vlasenko** [comment]
Implemented server-side integration tests for Counter GraphQL API:
https://github.com/sysgears/apollo-fullstack-starter-kit/pull/144

**Comment by vlasenko** [comment]
Basic integrations tests have been added. For other test types separate issues will be opened as needed
