### ISSUE TITLE
How do we successfully add CSS and Javascript file from 3rd Party CSS Framework into this Project?

### ISSUE THREAD

**Issue by hhashmi** [sysgears/apollo-universal-starter-kit#170]
I have to integrate a design template into my current project.
That design template is built some 3rd party CSS and JS frameworks like
jQuery, bootstrap, jqGrid and etc

how can I use their CSS and JS files in my current project?

**Comment by hhashmi** [comment]
following are the lines in design template I need to use OR translate for my current project





	<script type="text/javascript">
		window.jQuery || document.write("<script src='assets/js/jquery.js'>"+"<"+"/script>");
	</script>




<script type="text/javascript">
	if('ontouchstart' in document.documentElement) document.write("<script src='assets/js/jquery.mobile.custom.js'>"+"<"+"/script>");
</script>


<script src="assets/js/bootstrap.js"></script>
<script src="assets/js/jquery-ui.custom.js"></script>
<script src="assets/js/jquery.ui.touch-punch.js"></script>
<script src="assets/js/chosen.jquery.js"></script>

<script src="assets/js/ace/elements.scroller.js"></script>
<script src="assets/js/ace/elements.typeahead.js"></script>
<script src="assets/js/ace/ace.js"></script>
<script src="assets/js/ace/ace.searchbox-autocomplete.js"></script>

<script src="assets/js/owl.carousel.js"></script>
<script src="assets/js/custom.init.js"></script>
<script src="assets/js/custom.init.form.js"></script>
<script src="assets/js/ace-extra.js"></script>

**Comment by vlasenko** [comment]
@hhashmi Closing as inappropriate. We do not provide support for your project, only for this starter kit.

**Comment by sakhmedbayev** [comment]
@hhashmi I know this issue was closed as inappropriate, but I am facing thing problem - cannot figure out right way to integrate third party assets. Have you managed to do it? If so, can you please share?

**Comment by vlasenko** [comment]
@sakhmedbayev @hhashmi I believe the problem with including 3rd party css styles should be finally resolved now via: https://github.com/sysgears/apollo-universal-starter-kit/commit/36ad9fd985d7b930ce805142e0501f3e36e84851 and
https://github.com/sysgears/spinjs/commit/310fa92f8b953be0f425d6f18cc87b4d9198d666

**Comment by sakhmedbayev** [comment]
Thank you @vlasenko for letting us know. Happy Thanksgiving :)

**Comment by vlasenko** [comment]
Happy Thanksgiving @sakhmedbayev :)

**Comment by bamne123** [comment]
@sakhmedbayev were you able to get jQuery working???

**Comment by bamne123** [comment]
Can you share details? 
I am stuck with JQuery and JS files not working.

**Comment by sakhmedbayev** [comment]
Just place your files in the favicon module and use them from there.
