### ISSUE TITLE
Integrate React Native and Expo for Android and iOS native apps development

### ISSUE THREAD

**Issue by vlasenko** [sysgears/apollo-universal-starter-kit#185]
It would be nice to see React Native and Expo native mobile application development support in this starter kit with utilizing Webpack infrastructure benefits for code sharing between backend, web frontend and mobile frontends for iOS and Android

**Comment by vlasenko** [comment]
This is a challenging feature, but from the brief look at Expo, React Native and previous attempts to integrate with Webpack at the moment I think it is doable and maintenance costs should be bearable.

**Comment by mairh** [comment]
It would be really amazing to run the GraphQL backend on a separate node and use the same server for `react-native` app.

**Comment by vlasenko** [comment]
So the idea to integrate React Native and Expo is via hybrid approach. We can use Expo entry code compiled with React Native package manager as is done by Expo, but we will not include into this entry actual application code directly.The React Native package manager runs webserver with in-memory bundle for application entry, it understand how to package Haste modules used by `react-native` and perhaps `expo`. 

We start our own webpack-dev-server that mimicks React Native webserver but adds application code compiled by webpack to the initial bundle for Expo entry code generated by React Native packager. We will override Expo XDL library endpoint for React Native webserver to point to our webpack-dev-server and it should do the trick

**Comment by mitjade** [comment]
Sounds great! I am really exited for the possibility of this addition and can't wait to start porting post/comment example to react native and see how much code can be reused.

Will look into [react-native-web](https://github.com/necolas/react-native-web), if this could help in making more code reusable.

**Comment by vlasenko** [comment]
During investigation I have found this project:
https://github.com/callstack-io/haul
which comes very near to what we need, though not at 100%, but very close

**Comment by mitjade** [comment]
Looks awsome and it is actively maintained, which is also positive.

**Comment by vlasenko** [comment]
I have opened issue about exposing Haul as a library, right now its slightly complicated to access Haul in a programmatic way in our project, but still possible. If Haul were exposed as a library we could integrate it very easily:
https://github.com/callstack-io/haul/issues/155

**Comment by vlasenko** [comment]
Closing this now, as basic support has been added. Of course a lot more work needed to polish it, which will be covered by Roadmap steps or specific issues. Thank you everyone for discussion and help with this!
