### ISSUE TITLE
Proper way to use fragments in graphql queries in the client

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-universal-starter-kit#218]
What is a proper way to add new fragment to a graphql query on the client side?
I added a new module, similar to the "Post" module, the "Blog" module. The backend for this module is set and working properly. However, when I added some fragments for graphql queries on the client side in  `src/client/modules/blog/graphql` directory, webpack could not compile project anymore, throwing this error:

    if (def.kind === 'FragmentDefinition') {
                         ^

    TypeError: Cannot read property 'kind' of undefined

**Comment by mairh** [comment]
how does your `graphql/blog.graphql` file looks like?

Also, could you paste the query you are trying to execute?

**Comment by vlasenko** [comment]
Closing due to issue creator inactivity
