### ISSUE TITLE
Client side

### ISSUE THREAD

**Issue by zunder** [sysgears/apollo-universal-starter-kit#236]
I am wondering if there is any chance for obtaining the starter kit containing only the client side implementation?

**Comment by vlasenko** [comment]
@zunder Yes. To use external backend set `serverConfig.url` at `tools/webpack.app_config.js`. After you do this backend part will not be compiled via Webpack anymore and external GraphQL backend at given endpoint will be used.

**Comment by zunder** [comment]
@vlasenko Nice, thank you for the hint! Is there also a list describing all the modules used by the server only? I would prefer a project with minimum dependencies only including the client stuff.

**Comment by vlasenko** [comment]
@zunder Yes, the list is in the same file `tools/webpack.app_config.js`. Those deps marked with `server` only are used for backend
