### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by zunder** [sysgears/apollo-universal-starter-kit#244]
This is more of a question of how to do it myself, rather than an actual request. I've been wondering what has to be done in order to provide support for Typescript. As for my understanding using Haul should make this task possible with RN. Unfortunately there is little to non example available for accomplishing this task. What I could do for now is using tsc in order to compile .ts files into the appropriate folders. A perfect solution would be using the `awesome-typescript-loader` or `ts-loader` with an appropriate Webpack rule. There is also a `react-native-typescript-transformer` available, but according to its documentation it is only valid for RN >= 0.45 which is not the case for this starter-kit. Any hints on achieving this task?

**Comment by vlasenko** [comment]
At some point in the past I have ported this starter kit to TypeScript, but after fighting with TypeScript for a while I decided to go with `flow` instead. The problem with using TypeScript for web apps and mobile apps with lots of dependencies is that TypeScript enforces that all deps supported it and this is usually not the case for non trivial web apps. Flow is much better in this respect as it doesn't enforce you to use it for all the deps, only for the deps and parts of code that want to use flow checks.

**Comment by vlasenko** [comment]
So if you want type checking why not just go with `flow` which is the most React-friendly type checker. And if you want to enforce types at runtime too, not only at compile time, just add https://github.com/gcanti/babel-plugin-tcomb to babel plugins at `webpack.config.js`

**Comment by zunder** [comment]
I agree on those points and to tell the truth we were discussing on wether or not to use flow or typescript. The decision did fall in typescript's favor, so I need to have a look on ways of getting it working with the toolchain. Is this port of yours still available somewhere so I could take a brief look at it?

**Comment by vlasenko** [comment]
I don't think that old port is much relevant now, it was very outdated and was done when this starter kit didn't support React Native. The primary problems were not with enabling `awesome-typescript-loader` for Webpack, this is easy, as well as adding tslint, etc. But there were problems with Apollo libs itself, I had to always invent workarounds for Apollo libs to work with TypeScript code, I have even submitted some PRs to Apollo to fix this. Right now the Apollo libs were moved forward and they have new issues with TypeScript that require new workarounds:
https://github.com/apollographql/graphql-subscriptions/issues/77

If someone appears who wants to maintain a branch of this starter kit to support TypeScript and who will work to improve Apollo's support of TypeScript users that is fine with us, we will try to help. But this is not the thing we are ready to jump into ourselves at the moment, we have plenty other ideas to implement first.

**Comment by zunder** [comment]
Alright, I will try to integrate the kit in Typescript in our system first and see if I can help out maintaining such a branch here. I agree that there are more important things to this project especially the react-navigation integration and splitting into Lerna packages. Can't wait for those changes to be released. Thank you for your work!
