### ISSUE TITLE
HCR opens a new browser if backend url specified

### ISSUE THREAD

**Issue by zunder** [sysgears/apollo-universal-starter-kit#245]
Steps to reproduce:

Uncomment the url in webpack.app_config.js:
```
const serverConfig = {
  url: 'http://localhost:8080/graphql',
  entry: {
     ...
  }
};
```

Start by launching `npm run watch`. Go to `localhost:3000`. Make a change in e.g. `counter_show.web.jsx`. Save the change. A new browser window will open instead of only reloading the module in current one. This does not happen if you use build-in server.

**Comment by zunder** [comment]
@vlasenko Could have figured that one myself.. Thank you for the quick fix!

**Comment by vlasenko** [comment]
@zunder You are welcome!
