### ISSUE TITLE
Are we interested in docker?

### ISSUE THREAD

**Issue by zirho** [sysgears/apollo-universal-starter-kit#250]
I'm trying to deploy my app built on this boilerplate to docker cloud. 

It looks package.json dependencies are not organized by NODE_ENV, so that docker builder can get all the deps for a building environment.

Is it a common practice to install devDeps when building deployable docker image?

Thanks!

**Comment by vlasenko** [comment]
@zirho I'm not sure what do you mean dependencies are not organized by NODE_ENV and how is it related to docker and to what `docker builder` do you refer? Please clarify what tools do you exactly use and what problems do you have with those tools

**Comment by zirho** [comment]
Oh, sorry about that.

I have a Dockerfile to build deployment docker image which set NODE_ENV=production.
Which makes `yarn install` only installs production deps.
Which makes build fail.

I think I can just not set NODE_ENV so that it installs all deps for the build process.

Am I using it right?

**Comment by vlasenko** [comment]
@zirho Yes, we might need to fix the docs here:
https://github.com/sysgears/apollo-universal-starter-kit#user-content-deploying-to-linux-running-nodejs
Only `yarn seed` step must set NODE_ENV=production all the other steps must not set NODE_ENV

Well, the last step when you run the built app via `yarn start` or `node build/server` might need to have NODE_ENV=production set as well

**Comment by zirho** [comment]
@vlasenko 

It seems it needs some adjustment for a seamless CICD with docker cloud.
Thanks for the help.

This project seems going really great. It's kinda hard to catch up!

Good work guys, I really appreciated it!
