### ISSUE TITLE
The example: the counter is not updated when switching "Apollo Starter Kit" and "Posts"

### ISSUE THREAD

**Issue by xtringo** [sysgears/apollo-universal-starter-kit#258]
Greetings,
I observed the counter is not updated. The following are my steps:

1. Start `Yarn watch`
2. In browser, open 2 Tabs http://localhost:3000/ (resize 2 windows to observe the result easier)
3. In the first tab, press button "**Click to increase count**". Both counters in 2 tabs are increased. This is the expectation.
4. In the second tab, open the "**Posts**" list (top nav bar)
    In the first tab, press button "**Click to increase count**".
5. In the second tab, open the "**Apollo Starter Kit**" list (top nav bar).
Now, the counters in 2 tabs are different. Is this also expected behavior of the example?

**Comment by vlasenko** [comment]
@xtringo Yes, it is expected behavior of the example. Because we are subscribing to counter updates only on counter page and unsubscribing when you leave the page. If you want your scenario to work we probable should force fetch the latest counter value on counter page entering.

**Comment by mitjade** [comment]
I use something like this:
```
  graphql(POSTS_QUERY, {
    options: () => {
      return {
        fetchPolicy: 'cache-and-network',
        variables: { limit: 10, after: 0 },
      };
    },
```
It will make an additional request to the server every time you go back to the page, but you will not see any changes if result is the same.
