### ISSUE TITLE
Add basic filtering and sorting options to the post list page

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-universal-starter-kit#268]
First of all, let me thank you for this awesome kit. I am really happy to discover it!

This issue is not really an issue, but rather a feature suggestion. I just want to propose to include a basic filtering and sorting options on the post list page. For instance, kit can feature a filter that allows users to filter posts which have more than 2 or 3 comments and sort the list by posts' titles. I think this feature is worth to add since it is common feature for any list view.

**Comment by mitjade** [comment]
I agree this could be a nice addition to this example. Will add it to the roadmap.

**Comment by mairh** [comment]
We could add search feature too along with filter and sorting feature for further improvement.

**Comment by mitjade** [comment]
#420

**Comment by mitjade** [comment]
#420 Has been merged, that has this implemented. Please login as `admin@example.com:admin` and go to `Users` page to see it in action. Documentation will be added a bi later.
