### ISSUE TITLE
Using a separate GraphQL service?

### ISSUE THREAD

**Issue by claym** [sysgears/apollo-universal-starter-kit#276]
What's the proper method for disconnecting the front end components from the backend GraphQL server and database?

Basically, pointing to the preferred service and preventing the other ones from starting up?

Thanks!

**Comment by vlasenko** [comment]
@claym This is the most frequently asked question. The proper method is to uncomment the line:
https://github.com/sysgears/apollo-universal-starter-kit/blob/c8064dc5996829e08c3e05cfe4f62ff64a42e08f/tools/webpack.app_config.js#L4

Pull Request to make answer to this question intuitive is more then welcome

**Comment by claym** [comment]
Ah, and the rest of the system is smart enough to go "oh, don't need start the graphql server"?

Would this work with something like Graph.cool? it appears to be trying to connect to wss://api.graph.cool/<endpoint> and failing out.

**Comment by vlasenko** [comment]
@claym Yes the rest of the kit is smart about this `url` param.

Yes it should work with graph.cool, but there is one gotcha. Recent Apollo versions recommend to use websockets protocol over HTTP, so this starter kit switched to websockets both for subscriptions and queries/mutations. I don't know whether `graph.cool` exposes `websocket` endpoint for queries and mutations or not yet?

**Comment by vlasenko** [comment]
@claym Check this issue:
https://github.com/apollographql/subscriptions-transport-ws/issues/169

Right now we are using never WebSocket transport option, but if `graph.cool` doesn't support it, I think we should rollback to older Hybrid transport option, this is not difficult, we should rollback this commit for `main.jsx` to return to `Hybrid` transport which should be compatible with all GraphQL backends:
https://github.com/sysgears/apollo-universal-starter-kit/commit/a6b36f7246d1b40ecab14c1d2c50a9bdd016d253#diff-362f0c994b80043b94a5d3de967ad801

**Comment by vlasenko** [comment]
@claym Ok, I have rolled back to `Hybrid` transport approach which should be comatible with `graph.cool` for sure, please reopen this issue if you will see any problems with Graph.cool

**Comment by claym** [comment]
So, what I'm seeing now is that the system keeps trying to make websocket connections even if previous ones fail and the fetch request was successful

![image](https://user-images.githubusercontent.com/230486/27999111-e920a418-64e6-11e7-8e24-fb68165c4d15.png)

I'm not sure if I've enabled some subscription service accidentally on a new module, or this is expected behavior.

**Comment by vlasenko** [comment]
@claym This is expected:
https://github.com/sysgears/apollo-universal-starter-kit/blob/2c2e0360cf495573aabb5c109a6e34f605663d90/src/client/app/main.jsx#L32

**Comment by claym** [comment]
Will it melt anything if I turn reconnect off?

**Comment by vlasenko** [comment]
@claym Please clarify what exact question do you have about starter kit. Questions like "Will it melt anything if I turn reconnect off?" are too vague and considered offtopic here.

**Comment by claym** [comment]
I was asking if there were any unexpected consequences if you change the value of reconnect to false in the code you linked to above.

**Comment by vlasenko** [comment]
@claym Unexpected consequences - no.

**Comment by davidyin1212** [comment]
@vlasenko what about with the new webpackAppConfig.js where should the url go now?

**Comment by vlasenko** [comment]
@davidyin1212 You can use `backendUrl` option now:
https://github.com/sysgears/apollo-universal-starter-kit#configuring-starter-kit
You can also set `backendUrl` per each builder in `.spinrc.json`
