### ISSUE TITLE
Google Analytics issue

### ISSUE THREAD

**Issue by zirho** [sysgears/apollo-universal-starter-kit#278]
Hi all, 

Based on my research and Google Tag Assistant, react-ga does not get fired when a user gets a server-rendered page. (the first load)

I tried to see if this works correctly using this tool.
https://get.google.com/tagassistant/

While react app being rendered in node (server side), does it fire the tracking directly to GA?
Is that why I cannot see the tracking request being fired on Chrome extension?

Thanks!

**Comment by vlasenko** [comment]
I don't see clear issue description here. Are you sure this an issue of this starter kit. If yes, what is wrong with the starter kit and what are exact steps to reproduce it?

Closing until description of the problem in the starter kit will be provided together with reproduction steps.

**Comment by zirho** [comment]
Hi Victor,

Here's how to verify it's not working.
This is my personal blog which GA is properly setup. 
You can see the it is properly loading analytics.js and fire the initial call for the page.

![image](https://user-images.githubusercontent.com/1251296/28055278-1c754ddc-65cd-11e7-949e-8a21de5fb32a.png)


Here's what we got from plain starter kit.
It loads up `analytics.js` but not firing the initial request.

![image](https://user-images.githubusercontent.com/1251296/28055314-3db94052-65cd-11e7-9c0f-9a0f34fd37ae.png)

If I click any link in the page, it fires the tracking request.
![image](https://user-images.githubusercontent.com/1251296/28055347-5f5fbc40-65cd-11e7-8dc0-895c7423e1c7.png)

I tried to find a fix for it in react-ga project but couldn't find one.
But I found similar thread here
https://github.com/erikras/react-redux-universal-hot-example/issues/886

**Comment by vlasenko** [comment]
https://github.com/sysgears/apollo-universal-starter-kit/blob/cc4c1fb4d1a00ab702f7c8141d3b302fefeccd10/src/client/app/main.jsx#L60-L63

I guess adding the lines:
``` js
ReactGA.set({ page: window.location.pathname });
ReactGA.pageview(window.location.pathname);
```
below 
``` js
ReactGA.initialize('UA-000000-01');
```
will fix the problem.

Better yet to have a function:
``` js
const logPageView = () => {
  ReactGA.set({ page: window.location.pathname });
  ReactGA.pageview(window.location.pathname);
};
```
and call this function both after `ReactGA.initialize` and inside `history` listener

**Comment by zirho** [comment]
Awesome! Thank you
