### ISSUE TITLE
Running over https

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-universal-starter-kit#285]
After https://github.com/sysgears/apollo-universal-starter-kit/commit/cc4c1fb4d1a00ab702f7c8141d3b302fefeccd10, I have problems running in production over `https`.

I have node running on localhost and then have proxy setup on `ngnix` to run over `https`.

Any ideas how to solve this?

**Comment by mitjade** [comment]
I still have the following problems:
```
(index):1 WebSocket connection to 'ws://localhost:8080/graphql' failed: WebSocket is closed before the connection is established.
```

and 
```
Mixed Content: The page at 'https://XXX' was loaded over HTTPS, but requested an insecure resource 'http://localhost:8080/graphql'. This request has been blocked; the content must be served over HTTPS.
t.batchedFetchFromRemoteEndpoint @ vendor.b17cb84….js:11
(anonymous) @ vendor.b17cb84….js:11
vendor.b17cb84….js:11 Unhandled (in react-apollo) Error: Network error: Failed to fetch
    at new t (https://XXX/vendor.b17cb84571ce81646c86.js:11:365974)
    at t.currentResult (https://builder.impera.si/vendor.b17cb84571ce81646c86.js:11:367666)
    at u.dataForChild (https://XXX/vendor.b17cb84571ce81646c86.js:11:165419)
    at u.render (https://XXX/vendor.b17cb84571ce81646c86.js:11:166054)
    at f._renderValidatedComponentWithoutOwnerOrContext (https://XXX/vendor.b17cb84571ce81646c86.js:25:780746)
    at f._renderValidatedComponent (https://XXX/vendor.b17cb84571ce81646c86.js:25:780873)
    at f._updateRenderedComponent (https://XXX/vendor.b17cb84571ce81646c86.js:25:780177)
    at f._performComponentUpdate (https://XXX/vendor.b17cb84571ce81646c86.js:25:779978)
    at f.updateComponent (https://XXX/vendor.b17cb84571ce81646c86.js:25:779256)
    at f.performUpdateIfNecessary (https://XXX/vendor.b17cb84571ce81646c86.js:25:778589)
(anonymous) @ vendor.b17cb84….js:11
```

Second one pops up whenever I go to a different page.

**Comment by vlasenko** [comment]
@mitjade Yes, I'm looking right now

**Comment by vlasenko** [comment]
@mitjade I have rewritten last commit multiple times. So with the last edition it should work with production:
https://github.com/sysgears/apollo-universal-starter-kit/commit/c7be2f2f9c03115d7ffa4ebfd26213b6c233fdf3

**Comment by mitjade** [comment]
Second problem is gone now.

Subscriptions are still not working for me, am still investigating.
So the first warning is still there, but now through `wss` as it should be:
`WebSocket connection to 'wss://XXX/graphql' failed: WebSocket is closed before the connection is established.`

**Comment by vlasenko** [comment]
@mitjade Is this line (specifically port part) correct `wss://XXX/graphql` ?

**Comment by mitjade** [comment]
No port is shown, that might be the problem.

**Comment by mitjade** [comment]
`window.location.origin` returns the webpage url aka `https://example.com`. Not sure hot this worked before?

**Comment by vlasenko** [comment]
I think it was working the same
https://github.com/sysgears/apollo-universal-starter-kit/commit/cc4c1fb4d1a00ab702f7c8141d3b302fefeccd10

**Comment by mitjade** [comment]
I guess this is missing `.replace(':' + settings.webpackDevPort, ':' + settings.apiPort)`

**Comment by vlasenko** [comment]
It is only relevant in __DEV__ mode

**Comment by vlasenko** [comment]
Well I can take `window.location.url` and then substitude server port into it. It should probably fix things for you, but I'm not sure how it was working for you before :)

**Comment by mitjade** [comment]
Seems to be working now!

Just stopped and started the backend?

**Comment by vlasenko** [comment]
@mitjade Okay, it should work, because the logic should be the same in prod mode as it were before. Only the logic in `__DEV__` mode is new

**Comment by vlasenko** [comment]
@mitjade Mitja should we close this or are you still checking?

**Comment by vlasenko** [comment]
Closing for now, reopen if this fix still doesn't work for you
