### ISSUE TITLE
Feature Discussion: CSS Modules?

### ISSUE THREAD

**Issue by justinr1234** [sysgears/apollo-universal-starter-kit#293]
Have you ever considered CSS modules for this project? Curious on thoughts.

https://github.com/css-modules/css-modules
https://github.com/gajus/react-css-modules

**Comment by vlasenko** [comment]
This project is using Styled Components: 
https://github.com/styled-components/styled-components
We consider them to be superior then CSS modules

**Comment by justinr1234** [comment]
Sure, just curious the reasoning here. Not telling you that you should use modules, just trying to understand the decisions made. Thanks!

**Comment by vlasenko** [comment]
The reasoning is that there was request to switch to Styled Components from Glamor and authors agree that this will be beneficial enhancement:
https://github.com/sysgears/apollo-universal-starter-kit/issues/93

What is the reasoning to switch over to CSS modules from Styled Components? I have heard and read about CSS modules before, but didn't delve into studying them too much. I'm not sure why they can be a better alternative then Styled Components.

**Comment by vlasenko** [comment]
Closing due to topic starter inactivity.
