### ISSUE TITLE
Could you support Join Monster instead of "dataloader"?

### ISSUE THREAD

**Issue by MichelDiz** [sysgears/apollo-universal-starter-kit#306]
This
http://join-monster.readthedocs.io/en/latest/

best regards

**Comment by vlasenko** [comment]
@MichelDiz Yes, Pull Request is welcomed

**Comment by MichelDiz** [comment]
I'm having trouble understanding the flow of modules (Working on it.). I have to tag the scheme's implementation. I could do this regardless of the template created for the modules. But to do something native to your project you would have to understand the concept (flow) of modulation that you use to fit the Join monster natively. And so you can generate a join monster for each module individually.

**Comment by vlasenko** [comment]
@MichelDiz Perhaps discussing modules in our chat will help you?
https://gitter.im/sysgears/apollo-fullstack-starter-kit

**Comment by vlasenko** [comment]
@MichelDiz Modules in this kit are application features. Each `modules` folder has a collection of similair features. We mostly use modules to implement routes of the application, both server implementation for the route and client side implementation for the route. Each feature registers itself to the application by creating an instance of connector interface class: `modules/connector.js`. Connector interface class should also support creating feature from the collection of features, to support aggregation of features, the aggregated feature is exported by `modules/index.js`. Then downwards in the starter kit code we usually import `modules/index.js` and use this aggregated feature through its connector interface.

Connector interface class is application-specific. But we provide example for client-side routes connector and server-side routes connector with the starter kit. One can use this concept not only with routes but with other collections of features that behave similar.

**Comment by vlasenko** [comment]
@MichelDiz I'm going to create blog post soon about this module-features pattern, to explain it more thoroughly.

**Comment by MichelDiz** [comment]
Let me abuse your attention one more time.

I have to get access to ("raw") "Schema" so the adapter use it to Apollo and create a loop with this function below:

```js
Module.exports = function joinMonsterAdapt (schema, jmConfigs) {
  For (let typeName in jmConfigs) {
    // get the type definition from the schema
    Const type = schema._typeMap [typeName]
    Assert (type, `Type with name $ {typeName} not found in schema.`)
    // and transfer some properties over from the passed join monster config
    DecorateType (type, jmConfigs [typeName])
  }
}

```

It turns out that the module flow does not return only the "schema" I need. It creates an array with a context and so on. Forgive me if I am being very unintelligible. I'm kind of new to the JS world. I have always used JS for basic things on the daily. And not as the main language. You module approach is also new for me.

Knowing that Join Monster will create a query in SQL. I think it should be integrated into the SQL.js file of the folders. But for this I would have to create some "callback" for the "raw schema" of this module individually. And finally create a template as part of cli to be native, right?

I also have very little time available to devote to "reverse engineering" and Studies focused on JS (i'm dedicating myself a lot), I'm doing my best to study your kit, which is wonderful. I really enjoyed the organization and even the idea of ​​the modules like that. But I need to methodically understand how to use it on daily.

I think this what I just wrote may perhaps serve as feedback for your blog post. That I'll be waiting.

Best Regards.

**Comment by vlasenko** [comment]
@MichelDiz Okay, feature-modules is an abstract concept. Schema of a feature within current implementation is an array of AST (abstract syntax tree) schemas. What you are doing in your function is iteration over single AST schema. Feature-modules don't enforce the format of GraphQL schemas, this AST schema format comes from `graphql-tag` loader. I just know this and can answer your question, this has nothing to do with feature-modules concept. I still recommend you to just ask questions in the chat, but its fine to ask questions in issues too.

So to make your function work, you need to modify it, since `schema` that you get from feature modules is really schema array, so just iterate over this array and do your thing for each schema in the array and you are done.

**Comment by MichelDiz** [comment]
I solved the issue (but I have not made Pull Request yet - in time I do) but it follows what I did to make the Kit compatible with Join Monster.

And everything is working perfectly. The advantages of Join Monster is being able to generate an SQl in the exact way you need or what the Client version needs. Making in a single request of any complex query that comes.

There is no secret in reality, to implement this.

There is no need to change anything. At least for a while. If anyone wants to use Join Monster for free will and spontaneously. But If you are going to add Join Monster to the project natively. Completely eliminating the "Dataloader". It would have to be evaluated.

So, I created a simple module
> Yarn cli addmodule mymodule

First I created a new instance to use Mysql / MariaDB
I installed yarn add Mysql2 - Then I added the settings to knexdata.js

```js
Export const developmentMysql2 = {
  Client: 'mysql2',
  Connection: {
    Host: '127.0.0.1',
    User: 'root',
 Charset: 'utf8',
    Password: 'MyTempPass',
    Database: 'MyDataBase'
  },
  Debug: true,
  UseNullAsDefault: true
};

```

From there inside the src / sql / connector.js I added the following to connect my new MySQL instance:

```js
Export const mySql2 = require ('knex') (environments.developmentMysql2);

If (knex) {
  Console.log ("=====> Knex Connected!");
} Else {
  Console.log ("=====> Knex Connection Failed");
}

If (mySql2) {
  Console.log ("=====> Knex Connected! MySql2");
} Else {
  Console.log ("=====> Knex Connection Failed mySql2");
}
```

I created a file named "joinMonsterMetadata.js" inside the middleware folder that will tag my Types. And I filled in with:


```js
Query: {
    Fields: {
     // example 1
     GetUserByID: {
        Where: (table, {id_user}) => `$ {table} .id_user = $ {id_user}`,
       } // I apply a condition generated by Join monster
      }
  },
User:
    // map the User object to its SQL table
    SqlTable: 'ps_user',
    UniqueKey: 'id_user',
    // tag the User's fields
    Fields: {
   All fields / columns I need from the database or joins
}


```

Inside middleware / graphql.js I added:

```js
Import joinMonsterMetadata from './joinMonsterMetadata'; // After "import modules"

JoinMonsterAdapt (schema, joinMonsterMetadata); // to the bottom of the page

```
Within Resolvers I added:

```js
Import {GraphQLDate} from "graphql-iso-date";
Const joinMonster = require ('join-monster').

Query: {

AllUsers (parent, args, context, resolverInfo) {
              Return joinMonster (resolveInfo, context, sql => {
                Return context.Mymodule.gtallUsers (sql) .then (result => result [0]);
              }, {Dialect: 'mysql'}); // very important for JoinMonster and Knex compatibility.
          },
},

 Date: GraphQLDate, // To solve problems with dates types

```

Within schema.graphqls I did:

```
#Use this if you wanna use Dates values in types.
Scalar Date

Type User {

All types that I need go here ...
}

Extend type Query {
    AllUsers: [User!]!
    GetUserByID (id: String!): User
}

```
Within SLQ.js I did:
```js
// I created a connection to the new instance and changed the alias to a friendly name.
Import {mySql2 as knex} from '../../../server/sql/connector';


Export default class Mymodule {
Async gtallUsers (sql) {
        Return knex.raw (sql);//Will simply pass raw queries made by Join Monster
  }

}
```

**Comment by mitjade** [comment]
I checked out Join Monster and I like it. Would you be willing to redo `Post` example to use it instead of `Dataloader`?

I will reopen this issue and add this to the roadmap.

**Comment by MichelDiz** [comment]
I changed the Post query. In time I will change the rest of the code.
https://github.com/MichelDiz/apollo-universal-starter-kit/commit/ee6fd689d4d7d2bf90cc5298b499db9afdfdeb03

**Comment by mitjade** [comment]
@MichelDiz Nice work! Why not change the post example it self and not make a separate module?

**Comment by MichelDiz** [comment]
Well, I'm trying to follow the logic of the previous code first. I'm doing it just so I do not break anything. Then it would be just to reuse the work and change the "names".

**Comment by mitjade** [comment]
@MichelDiz Great! Looking forward to it.

**Comment by mitjade** [comment]
@MichelDiz Why not use it just for select statments? What do you gain if used with mutations?

**Comment by MichelDiz** [comment]
I thought in change the post completely. Because complex mutations could be made in one single batch. And generating SQL dynamically pelo join-monster.

**Comment by mitjade** [comment]
@MichelDiz Ok, looks like I need to reed into JoinMonster a bit more :)

**Comment by mitjade** [comment]
@MichelDiz I tried to make JoinMonster work with relay style pagination and it looks like it does not support `sqlite3`, so I guess it is not appropriate for this kit.

**Comment by MichelDiz** [comment]
Did you tried the way they do? https://join-monster.readthedocs.io/en/latest/pagination/
is different, but the goal is the same. sqlite3 is supported. Because it is found in the documentation as being supported.

**Comment by mitjade** [comment]
Tried to use `join monster` on an existing project and it in the end created more problems than in solves. I really like the idea if it, but I think it is not yet ready to be added to this kit.

Will close this for now and revisit this later on.
