### ISSUE TITLE
Does this starter support media queries if building for both native AND web?

### ISSUE THREAD

**Issue by sjl2024** [sysgears/apollo-universal-starter-kit#309]
Or is that one of the limitations of combining react-native and react libs in a write once/deploy everywhere fashion? How do media queries function in react-native alone? Is it possible to write media queries once and deploy them to both platforms and they'll work as expected?

**Comment by vlasenko** [comment]
@sjl2024 React Native doesn't support media queries natively, but workarounds exist:
https://github.com/vitalets/react-native-extended-stylesheet#media-queries
https://github.com/adbayb/react-native-responsive

We are using `react-native-web` for supporting `react-native` components on the web, here is the info about media queries support in `react-native-web`:
https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md#user-content-what-about-media-queries

So media queries are not supported universally on each platform, but they generally should not be needed and other mechanism exist to make design responsive, as outlined in `react-native-web` FAQ answer above.
