### ISSUE TITLE
Help wanted: cryptic createContext()

### ISSUE THREAD

**Issue by ChingxWando** [sysgears/apollo-universal-starter-kit#310]
Hi folks,
First of all, thanks for providing a solution that help creating some kind of baseline or standard.
Just like the title described it's not a issue/ bug I'm just needing some kind of pointers.

The title doesn't actually describe my problem
It did took me some time to work out conventions between Feature/ connector class and various other helper functions like createContext(), but I did that. Done.

What utterly confused was after. After I got my head around. I realised -
**In our resolvers... we are using functions provided by the graphql endpoint's context object.**

*on the ground begging for relief from this terrible curiosity of relief of a swift death
I did not know that was even possible!

**Comment by vlasenko** [comment]
@ChingxWando So, what is the question? :)

**Comment by ChingxWando** [comment]
What is the intention or benefits to implement database operations in context and not in usual resolvers? Is it to simply expose these functions to all request in a nice way or is there other less obvious requirement for it? @vlasenko 

And do I need to do that too? Or I could as well have actual database operations in resolver.js files and only export to context (by writing in the sql.js file) when needed.

**Comment by vlasenko** [comment]
@ChingxWando You can have actual database operations in GraphQL resolvers. It is up to you.

The benefit to implement database operations separately is to decouple them from the rest of resolvers logic to let share the same SQL operation implementation across different resolvers (for example `Post.getPost` is used in several resolvers), and as we implemented them as ES6 classes, we need to instantiate them somewhere. For GraphQL the right place to instantiate classes/place state for resolvers - is a GraphQL context.

Of course our SQL ES6 classes do not have state - so we don't have to place their instances into GraphQL context - rather they can have static methods that can be directly used in resolvers.

**Comment by ChingxWando** [comment]
Wow that's wonderful, glad I asked! *sending flying kisses @vlasenko
