### ISSUE TITLE
Support non-Latin characters in URLs in SSR

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-universal-starter-kit#328]
Perhaps I am missing something, but when I am using non-Latin characters (Cyrillic for instance) in urls SSR does not work. Rendering on client works as expected.

**Comment by vlasenko** [comment]
@sakhmedbayev Could you prepare example in a fork of this project, so that we can easily reproduce this behavior?

**Comment by sakhmedbayev** [comment]
Yes, I will

**Comment by sakhmedbayev** [comment]
I have done some work in the fork to reproduce the issue. Here is the [link](https://github.com/sakhmedbayev/apollo-universal-starter-kit/tree/with_single_post_container)

In the fork, I introduced a new container `src/client/modules/post/containers/post_single.jsx`. It can be accessed via new route `<Route exact path="/post/test/:slug" component={PostSingle}/>,`

All routes of master branch of the kit _can_ handle non-Latin characters in SSR, check for instance this route:
`http://localhost:3000/post/%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0-%D1%80%D1%83%D1%81-%D1%81-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%D0%B0%D0%BC%D0%B8`

The new route, however, cannot handle non-Latin characters in a route:
`http://localhost:3000/post/test/название-на-рус-с-пробелами` (paste it in the browser's address bar)

Latin still works:
http://localhost:3000/post/test/title-in-english-with-spacing

It is most likely that I do not understand about react-router, cannot make it work.

**Comment by vlasenko** [comment]
I have cloned your repo and URL http://localhost:3000/post/test/title-in-english-with-spacing doesn't open for me, the error is:
```
backend error { ReferenceError: location is not defined
    at PostSingle (/home/victor/src/apollo-universal-starter-kit/src/client/modules/post/components/post_single_show.web.jsx:13:1)
    at walkTree (/home/victor/src/apollo-universal-starter-kit/node_modules/react-apollo/server.js:34:21)
    at walkTree (/home/victor/src/apollo-universal-starter-kit/node_modules/react-apollo/server.js:37:13)
    at walkTree (/home/victor/src/apollo-universal-starter-kit/node_modules/react-apollo/server.js:37:13)
    at getQueriesFromTree (/home/victor/src/apollo-universal-starter-kit/node_modules/react-apollo/server.js:57:5)
    at getDataFromTree (/home/victor/src/apollo-universal-starter-kit/node_modules/react-apollo/server.js:72:19)
    at /home/victor/src/apollo-universal-starter-kit/node_modules/react-apollo/server.js:79:41
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) queryErrors: [ [Circular] ] }
```

**Comment by sakhmedbayev** [comment]
Did you checkout "with_single_post_container" branch or master? All changes are in "with_single_post_container" branch, sorry for confusion.

**Comment by vlasenko** [comment]
Yes, I have checkout `with_single_post_container`

**Comment by sakhmedbayev** [comment]
I just completely removed my forked kit from my local machine and then cloned it from github to make sure that http://localhost:3000/post/test/title-in-english-with-spacing is working. Do not know what is going on... :-(

**Comment by vlasenko** [comment]
@sakhmedbayev If you look into stack trace that I have posted and check the offending source code line, you will find out, that you forgot to pass `location` prop to PostSingle functional component here:
https://github.com/sakhmedbayev/apollo-universal-starter-kit/blob/with_single_post_container/src/client/modules/post/components/post_single_show.web.jsx#L9-L13

So your code shouldn't work obviously. When I have tried to fix this by adding parameter I have faced another problem. I need working example to play with.

**Comment by sakhmedbayev** [comment]
Thank you @vlasenko! I found problem in `post_single_show.jsx`. As I changed it in the following way, it began to work.

```
import React from 'react';
import PropTypes from 'prop-types';
import Helmet from 'react-helmet';
import { Link } from 'react-router-dom';

import PageLayout from '../../../app/page_layout';


const PostSingle = ({ loading, post, match, location }) => {
  let postObj = post;

  // if new post was just added read it from router
  if (!postObj && location.state) {
    postObj = location.state.post;
  }

  const renderMetaData = () => (
    <Helmet
      title="Apollo Starter Kit - Edit post"
      meta={[{
        name: 'description',
        content: 'Edit post example page'
      }]} />
  );

  if (loading && !postObj) {
    return (
      <PageLayout>
        {renderMetaData()}
        <div className="text-center">
          Loading...
        </div>
      </PageLayout>
    );
  } else {
    return (
      <PageLayout>
        {renderMetaData()}
        <Link id="back-button" to="/posts">Back</Link>
        <h2>{post ? post.title : null}</h2>
      </PageLayout>
    );
  }
};

PostSingle.propTypes = {
  loading: PropTypes.bool.isRequired,
  post: PropTypes.object,  
  location: PropTypes.object.isRequired,  
};

export default PostSingle;
```
"another problem" was here `<h2>{post ? post.title : null}</h2>`

Thanks again!

**Comment by vlasenko** [comment]
@sakhmedbayev What about nonLatin chars in URLs, are they working ?

**Comment by sakhmedbayev** [comment]
Yes, they do. Apparently there are some decoding of non-Latin chars happening when react router receives URL string from the browser. `location` check fixes it. I wish you could see my example,
.

**Comment by vlasenko** [comment]
@sakhmedbayev So we can close this issue or no, I'm not really following?

**Comment by sakhmedbayev** [comment]
Yes, we can. Thanks
