### ISSUE TITLE
Upgrade react to v16.

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-universal-starter-kit#329]
I know this might be a bit early, since a lot of packages will take a while to all move to v16 and `react-native-web` is still not yet compatible, but should be soon (https://github.com/necolas/react-native-web/issues/364).

New version of RN uses now `react` v16.beta5 and we theoretically could make this kit already work with the latest RN and expo packages.

I would rather remove `react-native-web` for now and have new RN (flatList, ...), but am not sure this is the only think that would break.

@vlasenko what are your thoughts. Should we wait a few moths or give this a try sooner?

**Comment by vlasenko** [comment]
@mitjade Lerna branch of this kit is perfectly working with React v16 for a month already. So I don't see any other problems, except that some of our dependencies are not ready yet. But if we can move away from these dependencies I'm all for it. I would like we give this a try as soon as possible

**Comment by vlasenko** [comment]
@mitjade Build infra should be perfectly compatible with React v16. When I have tested it works even better with React v16, then with v15

**Comment by mairh** [comment]
so what's the plan? Improve `lerna` branch to use v16 or implement v16 in the current master and get rid of `react-native-web`?

**Comment by vlasenko** [comment]
@mairh get rid of `react-native-web` and implement v16 in current master

**Comment by mitjade** [comment]
I am for this as well.

**Comment by mitjade** [comment]
Since `react` is already rolling out release candidates, we can probably wait until they release a stable version and for RN to use it as well. Hopefully this might be happening within a month, since RN has monthly release cycles.

**Comment by vlasenko** [comment]
@mitjade Yep, I agree

**Comment by mitjade** [comment]
@vlasenko I see you created a branch for `react16`. Do you intend to upgrade this kit to react 16?

**Comment by vlasenko** [comment]
@mitjade Yes, I'm working on this. Not all the deps are ready, but I'm going to find workarounds for all.
