### ISSUE TITLE
Prettier usage

### ISSUE THREAD

**Issue by bastianwegge** [sysgears/apollo-universal-starter-kit#333]
Hey,

I see `"prettier": "^1.6.1",` in the `package.json` file. 
Is this used somewhere in the project?

If not, do you @vlasenko have preferred settings for prettier? Doing something like a pre-commit hook will save lots of `nit` commits.

All the best 🤖

**Comment by vlasenko** [comment]
Hi,

It is no longer used, I have committed removal of this dependency.

**Comment by bastianwegge** [comment]
Is there a reason why you removed it? Since there are many people working on the project we already have many different coding-styles.

**Comment by vlasenko** [comment]
I have removed it because it is not used in the starter kit. I think it was required by one of the previous versions of some of the dependencies. Now it is not required and not used, hence I removed it

**Comment by bastianwegge** [comment]
It's a library to unify code indenting and formatting, so why remove it?

**Comment by mairh** [comment]
I think we should have one coding style for the kit. I know everyone has a different opinion on the styles, but we can agree to one after defining those. For e.g I see some inconsistencies among different files in the kit.

For e.g

`<SomeComponent props={props}/>`
vs 
`<SomeComponent props={props} />` 

or

`const someVar = {arg1, arg2}` 
vs 
`const someVar = { arg1, arg2 }`

or
```
function myfunction() {
  ...
}
```
vs
```
function myfunction () {
  ...
}
```

**Comment by vlasenko** [comment]
As suggested by @bastianwegge we can use `prettier` to solve this problem. We need to configure it correctly and reformat all the source code of the kit with `prettier`

**Comment by bastianwegge** [comment]
I'd suggest using a pre-commit hook. -> https://github.com/sysgears/apollo-universal-starter-kit/pull/340

**Comment by mairh** [comment]
This can be closed I suppose
