### ISSUE TITLE
Redux Time-Travel is not working

### ISSUE THREAD

**Issue by bastianwegge** [sysgears/apollo-universal-starter-kit#337]
I noticed that time-travel in the redux-store is not working with this project. Does anyone know why or how to fix this?

Time-travel explained: https://youtu.be/xsSnOQynTHs?t=1429

**Comment by bastianwegge** [comment]
Seems to be a problem with Apollo itself: https://github.com/apollographql/apollo-client/issues/1800

**Comment by vlasenko** [comment]
Fixed via:
https://github.com/sysgears/apollo-universal-starter-kit/commit/442f26eb76f3a905f6fc9eb9b8a51387d30b449b
and
https://github.com/sysgears/apollo-universal-starter-kit/commit/442f26eb76f3a905f6fc9eb9b8a51387d30b449b
