### ISSUE TITLE
SpinJS is opinionated on the file extensions

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#339]
I just tried to merge the PR https://github.com/sysgears/apollo-universal-starter-kit/pull/314 However, I am getting an error if I name the index file as `src/client/index.js` instead of `src/client/index.jsx`

Usually, I prefer to name all my files with `js` extension instead of `jsx` and I believe we should not be opinionated on how the users should name the file based on the kit.

```
ERROR in ./src/client/index.jsx
Module build failed: Error: ENOENT: no such file or directory, open '/Users/nish/Documents/code/EasyMedi/src/client/index.jsx'
 @ multi webpack-hot-middleware/client ./node_modules/babel-polyfill/lib/index.js ./src/client/index.jsx
```

Build works fine if I change `js` to `jsx`

**Comment by vlasenko** [comment]
How about defining this in your `tools/webpack_app.config.js`:
```
const web = {
  entry: {
    index: [
      'babel-polyfill',
      './src/client/index.js'
    ]
  }
};
```

**Comment by vlasenko** [comment]
@mairh Spin.js must provide some default extension, according to Webpack rules. And the default extension in case of `['react', 'client']` stack is `.jsx`, I think it makes sense. If you want another extension - please customize your config

**Comment by mairh** [comment]
Overriding `tools/webpack_app.config.js` doesn't seem to work. Getting the same error.

**Comment by vlasenko** [comment]
@mairh Strange, I will take a look and return back to you

**Comment by mairh** [comment]
I tested following scenarios - just to test different combiations

1) `src/client/index.js`and `tools/webpack_app.config.js` web config comment out - Doesn't work
2) `src/client/index.js`and `tools/webpack_app.config.js` web config override with `js` extension - Doesn't work
3) `src/client/index.js` and `tools/webpack_app.config.js` web config override with `jsx` extension - Doesn't work
4) `src/client/index.jsx` and `tools/webpack_app.config.js` web config override with `js` extension - Doesn't work
5) `src/client/index.jsx` and `tools/webpack_app.config.js` web config override with `jsx` extension - Doesn't work

The only config works if `src/client/index.jsx` and `tools/webpack_app.config.js` is comented out

**Comment by vlasenko** [comment]
@mairh Should work in `spinjs@0.2.1`, please give it a try

**Comment by vlasenko** [comment]
@mairh This commit should have fixed the problem:
https://github.com/sysgears/spin.js/commit/437f2d0a64d89876ca62d506469665decdf803a7
It will replace entry point in Webpack config with value from `tools/webpack_app.config.js`. Previously it have just appended value from `tools/webpack_app.config.js` to those that were generated in Webpack config, hence it didn't work

**Comment by mairh** [comment]
Awesome. It works. Closing the issue!
