### ISSUE TITLE
Route change after success data load

### ISSUE THREAD

**Issue by t0x1c123** [sysgears/apollo-universal-starter-kit#344]
Hello, I want to ask if it's possible to change route after success data fetch. This "style" of data loading is used for example on YouTube. When you click on link there is a progress bar on top of the page (https://github.com/rstacruz/nprogress) and then route is changed after success data load. Now in example it's like that when you click on route page is changed immediately and when data are not loaded yet you need to show some loading indicator. Sorry if it's not right place to ask but I really need this feature :(

**Comment by vlasenko** [comment]
Hi,
This is more a question for `react-router` and `react-apollo`. Related issues:
https://github.com/apollographql/react-apollo/issues/417
https://github.com/apollographql/react-apollo/issues/711
