### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by t0x1c123** [sysgears/apollo-universal-starter-kit#352]
Hello I'm trying to normally render image in <image/> tag. Image's path is fetched from graphql and then added to image src atribute. When i do F5 image is normally rendered, but when I navigate somewhere and than back, image is invisible. So I tried inspect elements and image tag is there with correct src path but width is set to 0px and height to 16px. So I tried set width and height manually but nothing happens (in chrome). Weird is that this is not happening in edge browser (I also tried to switch off adblock).

**Comment by vlasenko** [comment]
@t0x1c123 Is this issue of the starter kit or the code of your project?

**Comment by t0x1c123** [comment]
Starter kit. I tried it also on fresh install of starter kit. Try to put image tag with random static image (I used google logo) on counter page and then go to posts and back. Image is not shown after that step.

**Comment by mairh** [comment]
Would be nice to see some code and recreate the problem.

**Comment by t0x1c123** [comment]
Code preview:
`
<PageLayout>
        {renderMetaData()}
        <div className="text-center mt-4 mb-4">
          <Section>
            <image src="https://www.google.cz/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" />
            <p>
              Current count, is {count.amount}. This is being stored server-side
              in the database and using Apollo subscription for real-time
              updates.
            </p>
            <Button id="graphql-button" color="primary" onClick={addCount(1)}>
              Click to increase count
            </Button>
          </Section>
          <Section>
            <p>
              Current reduxCount, is {reduxCount}. This is being stored
              client-side with Redux.
            </p>
            <Button
              id="redux-button"
              color="primary"
              onClick={onReduxIncrement(1)}
            >
              Click to increase reduxCount
            </Button>
          </Section>
        </div>
      </PageLayout>
`
So I just added `<image src="https://www.google.cz/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" />`

**Comment by vlasenko** [comment]
@t0x1c123 There is no such tag in HTML as `image`, you meant `img` probably. With `img` everything works as expected.

**Comment by t0x1c123** [comment]
OMG I'm totally retarded 😭 😭 Sorry for wasting your time 🤢. This is all because JSX! I don't know common html tags anymore 😭 😭 😭 😭
