### ISSUE TITLE
Upgrade to Apollo 2.0

### ISSUE THREAD

**Issue by vlasenko** [sysgears/apollo-universal-starter-kit#356]
https://github.com/apollographql/apollo-client/blob/master/Upgrade.md

**Comment by vlasenko** [comment]
I don't see that subscriptions have been implemented in Apollo v2 yet. So we need to wait for them to try 2.0

**Comment by mairh** [comment]
Where can I find the note that subscriptions have not been implemented in Apollo v2?

**Comment by vlasenko** [comment]
I don't find the note that they have been implemented. Obviously existing subscription packages for Apollo v1 will not work with Apollo v2, since they rely on networkInterface and don't have ways in the docs to use new Apollo Link

**Comment by mairh** [comment]
@vlasenko Check this out https://github.com/reactql/kit/issues/80

Lee has outlined some very nice points on upgrading to Apollo 2.0. It seems to me that subscription will work on Apollo V2 as well.

**Comment by vlasenko** [comment]
@mairh There is initial subscription transport implementation for Apollo Link:
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-ws/src/webSocketLink.ts

This implementation looks like neither documented nor thoroughly tested yet. So we can have tough time using it and likely face some underwater stones. 

I would like to give Apollo 2 a try early next week and see how it works and whether it is usable at this stage.

**Comment by mairh** [comment]
or maybe we just wait until it is out of beta.

**Comment by mitjade** [comment]
@mairh My guess is that will happen just before https://summit.graphql.com

**Comment by vlasenko** [comment]
Apollo v2 support has merged into master
