### ISSUE TITLE
File Naming Convention (Voting request)

### ISSUE THREAD

**Issue by ChingxWando** [sysgears/apollo-universal-starter-kit#359]
## Backgrounds
Since this related to people's preferences Victor suggests me to open a vote to find out what are people's preference on this.

Another similar experience I had was dropping [Javascript Standard Style](https://github.com/standard/standard) and pick up [airbnb javascript style](https://github.com/airbnb/javascript) after finding out about it from you guys and the justification for me was that it's more mainstream and is less intruding. So we also taking into account if what if people have existing projects and the amount of work required for maintainer to update imports and templates.

## Proposed recommendation
My believe is that the baseline would be to conform to [23.6 filenames should match export](https://github.com/airbnb/javascript#naming--filename-matches-export) and just PascalCase for [react components](https://github.com/airbnb/javascript/tree/master/react#naming) since we already using airbnb style and eliminate completely the uncertainty when thinking of filenames.

Something on the lines of "counterReducer.js" for reducers are functions and on the lines of LayoutComponent.jsx, PageNotFound.jsx for react components.

## Voting
Please let everyone know if you are for or against or simply okay with it. Victor will probably need to the one to make the change though, as it involves too many changes; but first we need to get a generally favourable feedback before anything else.

**Comment by vlasenko** [comment]
Thank you @ChingxWando very much for opening this issue and providing strong arguments why this change should be considered!

**Comment by mairh** [comment]
Since we are following `airbnb` style guide for the `eslint` rules. We can simply follow the naming conventions as well from `airbnb` https://github.com/airbnb/javascript#naming-conventions.

Not only the file names we can also focus on the method declaration. I would prefer if we change the function declaration such as (present in the kit)
```
function myFunction() {
  // foo
}
```
to 
```
const myFunction () => {
  // foo
}
```

**Comment by mitjade** [comment]
@ChingxWando I am OK with making the change.

**Comment by mairh** [comment]
Is anyone working on this? I have some time today to work on this if no one has picked it up yet.

**Comment by vlasenko** [comment]
@mairh Sure, please go ahead if you have a chance to work on this. I haven't started on this task yet. Mostly working on Angular2 / TypeScript support.

**Comment by mitjade** [comment]
@mairh It would be great to have this done soon. I am starting a new project and would love to have this done before I clone the kit repo.

**Comment by mairh** [comment]
Ok. I will try my best to complete it by tonight otherwise by tomorrow.

**Comment by mitjade** [comment]
@mairh I am currently fixing `cli` to generate modules that comply to `prettier` format. I would also like to rename all components from `..._show` to `..._view`. Maybe I can help out with this today also. Depends on how much time I will have. If you push a branch when you have something we can work from there together and split up some work.

**Comment by mairh** [comment]
Let me push a branch first with some updates wrt file names and function names. We can take it from there. It's better to work on the same branch and have no conflicts.

**Comment by mitjade** [comment]
@mairh Made some commits already, but they only concern `cli` templates. Let me know when you have something.

**Comment by mitjade** [comment]
@ChingxWando Could you also please check https://github.com/sysgears/apollo-universal-starter-kit/pull/360, since you ware the one requesting this feature.

**Comment by mairh** [comment]
PR has been merged. It might be possible that we have missed few things in the first PR regarding file and component naming convention. @ChingxWando Pls have a look at the latest master and let us know if there is anything missing or require changes.
