### ISSUE TITLE
Stranger issue with Login/Register (Clean clone, Windows 10)

### ISSUE THREAD

**Issue by MichelDiz** [sysgears/apollo-universal-starter-kit#375]
Just cloned and I did the usual process.

So I noticed that there was this authentication new feature (I had not noticed before.).
I decided to test. So:

Chrome could not GET / register or login
With Vivaldi gave Can not GET / register or login
With Edge gave Can not GET / register or login

However, in the old Internet Explorer it authenticates normally. Although I had a moment that gave the error below.

`backend HMR error status: fail`

Cheers

**Comment by mitjade** [comment]
@MichelDiz Do you get any errors in browser console or terminal? Can you check if you can see `token`  and `refreshToken` in your LocalStorage or `x-token` and `x-refresh-token` in your cookies, when you try to login.

I tested latest on Mac: Safari, Chrome, Firefox and Vivaldi. All work ok. I do not have access to a Windows machine right now.

Maybe also try to delete `dev-db.sqlite3` since some table name was changed, but since you did a fresh clone, this should not be the problem.

**Comment by MichelDiz** [comment]
Can not GET came from Browser in page.
backend HMR error status: fail appears randomly

I was using the port that the terminal offers. But when I used 3000. 
It kept logging in normally. It seems to me something related to "proxy" permissions.

Would not it be nice to standardize this project for Docker? It varies a NodeJs image with Linux and leaves "src" and "Build" in open volumes. So it would be interesting even for those who want to do quick tests. Just generate the image and run the container. And anyone on different operating systems would have no problems. Since we would be using a controlled Linux environment.

**Comment by vlasenko** [comment]
@MichelDiz Yes, having `Dockerfile` for this project would be nice, certainly

**Comment by MichelDiz** [comment]
@vlasenko I'm Starting some tests with Docker with this repo - Have you some tip to better approach?https://github.com/MichelDiz/apollo-universal-starter-kit/tree/dockerising

**Comment by MichelDiz** [comment]
So I tested the environment here and it's working.
Now you need to do something more geared towards deploy.
This form I made is for testing purposes only. Because docker-Compose is mirroring the entire root folder to ==> / usr / src / app

Would need to separate or generate non-persistent volumes for production

But even so, it helps.

The problem with browsers I mentioned was not happening using Docker.

I guess we can close it.

Cheers

**Comment by MichelDiz** [comment]
My bad, I just take the test with the login (I had forgotten it) the application works. But the authentication system does not. Now in neither browser. I think with this Docker I did you guys could better evaluate the problem.

```
webpack-for-web debug Backend has been started, resuming webpack dev server...
{ Error: spawn xdg-open ENOENT
    at _errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://172.20.0.2:3000' ] }
```

**Comment by vlasenko** [comment]
@MichelDiz What docker image do you want? The image that starts the kit in development mode or in production mode?

**Comment by MichelDiz** [comment]
Is there an image already?

My question is more about wich is proper configuration for a container  in relation to this project. For a production image, you would use docker-compose.override.yml and docker-compose.prod.yml

The above error seems to me something related to Proxy or some folder location due to lack of a correctly ENV in environment variables. I don't know.

At first I think this docker composite I wrote is useful to use. Only the visual part is missing due to this problem quoted above.

**Comment by MichelDiz** [comment]
But it's still a problem, as I wish it to allow for Host browsers. xD

**Comment by vlasenko** [comment]
@MichelDiz It is allowed for Host browsers. But you will have to type in URL in Host browser yourself, because starter kit is isolated in container and cannot execute commands on your host to open URL in the browser for you

**Comment by MichelDiz** [comment]
Well, it does not seem to work.

Work ==> http://localhost:8080/
Doesn't Work ==> http://localhost:8080/login?email=admin%40example.com&password=admin
Doesn't Work ==> http://localhost:3000/

Work ==> http://127.0.0.1:8080/
Doesn't Work ==> http://127.0.0.1:8080/login?email=admin%40example.com&password=admin
Doesn't Work ==> http://127.0.0.1:3000/

**Comment by vlasenko** [comment]
@MichelDiz You should use IP of your docker instance, not `localhost`. You have an error in Web Browser JavaScript console with this IP.  Please attach JavaScript console output when you open issues.

**Comment by MichelDiz** [comment]
The fact is that I had tried this too. I actually tried everything I found on Google. And nothing worked. Another fact is, as in thesis this project would be hosted on a Docker Host. It should work in tune with Docker completely. And it works, just the part of Auth that does not.

Do the test. Use my yml and see with your own eyes.

Cheers

```bash
/usr/src/app # yarn watch
yarn watch v1.0.2
$ spin watch
[HPM] Proxy created: !/*.hot-update.{json,js}  ->  http://172.20.0.2:8080
webpack-for-web Webpack web dev server listening on http://172.20.0.2:3000
webpack-for-web debug Webpack dev server is waiting for backend to start...
webpack-for-server Starting backend
webpack-for-server Time: 11940ms
backend info API is now running on port 8080
webpack-for-web debug Backend has been started, resuming webpack dev server...
{ Error: spawn xdg-open ENOENT
    at _errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://172.20.0.2:3000' ] }
webpack-for-web bundle is now VALID.
webpack-for-web Time: 16193ms
```

**Comment by vlasenko** [comment]
@MichelDiz What did you get in JavaScript console when you have tried it?

**Comment by MichelDiz** [comment]
When I try to login throught auth - the console nothing happens.

Just returns on my browser screen "Can not GET / login"
My console looks exactly like the one I posted above. It does not change anything.

**Comment by vlasenko** [comment]
@MichelDiz It is not a web browser JavaScript console. It is a terminal. I'm asking about web browser JavaScript console. You should check it every time you have some trouble with web application

**Comment by MichelDiz** [comment]
just:
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by vlasenko** [comment]
@MichelDiz What URL are you opening in web browser?

**Comment by MichelDiz** [comment]
And this when I open the GraphQL endpoint:
`WebSocket connection to 'ws://172.20.0.2:8080/graphql' failed: WebSocket is closed before the connection is established.`

**Comment by MichelDiz** [comment]
I use  http://localhost:8080/login?email=admin%40example.com&password=admin
because 172.20.0.2:8080 does not open

**Comment by vlasenko** [comment]
@MichelDiz This is wrong URL. You should use the URL reported to you by Webpack Dev Server during development:
```
webpack-for-web Webpack web dev server listening on http://172.20.0.2:3000
```

**Comment by MichelDiz** [comment]
Sorry if I'm not clear, but the URL that the terminal passes is not working externally on the HOST.

**Comment by vlasenko** [comment]
@MichelDiz What Operation System are you using to run Docker?

**Comment by MichelDiz** [comment]
Windows 10

**Comment by vlasenko** [comment]
@MichelDiz I have tried your docker compose image. It is working for me under Linux host. Normally starter kit uses LAN IP for all connections, this is done to enable direct access from the Android and iOS phone to the application running on local machine. To make all of the starter kit work as expected you need to figure out networking issues you have with docker. You should be able to access IP that is reported to you by the kit in the terminal from your machine. 

If you just want to run web part of the kit, then you can force to run it on localhost. You need to change `.spinrc.json` -> `options` -> `backendUrl` and replace `{ip}` with `localhost` in it.

**Comment by MichelDiz** [comment]
@vlasenko @mitjade I still have that issue. Even not using Docker. See the video https://youtu.be/o-tghyZ5eFc . It only works on port 3000. I reread everything we talked about in this issue, reviewed everything and this problem continues. It's only in development mode. I'm reporting this because I believe this should not be the behavior of the Kit. This is a clean instalation as before. All "clean".
