### ISSUE TITLE
No loader specified Error: No loader specified

### ISSUE THREAD

**Issue by semyenov** [sysgears/apollo-universal-starter-kit#380]
Fresh copy of the kit with `builders.android.enabled = true` in .spinrc.json
> yarn watch v0.27.5
$ spin watch
Generating vendor_web DLL bundle with modules:
["apollo-client","apollo-logger","bootstrap","cors","graphql","graphql-iso-date","graphql-tag","history","immutability-helper","jwt-decode","lodash","minilog","persistgraphql","prop-types","react","react-apollo","react-cookie","react-dom","react-ga","react-helmet","react-hot-loader","react-redux","react-router","react-router-dom","react-router-redux","react-transition-group","reactstrap","redux","redux-devtools-extension","redux-form","styled-components","subscriptions-transport-ws"]
Generating vendor_android DLL bundle with modules:
["@expo/vector-icons","apollo-client","apollo-logger","cors","expo","graphql","graphql-iso-date","graphql-tag","immutability-helper","lodash","minilog","prop-types","react","react-apollo","react-native","react-navigation","redux","subscriptions-transport-ws","/home/xxx/node_modules/spinjs/lib/plugins/react-native/react-native-polyfill.js"]
webpack-for-webDll Time: 40028ms
[HPM] Proxy created: !/*.hot-update.{json,js}  ->  http://10.0.3.225:8080
webpack-for-web Webpack web dev server listening on http://10.0.3.225:3000
webpack-for-androidDll Time: 58481ms

> ERROR in ./node_modules/react-navigation/src/createNavigationContainer.js
Module not found: Error: Can't resolve './PlatformHelpers' in '/home/xxx/node_modules/react-navigation/src'
resolve './PlatformHelpers' in '/home/xxx/node_modules/react-navigation/src'
  using description file: /home/xxx/node_modules/react-navigation/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/xxx/node_modules/react-navigation/package.json (relative path: ./src)
    using description file: /home/xxx/node_modules/react-navigation/package.json (relative path: ./src/PlatformHelpers)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers doesn't exist
      .android.jsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers.android.jsx doesn't exist
      .android.js
        Field 'browser' doesn't contain a valid alias configuration
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers.android.js doesn't exist
      .nativejsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers.nativejsx doesn't exist
      .nativejs
        Field 'browser' doesn't contain a valid alias configuration
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers.nativejs doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers.jsx doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers.js doesn't exist
      as directory
        /home/xxx/node_modules/react-navigation/src/PlatformHelpers doesn't exist
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers]
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers.android.jsx]
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers.android.js]
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers.nativejsx]
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers.nativejs]
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers.jsx]
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers.js]
[/home/xxx/node_modules/react-navigation/src/PlatformHelpers]
 @ ./node_modules/react-navigation/src/createNavigationContainer.js 1:1138-1166
 @ ./node_modules/react-navigation/src/react-navigation.js
 @ dll vendor
webpack-for-android No loader specified Error: No loader specified
    at Function.normalizeUseItem (/home/xxx/node_modules/webpack/lib/RuleSet.js:274:10)
    at Function.normalizeUse (/home/xxx/node_modules/webpack/lib/RuleSet.js:236:19)
    at Function.normalizeRule (/home/xxx/node_modules/webpack/lib/RuleSet.js:184:26)
    at rules.map (/home/xxx/node_modules/webpack/lib/RuleSet.js:86:20)
    at Array.map (<anonymous>)
    at Function.normalizeRules (/home/xxx/node_modules/webpack/lib/RuleSet.js:85:17)
    at new RuleSet (/home/xxx/node_modules/webpack/lib/RuleSet.js:80:24)
    at NormalModuleFactory (/home/xxx/node_modules/webpack/lib/NormalModuleFactory.js:49:18)
    at Compiler.createNormalModuleFactory (/home/xxx/node_modules/webpack/lib/Compiler.js:474:31)
    at Compiler.newCompilationParams (/home/xxx/node_modules/webpack/lib/Compiler.js:487:30)
webpack-for-web debug Webpack dev server is waiting for backend to start...
webpack-for-server Starting backend
webpack-for-server Time: 65307ms
backend info API is now running on port 8080
webpack-for-web debug Backend has been started, resuming webpack dev server...
webpack-for-web bundle is now VALID.
webpack-for-web Time: 27850ms

**Comment by mairh** [comment]
Can you post your system info?

**Comment by vlasenko** [comment]
@semyenov @mairh No need for system info, I can reproduce it

**Comment by semyenov** [comment]
> Field 'browser' doesn't contain a valid alias configuration
/home/xxx/node_modules/react-navigation/src/PlatformHelpers.nativejs doesn't exist
there is ./node_modules/react-navigation/src/PlatformHelpers.native.js

**Comment by mairh** [comment]
@vlasenko ok.

**Comment by vlasenko** [comment]
@semyenov The bug is fixed in `spin.js@0.3.6`. Going to update the kit now to point to this version.
