### ISSUE TITLE
Configuration for modules should be moved out of app.json

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-universal-starter-kit#382]
I started adding configuration for `user` module inside `app.json`, but I think this should be moved to module it self.

If you remove the module this configuration remains and it makes `app.json` more complex.

But you can have only `server` or `client` modules, so I am not sure where to put this. Maybe have a separate `client`, `server` configs?

@vlasenko I would like your thoughts on this, where to put it, so it gets deleted when module is deleted and we can provide a standard place for module configurations.

**Comment by vlasenko** [comment]
@mitjade We can have per-module config in a config dir. The same way as Linux services have the dir /etc/default with per-module config in each file that have the same name as a service. We can name this dir `config`. The global config should still reside in `app.json` though

**Comment by mitjade** [comment]
@vlasenko Ok. Will try to figure it out how to set this up.

**Comment by mitjade** [comment]
@vlasenko So you are proposing something like this:
`/config/user.json` and then extend `settings.js` to include all files under `config` and export them same as now for `app.json`?

**Comment by mitjade** [comment]
Proposed PR: https://github.com/sysgears/apollo-universal-starter-kit/pull/383

**Comment by mitjade** [comment]
Implemented in #383
