### ISSUE TITLE
Shall we start to include Release and changelog in the kit?

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#384]
I think it looks a bit more professional and clean to include CHANGELOG.md and release section.

Something similar to
https://github.com/reactql/kit/blob/master/CHANGELOG.md
https://github.com/reactql/kit/releases

Or do you think it is too much of a hassle to maintain that?

**Comment by vlasenko** [comment]
@mairh I think its too much hassle and too little outcome. But if many people will want that then we can maintain Changelog and produce Releases

**Comment by mairh** [comment]
Yeah. I understand your point. It was just a lingering question. I will close this issue as of now.
