### ISSUE TITLE
Integrating Apollo Optics to the kit

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#385]
Shall we add Apollo Optics to the kit? Since we use Apollo as our main client/server and Optics is offered by the same people (Free up to 1 million req/month). I think it would make a good addition to the kit.

https://www.apollodata.com/optics/

**Comment by vlasenko** [comment]
@mairh Yes, sure, I think it is a good idea.

**Comment by mitjade** [comment]
#422

**Comment by vlasenko** [comment]
Implemented in #423
