### ISSUE TITLE
Sign Up, Sign In, Reset Password, Forgot Password, Admin Dashboard features

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#390]
Sign Up and Forgot Password to be done through Email Verification and/or Mobile Phone / One Time Passwword

Sign Up - Captcha

Can we expect the contributors decide to add these essential features in near future?

Thanks

**Comment by vlasenko** [comment]
@coooolers We would certainly appreciate if these features were implemented for the kit. You can expect that we will include these features into the starter kit if someone implement them and submit Pull Request of a good quality. 

If you want these or other features to be added as soon as possible, please note, that this is possible via commercial support: https://github.com/sysgears/apollo-universal-starter-kit#commercial-support

**Comment by mitjade** [comment]
#420

**Comment by johnthepink** [comment]
Reset password in #424

**Comment by mitjade** [comment]
Manage users if admin in #420

**Comment by mitjade** [comment]
#420 has been merged. Basic user management implementation is now working.
