### ISSUE TITLE
Support all features provided by create-react-app

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#397]
This is the most powerful react app boilerplate especially when it comes to production..
https://github.com/facebookincubator/create-react-app

Do you have any plans to copy the functionality offered by this boilerplate and include it in your kit?

**Comment by vlasenko** [comment]
No

**Comment by vlasenko** [comment]
@coooolers Please consider using our chat for general discussions:
https://gitter.im/sysgears/apollo-fullstack-starter-kit
