### ISSUE TITLE
Best way to have upload support 

### ISSUE THREAD

**Issue by vinu** [sysgears/apollo-universal-starter-kit#411]
What is the best way to have upload support with the starter kit, I was thinking to use https://github.com/jaydenseric/apollo-upload-client and https://github.com/jaydenseric/apollo-upload-server 
or should I just create a rest endpoint /upload to handle all the uploads and just use graphql to save the references?

**Comment by mairh** [comment]
We have image upload feature in the pipeline https://github.com/sysgears/apollo-universal-starter-kit/issues/176

Doing image upload using graphql mutation is fine and doesn't have any security/performance impact on the application. One of the major service for backend https://www.graph.cool/ also does the file upload using graphql mutations.

At the moment [Apollo Upload Client](https://github.com/jaydenseric/apollo-upload-client) and  [Apollo Upload Server](https://github.com/jaydenseric/apollo-upload-server) seem to be the go-to choice. However, keep in my mind that we have already switched to Apollo V2 and [Apollo Upload Client](https://github.com/jaydenseric/apollo-upload-client) does not support V2 out of the box yet (Check [Issue](https://github.com/jaydenseric/apollo-upload-client/issues/33)).

You need to use [Apollo Fetch Upload](https://github.com/apollographql/apollo-fetch/tree/master/packages/apollo-fetch-upload) along with [Apollo Upload Client](https://github.com/jaydenseric/apollo-upload-client) to make it work for V2.

Here is one example https://github.com/jaydenseric/apollo-upload-examples/blob/master/app/helpers/with-data.js#L23

**Comment by mitjade** [comment]
#421

**Comment by vinu** [comment]
woohooo :+1: 

thanks guys, I am closing this :)
