### ISSUE TITLE
Incorrect callback URL for confirm email link

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#414]
Confirm email works on localhost, but if you deploy it to production the callback url is still pointing to localhost.

Steps to reproduce:

1) Register a new user on https://apollo-universal-starter-kit.herokuapp.com/register
2) Check the confirmation email link on https://ethereal.email/messages (user/pass is in `.env`)

The link contains `http://localhost:17145/confirmation/xxxxxxxxxxxx`. However, it should contain `https://apollo-universal-starter-kit.herokuapp.com/confirmation/xxxxxxxxxxxx`

**Comment by mitjade** [comment]
Will check it out.

**Comment by mairh** [comment]
@mitjade Thanks. Closing now
