### ISSUE TITLE
Multiple DB's and env vars

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#418]
2 points I would like to discuss in regards to supporting multiple DB's and their associated env vars

At the moment we have the following in `.env`

```
# DB
DB_USER=
DB_PASSWORD=
DB_DATABASE=
```

I think we can keep it like this and when doing a prod deployment we create another `.env` file in the server manually and change the `.env` values as suitable.

Second, I would like to ask opinion on how we generate the DB configs

What we have at the moment is

```
let DB_TYPE = 'sqlite';

let client = '';

let connectionDevelopment = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  multipleStatements: true,
  charset: 'utf8'
};

let connectionProduction = connectionDevelopment;

let connectionTest = {
  filename: ':memory:'
};

if (DB_TYPE === 'mysql') {
  // mysql
  client = 'mysql2';
} else if (DB_TYPE === 'pg') {
  // postgres
  client = 'pg';
} else {
  // sqlite
  client = 'sqlite3';
  connectionDevelopment = {
    filename: './dev-db.sqlite3'
  };
  connectionProduction = {
    filename: './prod-db.sqlite3'
  };
}

export default {
  dbType: DB_TYPE,
  client: client,
  connection: {
    development: connectionDevelopment,
    production: connectionProduction,
    test: connectionTest
  }
};
```

Now, here I see 2 problems

1) It won't work if you don't have `sqlite3` installed and your primary choice of DB is not `sqlite3`. If, for e.g I use `pg` as my primary DB, I would ask this question to myself why would I want to install `sqlite3` in `package.json` at first place. 

2) Actual Database name. (It is fine for `sqlite3` since are importing different `.sqlit3` files, but for `mysql and pg` we have the common DB whereas we would like to have different DB's for dev, test, and prod )

So I suggest we change the above code with the following one 

```
let DB_TYPE = 'sqlite';

let client = '';

let connectionDevelopment = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: `${process.env.DB_DATABASE}_dev`,
  multipleStatements: true,
  charset: 'utf8'
};

let connectionProduction = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: `${process.env.DB_DATABASE}_prod`,
  multipleStatements: true,
  charset: 'utf8'
};

let connectionTest = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: `${process.env.DB_DATABASE}_test`,
  multipleStatements: true,
  charset: 'utf8'
};

if (DB_TYPE === 'mysql') {
  // mysql
  client = 'mysql2';
} else if (DB_TYPE === 'pg') {
  // postgres
  client = 'pg';
} else {
  // sqlite
  client = 'sqlite3';
  connectionDevelopment = {
    filename: './dev-db.sqlite3'
  };
  connectionProduction = {
    filename: './prod-db.sqlite3'
  };
  connectionTest = {
    filename: ':memory:'
  };
}

export default {
  dbType: DB_TYPE,
  client: client,
  connection: {
    development: connectionDevelopment,
    production: connectionProduction,
    test: connectionTest
  }
};
```

This will solve the problem of installing only 1 DB in `package.json`and we will have 3 DB's for `mysql` and `pg` depending on the environment.

@mitjade Mentioned that he wouldn't like to have `xxx_prod` suffix in his prod database. So we have 2 options here either go with what I wrote in the above code or just use the suffix `xxx_test` for test DB only.

```
let connectionDevelopment = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: `${process.env.DB_DATABASE}`,
  multipleStatements: true,
  charset: 'utf8'
};

let connectionProduction = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: `${process.env.DB_DATABASE}`,
  multipleStatements: true,
  charset: 'utf8'
};

let connectionTest = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: `${process.env.DB_DATABASE}_test`,
  multipleStatements: true,
  charset: 'utf8'
};
```

**Comment by vlasenko** [comment]
@mairh I think we don't need separate configs for dev and prod database, we need only one config, lets call it main database config. We also need database config for running tests, which will have special setup to run tests quickly - e.g. moving database fully into memory if this is supported by engine, turning off transactions, etc. So we really need two connections `database connection` and `test database connection`

**Comment by mairh** [comment]
That would be nice.

**Comment by mairh** [comment]
By the way, @mitjade mentioned that `process.env.DB_USER is undefined in config/db.js unless I add import 'dotenv/config';?` was undefined when running `yarn test`.

In this commit https://github.com/sysgears/apollo-universal-starter-kit/commit/af6bbac6fd90fc6ce40750f5fe04adbf28941880 I moved the `dotenv` import to config `index.js` file. But still the env vars are not available for db.js. I wonder why

**Comment by mitjade** [comment]
@mairh I reverted the tests back to `sqlite` until we figure out how to do tests with other databases.

`dotenv` now seems to work for tests and running the kit it self.

**Comment by lyzhovnik** [comment]
Hi, issue is closed because this is a bit outdated. Actual config for database is here: [config/db.js](https://github.com/sysgears/apollo-universal-starter-kit/blob/master/config/db.js)
