### ISSUE TITLE
Integrate error handler

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-universal-starter-kit#42]
Hi,
I have just publish new module [graphql-apollo-errors](https://www.npmjs.com/package/graphql-apollo-errors). (Fully tested with 100% coverage)
This module help to handle errors in a better way for example:
* Make everything structured the same way
* FInally get the full error in the client (not only message path and location)
* Hooks for logging/storing the errors

and much more

I think it will be great to embed this into this project.
I already wrote all the code in my personal project (based on this starter-kit).
So I think to create a PR for this.

What do you think?

Thanks.

**Comment by vlasenko** [comment]
Hi,

I think that Apollo error processing is not responsibility of starter kit. Starter kit should only report what it gets as is. If default error handling and reporting in Apollo is bad, then Apollo should be fixed.

**Comment by GiladShoham** [comment]
@vlasenko 
Thanks for your comment.
It's bad, and I can't find a reason why the errors handled that's way (you can't get an object with code/name and other data to the client, only message).

So, do you want me to skip it or make it anyway?

**Comment by vlasenko** [comment]
You can make Pull Request, but most probably I will not merge it any time soon, I would prefer Apollo error handling to be improved instead. Let's keep this ticket open though for error handling discussion ideas.

**Comment by vlasenko** [comment]
Closing this issue, as I haven't heard about much troubles with Apollo error handling / or perhaps people quickly find the solution elsewhere to this problem
