### ISSUE TITLE
Update Password Mutation

### ISSUE THREAD

**Issue by johnthepink** [sysgears/apollo-universal-starter-kit#429]
I noticed there is an `updatePassword` mutation that is unrestricted here:

https://github.com/sysgears/apollo-universal-starter-kit/blob/master/src/server/modules/user/resolvers.js#L123-L131

Meaning anyone, logged in or not, can run this mutation and change anyone's password if they can guess the user id. I know this is just a boilerplate, but it feels like it would set people up better if we can restrict that to the current user context, or remove it so developers don't accidentally miss it.

Feel free to assign to me :)

**Comment by mitjade** [comment]
@johnthepink Good catch! Will fix it in my branch and then merge everything, including your PR, today.

**Comment by mitjade** [comment]
It was removed in #420, since it is no longer needed.
