### ISSUE TITLE
Support for Roles and Permissions

### ISSUE THREAD

**Issue by ramandhingra** [sysgears/apollo-universal-starter-kit#436]
Wonderful work ! Can you add support for Roles which is a basic requirement in almost all the projects. A developer should be able to define multiple roles in a Constants file...

**Comment by mitjade** [comment]
@ramandhingra You could extend `createResolver` to something like `requiresRole.createResolver` in `/src/server/modules/user/permissions.js` or replace it with something like [graphql-auth](https://github.com/kkemple/graphql-auth) `withAuth`.

Something like this is planed but not in the near future. If you manage to implement something your self before, any PRs are welcome. Also if you need some further info on how to implement this, we are willing to help.

**Comment by msand** [comment]
Has integration with https://github.com/postgraphql/postgraphql been considered? It has the user, roles and row-level-security of PostgreSQL with a GraphQL api, works beautifully.

**Comment by vlasenko** [comment]
@msand I cannot imagine how to integrate this starter kit with PostGraphQL. PostGraphQL seems to be PostgresQL specific, whereas this kit should be a generic platform for cross-platform (mobile, web and server) GraphQL application not tied to any particular database engine.

**Comment by msand** [comment]
@vlasenko True, was considering more if @ramandhingra wants roles etc. then it can be a great alternative to use that, as the postgres implementation is probably more robust and battle tested than anything custom made.

**Comment by coooolers** [comment]
For custom-made roles/permissions, security (cors and helmet express packges), Forgot/Reset Password, ProtectedRoute react component (redirect to login), Integration with nodemailer/mailgun, you may take cues from this package. I am sure it is well-tested.

 https://github.com/strues/boldr

**Comment by mitjade** [comment]
#467

**Comment by mitjade** [comment]
#467 is merged so closing this issue. Basic role permissions are added with the use of [graphql-auth](https://github.com/kkemple/graphql-auth).
