### ISSUE TITLE
DB settings in .env must be single-quoted or else the default DB will be used in Postgres.app (OSX)

### ISSUE THREAD

**Issue by JoeNoPhoto** [sysgears/apollo-universal-starter-kit#438]
~~Leaving this here for anyone who doesn't work with backends often and get stuck banging their head against a wall.~~

~~in the .env file, you must use single quotes in DB_:~~
```
# DB
DB_USER='db_user'
DB_PASSWORD='db_passord'
DB_DATABASE='db_database'
```
I didn't understand why every time I tried to migrate, 'JoeNoPhoto' was being used as a database and role. Turns out that if you're using Postgres.app on mac:

> When Postgres.app first starts up, it creates the $USER database, which is the default database for psql when none is specified. The default user is $USER, with no password.

~~The entire problem was that I wasn't using the single quotes in the .env file. Everything is working perfectly now. I'm not sure if this is common knowledge, or if all databases need this, or I'm an idiot or a combination of all 3 but I hope this helps someone else out somewhere down the line.~~

*****EDIT: *****
In fact, the only way I can currently log in with the proper username/password/database is hardcoding the information into ./config/d:
```
let connectionDevelopment = {
  user: 'db_user',
  password: 'db_pass',
  database: 'db_database',
  multipleStatements: true,
  charset: 'utf8'
};
```

**Comment by vlasenko** [comment]
@JoeNoPhoto Have you tried to dump your process.env in the top of `config/db.js` via
```
console.log(process.env);
```
? 
Maybe this will add you clues about whats going on?

**Comment by mitjade** [comment]
@JoeNoPhoto Please try again. Made a change that should also work for `yarn seed` command.

**Comment by JoeNoPhoto** [comment]
That did the trick and the quotes weren't necessary. Thanks.
