### ISSUE TITLE
Error when the command yarn seed is run

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#440]
/Project/apollo-universal-starter-kit$ yarn seed
yarn run v1.2.0
$ npm run migrate && knex seed:run

> apollo-universal-starter-kit@1.0.0 migrate /home/cool/Project/apollo-universal-starter-kit
> knex migrate:latest

Using environment: development
Already up to date
Using environment: development
Error: SQLITE_ERROR: no such table: auth_local
error Command failed with exit code 1.

**Comment by vlasenko** [comment]
@coooolers You should drop `dev-db.sqlite3` and run `yarn seed` again, the schema has changed.

**Comment by coooolers** [comment]
but i am running this kit for the very first time

**Comment by coooolers** [comment]
This problem has been solved but while running 'yarn watch', I get this error:
[HPM] Error occurred while trying to proxy request / from localhost:3000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /favicon.ico from localhost:3000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by vlasenko** [comment]
@coooolers Please use separate tickets for separate issues. For your last issue please provide reproduction steps
