### ISSUE TITLE
Error when the command 'yarn watch' is run

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#442]
[HPM] Error occurred while trying to proxy request / from localhost:3000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /favicon.ico from localhost:3000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by vlasenko** [comment]
@coooolers The issues like this are not welcomed here. I have asked you to provide reproduction steps.

**Comment by coooolers** [comment]
I simply followed these steps:

git clone https://github.com/sysgears/apollo-universal-starter-kit.git
cd apollo-universal-starter-kit
yarn
yarn seed
yarn watch

**Comment by mitjade** [comment]
@coooolers Can you provide some additional info like your os, node version, from which commit onward does this happen, in case you ware able to run this kit before with no problems.

**Comment by coooolers** [comment]
To update to the latest version, I did some "git pull" in the last few days and probably because of that this error was there,

Just now, I did the fresh reinstall and it worked fine.

Thanks.

I am closing this issue.

**Comment by vlasenko** [comment]
@coooolers Thanks for the update
