### ISSUE TITLE
Using UI React components library 

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#444]
This code is using styled-components. I want to use a library like semantic-ui-react or antd which will help me save time styling the components, they offer a number of ready-made UI components, and probably other third-party components like google-map-react. At the same time I don't want to do anything which does not favor the rules constrained by this boilerplate.

How can I use such libraries alongside styled-components? Can you write an example for this?

Thanks

**Comment by mitjade** [comment]
#441 This PR will attempt to solve this problem. It will take a while before it will be ready.

**Comment by mitjade** [comment]
This kit is using `reactstrap` along side `styled-components`, which is similar to `semantic-ui-react` but for `twitter bootstrap`.

**Comment by mitjade** [comment]
@coooolers #441 has been merged and offers the following:
By default `ui-bootstrap` is used to style all modules. If you would like to switch to `ui-antd`, all you need to do is make changes in `src/client/modules/index.js`, `src/server/modules/index.js` and `src/client/modules/common/components/web/index.jsx`.

If you would like to use something else, you can create a new `ui` module following the same approach  as done in `ui-bootstrap` module and add something like `ui-semantic` fairly easily.
