### ISSUE TITLE
checkAuth does not properly work with Postgresql

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-universal-starter-kit#454]
src -> client -> users -> containers -> Auth.js -> checkAuth function needs to be tweaked a little bit in order to properly work with Postresql.

on line number 39
   ```
   if (isAdmin === false) { // use 'false' here instead of '0'
        return false;
      }
```

**Comment by mitjade** [comment]
@sakhmedbayev You are correct. `MySql` and `SqlLite` return 0 or 1 for boolean types, but `postgres` returns true/false.

@vlasenko Do you know of any elegant way to solve this across all supported databases? `MySql` has `typeCast` to convert this to boolean, but `sqlite` does not. I see 3 solutions, non that I like:
- add to all if statements `(isAdmin === false || isAdmin === 0)`
- convert all sql select results of boolean fields to `Boolean` if not
- change isAdmin to `int`

**Comment by vlasenko** [comment]
@mitjade I vote for converting all sql select results of boolean fiels to `Boolean`

**Comment by vlasenko** [comment]
@mitjade But I'm not sure I see big problem in JS with 0 and false, both should be treated as false in JS. And non-zero should be treated as true. Just don't do (isAdmin == false), do (!isAdmin)

**Comment by mitjade** [comment]
@vlasenko You are right. We just need to setup the code to support all 3 databases. Those who are using a specific one will know it's special features like this.
