### ISSUE TITLE
Add Support for Filtering, Sorting Pagination, and Search

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#470]
First of all, this kit is maturing fast. Congratulations to the team.

Is it possible for the team to add support for the generic features like Filter, Sort, Pagination, Search. These could be applied to different components, let's say, Card, or Table.

Thanks

**Comment by mitjade** [comment]
@coooolers Examples on how to implement this already exist. Pagination in `post` module and Sort, Filter and Search in `user` module.

**Comment by coooolers** [comment]
ok. Is it server-side or client-side sort, filter, and pagination

**Comment by mitjade** [comment]
@coooolers Examples are for server side. For client side takke a look at ‘antd’ Table component. It offers most of this out of the box.

**Comment by coooolers** [comment]
Thanks you may close this issue
