### ISSUE TITLE
Gitignore includes src/*/upload folders

### ISSUE THREAD

**Issue by avsmithy** [sysgears/apollo-universal-starter-kit#475]
The current .gitignore file contains the line `upload` (which I assume is intended to only ignore the upload folder in the root of the project that is created when you upload a file to the app). This causes git to ignore the `upload` folders inside src. If you download a zip of the repo (or delete the git folder after cloning it), then these folders will be (incorrectly) ignored.

**Comment by vlasenko** [comment]
@avsmithy Thank you for reporting! Should be fixed via:
https://github.com/sysgears/apollo-universal-starter-kit/commit/c98cb732d6486a3f5cb6d654d95038bb2a322218

**Comment by avsmithy** [comment]
Speedy fix ;)
