### ISSUE TITLE
GraphQL redux integration

### ISSUE THREAD

**Issue by wojcikiewiczm** [sysgears/apollo-universal-starter-kit#483]
Hello, I noticed that when i try to for example load data via graphql no action is fired in redux (DevTools). In previous version all graphql actions was also catched by redux. It's bug or feature?

**Comment by vlasenko** [comment]
Hi
@wojcikiewiczm It is a "feature" of Apollo Client 2. In Apollo Client 2 the GraphQL cache is no longer maintained in Redux, but rather stored separately. However Apollo Team talked about possibility of writing an adapter for Redux to store the cache into it. When such adapter become available we will integrate it.

**Comment by wojcikiewiczm** [comment]
Oh okay thanks. I need this feature because of global codelists. I need to be able get codelist anytime anywhere.

**Comment by vlasenko** [comment]
@wojcikiewiczm You can continue using Apollo 1 branch of the kit meanwhile. We support it:
https://github.com/sysgears/apollo-universal-starter-kit/tree/apollo1
