### ISSUE TITLE
Is there a reason the *.graphql code is double-indented?

### ISSUE THREAD

**Issue by JoeNoPhoto** [sysgears/apollo-universal-starter-kit#484]
It's hard to see in github but all of the .graphql files are indented twice for each line. Example:
_(AddCounter.graphql)_
master
```
mutation addCounter($amount: Int!) {
    addCounter(amount: $amount) {
        amount
    }
}
```
vs.
```
mutation addCounter($amount: Int!) {
  addCounter(amount: $amount) {
    amount
  }
}
```

AFAIK, It's only happening in the .graphql files so I was curious as to if there was a specific reason.

**Comment by mairh** [comment]
We can change that to 2 spaces like any other files. `yarn lint` does prettify `.js` and `.jsx` files but not `.graphql` files. I can push the changes to the ki.

**Comment by mairh** [comment]
Fixed via https://github.com/sysgears/apollo-universal-starter-kit/commit/cb0f63e7e1249c7dfb3a80cb964f367436cbbb7b

**Comment by JoeNoPhoto** [comment]
Thank you for the explanation.
