### ISSUE TITLE
Verify Email Address by sending a confirmation link to that address when a new user registers  

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#485]
Forgot password has this support. Similarly, we can add support when a new user signs up

**Comment by mairh** [comment]
We have this feature already in the kit https://github.com/sysgears/apollo-universal-starter-kit/blob/master/src/server/modules/user/resolvers.js#L104

What problem are you facing?

**Comment by coooolers** [comment]
Ok fine if it is there..

Now there is an issue ...
I am already Logged In and still I can use the Forgot Password Functionality. Ideally, the user should not be able to browse both the Login/Forgot Password and Register routes (also hide these links from the main page) if she is already logged in. Instead, the Logout button is shown which when clicked takes the user to the main page and she should be allowed to browse the Login and Register routes/links.

**Comment by mairh** [comment]
Yes, that can be improved. `/login` path is not currently secured by auth. We need to redirect user (let's say to homepage) if the user is already logged in and tries to manually enter `/login` url in the browser.

**Comment by mairh** [comment]
By the way, you do see the logout link on the top nav bar once you successfully log in. The only issue that can be improved is to secure `/login` and `/register` route for logged in user.

**Comment by coooolers** [comment]
could you pl. make the appropriate additions in the code and complete this missing functionality?

**Comment by mairh** [comment]
I will create a new issue for securing `/login` and `/register` route for logged in user

**Comment by mairh** [comment]
Created https://github.com/sysgears/apollo-universal-starter-kit/issues/496
