### ISSUE TITLE
User Registration is Broken

### ISSUE THREAD

**Issue by dcurletti** [sysgears/apollo-universal-starter-kit#486]
The default FB login example is broken.  It fails here:
https://github.com/sysgears/apollo-universal-starter-kit/blob/1b7818e2e0f27b77165cfb45ca563dac4645d392/src/server/modules/user/index.js#L37
because `User.register` requires a password

Also, 
https://github.com/sysgears/apollo-universal-starter-kit/blob/1b7818e2e0f27b77165cfb45ca563dac4645d392/src/server/modules/user/index.js#L39

`User.createLocalOuth` is not defined.

**Comment by mitjade** [comment]
Should be fixed now with [a44cef4](https://github.com/sysgears/apollo-universal-starter-kit/commit/a44cef4cd81eae1e77be5c394f7d9e13a826fdd7). Thanks for reporting.

**Comment by dcurletti** [comment]
sweet. thank u.
