### ISSUE TITLE
Can't publish app

### ISSUE THREAD

**Issue by krzysztofp** [sysgears/apollo-universal-starter-kit#490]
I'm using Expo XDE. When I press publish button I'm getting this error:
```
Cannot find entry file src/server.js in any of the roots: ["./apollo-universal-starter-kit"]
```

**Comment by vlasenko** [comment]
@krzysztofp You should not use Expo XDE, it does not support the way this project is configured. This project supports launching on iOS Simulator and Android Emulator simulatenously, Expo XDE does not support it.

Please read instructions on how to launch the kit:
https://github.com/sysgears/apollo-universal-starter-kit

**Comment by krzysztofp** [comment]
@vlasenko I'm using iOS Simulator and it works perfectly fine. I'm just trying to publish my project to my client so she can play around with it. Normally with XDE I'd use Publish feature, but the way project is configured make this impossible - from where should I start to fix it?

**Comment by vlasenko** [comment]
@krzysztofp Oh, you are right. This is not in the documentation. We have section about building standalone apps, but not about publishing on Expo:
https://github.com/sysgears/apollo-universal-starter-kit#building-standalone-mobile-apps-for-play-store-and-app-store

However publishing on Expo is the same, e.g.:
`yarn exp publish`

**Comment by vlasenko** [comment]
@krzysztofp Actually this seems to be broken now, let me fix it quickly
