### ISSUE TITLE
Refactor add/edit user component

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#495]
At the moment any admin is able to change the password of any user, which should not happen.

What I propose is to make the following changes:

1) Add user - Same as the current one.
2) Edit user - Remove the password fields from the form.
3) Email - Send an email to the user when added by admin.

What do you think @mitjade

**Comment by mitjade** [comment]
1. Usually I am the admin and I mostly create users with different roles than mine.
2. If I am the admin user, I would still like to be able to change the password.
3. Should be an option.

**Comment by mairh** [comment]
1) I agree
2) Why would someone else be able to change the password for someone else's account? That seems to be a complete breach of privacy. One should have access to change/ modify the password for privacy, not anyone else.
3) Pretty easy to do.

**Comment by mitjade** [comment]
I use this for a project that is only used for employees and we set passwords for them, so they do not enter `admin123` or something. I agree that this is not the most used case, but I still need to be able to set the password as an admin.

**Comment by mitjade** [comment]
I know this can be enforced with some `RegExp`, but it is easier for me just to do it for them.

**Comment by mitjade** [comment]
I gmail I am also able to set passwords for for users if I have a `domain` account. But there you can have a random one generated, force the user to reset it after login etc.

**Comment by mairh** [comment]
I completely understand the project need and it makes sense in your use-case. However, as a starter kit, I guess we should follow the usual practice. Since changing the password for someone else is not really an industry practice and most of the apps don't allow you to do that. Just my 2 cents

**Comment by mitjade** [comment]
I agree. I just need the option to do that anyway. It can become a setting, turned off by default, but I do not want to remove this and then reimplement it on my project.

**Comment by mairh** [comment]
Sure. We can come up with some flag to hide the password filed from edit user.

**Comment by mitjade** [comment]
ok

**Comment by mairh** [comment]
Fixed via https://github.com/sysgears/apollo-universal-starter-kit/pull/497

**Comment by coooolers** [comment]
Let me add something to this discussion thread. The users are typically created by an administrator in Blog, Forum like web applications and are typically given the roles of moderators, editor, etc. In most of the web apps, an admin creates the co-admins and not regular users.

However, in all the cases, the admin does not create/enter the password of the other users. He can make them Inactive, if required but does not change their password.

Sending a password in an email is not a good idea. The email could be seen by an admin of the email server. Just send a link in the email which when clicked takes the user to the Enter Password screen.

Thank you

**Comment by coooolers** [comment]
Also the same Enter Password screen can be used to modify the screen. There should be a menu option My Profile - Settings - Modify Password.
