### ISSUE TITLE
Assign default 'User' role to end users of the system during Registration

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#499]
Consider that there are 3 roles: admin, staff, and user. In a config file, make a variable DEFAULT_ROLE and set its value to 'user' (role). 

There is a Register button on the main home page. Now when a new user registers and saves her registration details, the system should assign her the DEFAULT_ROLE i.e. the 'user' in our case.

Thanks for your great work

**Comment by mairh** [comment]
`user` role is assigned by default during registration https://github.com/sysgears/apollo-universal-starter-kit/blob/master/src/server/database/migrations/002_user.js#L8.

Reopen the issue if you encounter any bug.
