### ISSUE TITLE
QR Code is not showing on `yarn watch`

### ISSUE THREAD

**Issue by sejr** [sysgears/apollo-universal-starter-kit#501]
I would like to view this application on my mobile device but I am not seeing a QR code anywhere.

**Comment by vlasenko** [comment]
@sejr Have you enabled `android` or `ios` builder in `.spinrc.json` ?

**Comment by vlasenko** [comment]
Closing because of no response

**Comment by kwyn** [comment]
I'm having this same issues with the android and ios variables set.
