### ISSUE TITLE
nodejs debugger

### ISSUE THREAD

**Issue by fusionbeam** [sysgears/apollo-universal-starter-kit#505]
Could not find in the documentation instructions on how to start nodejs in debug mode while using spinjs configuration.
Thanks.

**Comment by vlasenko** [comment]
@fusionbeam It is started in debug mode automatically, during `spin watch`

**Comment by vlasenko** [comment]
``` sh
webpack-for-server Spawning node --inspect /Users/victor/work/apollo-universal-starter-kit.master/build/server/index.js
Debugger listening on ws://127.0.0.1:9229/918ab82e-73a2-4433-995f-87ed5554ae6a
For help see https://nodejs.org/en/docs/inspector
```

**Comment by hunglmtb** [comment]
@vlasenko Thank you
I can use the `127.0.0.1:9229` to attach debugger.
In my case, I use webstorm with `Attach to Node.js/Chrome` debug configuration

**Comment by hunglmtb** [comment]
Hi @vlasenko ,
I got debug link `Debugger listening on ws://127.0.0.1:9229/918ab82e-73a2-4433-995f-87ed5554ae6a` as you give on stable branch but when I switch to master, it disappears.
How can I config to receive this debug link?

**Comment by vlasenko** [comment]
@hunglmtb This is a regression in spinjs, pushed the fix into master
