### ISSUE TITLE
subscribeToMore | question

### ISSUE THREAD

**Issue by seeden** [sysgears/apollo-universal-starter-kit#513]
Hi guys is subscribeToMore working for you correctly?
I am automatically unsubscribed after first data from subscription. Here is my ticket https://github.com/apollographql/apollo-client/issues/2581
I am just curious if it is working for you.
Thank you for you answer

**Comment by mitjade** [comment]
@seeden I'm testing this out and it seems we have the opposite problem. I never unsubscribe when leaving the page, but should on `componentWillUnmount()`

**Comment by seeden** [comment]
@mitjade I found problem in apollo-link-dedup. Without it is working. But I have same issue like you :) Thanks
