### ISSUE TITLE
pre-commit hook fail on template graphql with addmodule 

### ISSUE THREAD

**Issue by H1net** [sysgears/apollo-universal-starter-kit#523]
With the latest in master, if you do `yarn cli addmodule testmod`, `git add -A`, and then `git commit` the pre-commit hook fails because of the empty graphql files with an error like below:
```
$ git commit
husky > npm run -s precommit (node v6.11.3)

Running tasks for *.{js,jsx,json} [started]
Running tasks for *.graphql [started]
eslint --fix [started]
prettier --parser graphql --write [started]
prettier --parser graphql --write [failed]
→ × prettier --parser graphql --write found some errors. Please fix them and try committing again.


[error] src\client\modules\testmod\graphql\TestmodQuery.graphql: SyntaxError: Syntax Error GraphQL request (2:1) Unexpected <EOF>
[error]
[error] 1: # GraphQL queries
[error] 2:
[error]    ^
[error]  (2:1)
[error]   1 | # GraphQL queries
[error] > 2 |
[error]     | ^
Running tasks for *.graphql [failed]
→ × prettier --parser graphql --write found some errors. Please fix them and try committing again.


[error] src\client\modules\testmod\graphql\TestmodQuery.graphql: SyntaxError: Syntax Error GraphQL request (2:1) Unexpected <EOF>
[error]
[error] 1: # GraphQL queries
[error] 2:
[error]    ^
[error]  (2:1)
[error]   1 | # GraphQL queries
[error] > 2 |
[error]     | ^
eslint --fix [completed]
git add [started]
git add [completed]
Running tasks for *.{js,jsx,json} [completed]
× prettier --parser graphql --write found some errors. Please fix them and try committing again.


[error] src\client\modules\testmod\graphql\TestmodQuery.graphql: SyntaxError: Syntax Error GraphQL request (2:1) Unexpected <EOF>
[error]
[error] 1: # GraphQL queries
[error] 2:
[error]    ^
[error]  (2:1)
[error]   1 | # GraphQL queries
[error] > 2 |
[error]     | ^

husky > pre-commit hook failed (add --no-verify to bypass)
```
I notice that similarly empty files do not throw this error for previous modules I created, though the new files seem to have "Query" in the filename so I presume some changes have been made?

**Comment by mairh** [comment]
@mitjade Can you have a look. I guess this is the culprit https://github.com/sysgears/apollo-universal-starter-kit/commit/1b94d41726a2046f6da163aa081a64ae931e652e

**Comment by mitjade** [comment]
@H1net @mairh I am aware of this probmem. Will soon push some cli changes that will resolve this.

**Comment by vlasenko** [comment]
@mitjade I wonder if this is still an issue?

**Comment by mitjade** [comment]
@vlasenko It is still a problem. I am still a long way from having CRUD cli ready, so I will not be pushing any cli changes. Will check it is can resolve this.

**Comment by H1net** [comment]
Still an issue, though anyone having this that doesn't want to delete or complete the query could just `git commit --no-verify`.

I also note the added issue at the end of https://github.com/sysgears/apollo-universal-starter-kit/issues/605 where server graphql needs to be completed for app to build. You cannot have empty mutations/subscriptions.

These are pretty trivial problems and perhaps could just be documented.

**Comment by vlasenko** [comment]
@H1net We have public wiki now, editable by anyone, we can document quirks there, should be easy now:
https://github.com/sysgears/apollo-universal-starter-kit/wiki

**Comment by lyzhovnik** [comment]
Hi everyone. I am closing this issue, because the pull request https://github.com/sysgears/apollo-universal-starter-kit/pull/847 updated the CLI. And now after creating the new module You can commit and run the tests without any errors.
