### ISSUE TITLE
tests script picks up wrong db config

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-universal-starter-kit#527]
I am using postgresql in my project. The `let DB_TYPE` variable is set to `pg` in /config/db.js file. Running tests throw the following error:

`Knex:warning - migrations failed with error: Sqlite does not support alter column.`

Should I tweak settings somewhere else?

**Comment by sakhmedbayev** [comment]
I am sorry, I found it :-)

**Comment by mairh** [comment]
Please always post the solution too since someone else could also face the issue in future, so it's better to have some reference.

**Comment by sakhmedbayev** [comment]
@mairh you are right. My problem was that I am using PostgreSQL in my project and that one step in the migrations involves altering a table. Now, when I wanted to test the project, I got an error telling that SQLite does not support table altering. So I needed to find how the kit implements database connection for the tests. I found it in `./knexdata.js`.  So if someone else will face the same problem, please look at this file :-)
