### ISSUE TITLE
Where are global vars being assigned?

### ISSUE THREAD

**Issue by dcurletti** [sysgears/apollo-universal-starter-kit#538]
Is it fair to assume that the spinjs package is the one that is injecting __DEV__ and __BACKEND_URL__ ?

If this is true, it makes it very difficult to understand what variables are available and which aren't (since the spinjs npm documentation doesn't talk about __DEV__ at all).

**Comment by vlasenko** [comment]
You can use `spin -v watch` to check what Webpack configs are being generated by `spinjs`. Feel free to submit PR to update documentation of `spinjs` or the kit

**Comment by dcurletti** [comment]
good to know, thanks!
