### ISSUE TITLE
How is the project aware of the various graphqls files?

### ISSUE THREAD

**Issue by timhuff** [sysgears/apollo-universal-starter-kit#540]
The title kinda says it all. These *.graphqls files are scattered amongst the server - what combines them?

**Comment by mitjade** [comment]
These two files deal with this:

`src/server/modules/connector.js` -> L:40 `schemas()`
`src/server/api/schema.js` -> L:8 `typeDefs: [rootSchemaDef].concat(modules.schemas)`

**Comment by timhuff** [comment]
Thanks for the quick answer!
