### ISSUE TITLE
Adding an External Option to the Webpack Config breaks the builder

### ISSUE THREAD

**Issue by dcurletti** [sysgears/apollo-universal-starter-kit#542]
```
const server = {externals: {}}
```

Adding the option `externals` breaks the build.  Even if I don't pass anything to it.

https://github.com/sysgears/apollo-universal-starter-kit/blob/master/tools/webpackAppConfig.js#L2-L9

Currently investigating as I need to add `newrelic` as an external to the server.

**Comment by dcurletti** [comment]
Nothing happens when I add it to the web config.  I'm assuming this might be a lower-level error with webpack and nodejs.

**Comment by vlasenko** [comment]
@dcurletti Add lower down the same file instead:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/tools/webpackAppConfig.js#L41-L101

**Comment by dcurletti** [comment]
beautiful. thank u. trying now.

**Comment by dcurletti** [comment]
works. thanks!
