### ISSUE TITLE
Errors are being squashed by undefined next()

### ISSUE THREAD

**Issue by verdverm** [sysgears/apollo-universal-starter-kit#564]
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/src/server/middleware/graphql.js#L23

When there is an error in a module's `createContextFunc` (as an arg when creating a Feature (generally in index.js in the module)...

The response is `"Invalid options provided to ApolloServer: next is not a function"` Triggered at the above line.

Changing `next(e)` to `log.error(e); throw e` provides more context, but I'm not really sure why next is not defined in the first place.

It seems we should log and throw, as the errorMiddleware picks up the exception anyway. Logging the error provides more context on the server side.

Thoughts? Any idea why `next` is `undefined`?

**Comment by vlasenko** [comment]
@verdverm Yes, but we should not log and throw, just throw, because errorMiddleware do logging for us, it is responsible for handling all middleware errors on server side

**Comment by vlasenko** [comment]
@verdverm I've pushed the fix, see above
