### ISSUE TITLE
Antd UI fires the form validation on page load

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#571]
When navigating to any page with a `form`, the validation kicks in on the page load, whereas in reality, it should kick in once the field loses focus and is empty or whatever validation you have.

<img width="769" alt="screen shot 2017-12-14 at 16 06 20" src="https://user-images.githubusercontent.com/4072250/33996329-89fcc5d2-e0e9-11e7-91db-7394c6999476.png">

**Comment by vlasenko** [comment]
Fixed via: https://github.com/sysgears/apollo-universal-starter-kit/commit/bef849a22075775e928f17458ccc2be7a197ac35
