### ISSUE TITLE
Apollo server errors and exception paths

### ISSUE THREAD

**Issue by verdverm** [sysgears/apollo-universal-starter-kit#581]
I encountered the following situation, wondering what your thoughts are about where the issue really lies.

When there is an error in the dynamic server components (like createContext) the underlying error `Invalid options provided to ApolloServer: ...` is getting squashed out.

The `JSON.parse` from the link below is throwing an exception on the error message above.

https://github.com/apollographql/apollo-fetch/blob/51c87f001f8f50bfb16d7eb028b5510fd5f36c1e/packages/apollo-fetch/src/apollo-fetch.ts#L155

The code in that file eventually reaches the `throwHttpError` causing the SSR to bug out and squash the true underlying error.

The problem is that the validity of the server should have occurred and it should not be taking requests (i.e. is should be down). But... because javascript doesn't parse the code until it needs to, the error doesn't occur until a request is made.

The error I see is a `500 Internal server error` with a irrelevant stack track. It's been super hard to track down some of these errors. I wasn't even getting the redbox.

So happens the serialization library in the `errorMiddleware` was also bugging out at the same time. I switched that to `JSON.stringify` and the SSR / no redbox errors went away.

I ended up adding a `__SSR__` switch in the errorMiddleware to get the underlying message to the browser. Still sometimes the stack trace is not helpful.

My `errorMiddleware now looks like this:

```
function errorMiddleware(e, req, res, next) {
  log.error(e);

  if (__DEV__ || !assetMap) {
    assetMap = JSON.parse(fs.readFileSync(path.join(spinConfig.frontendBuildDir, 'web', 'assets.json')));
  }

  const stripErr = stripCircular(e)
  let returnedErr = stripErr;

  // now do some introspection
  if (__SSR__ && returnedErr.networkError) {
    let val = e.networkError.response.raw
    console.log(val)

    returnedErr.message = val
  }

  // Causing issues for whatever reason
  //const serializedErr = serialize(stripErr)
  // Use json stringify instead
  const serializedErr = JSON.stringify(returnedErr)

  const serverErrorScript = `<script charset="UTF-8">window.__SERVER_ERROR__=${serializedErr};</script>`;
  const vendorScript = assetMap['vendor.js'] ? `<script src="/${assetMap['vendor.js']}" charSet="utf-8"></script>` : '';

  res.status(200).send(
    `<html>${serverErrorScript}<body><div id="content"></div>
    ${vendorScript}
        <script src="/${assetMap['index.js']}" charSet="utf-8"></script>
        </body></html>`
  );
}
```

**Comment by vlasenko** [comment]
@verdverm Thank you for noticing and describing this in detail. I have pushed commit that should handle this class of errors. The logic for handling this class of errors is a bit tricky to understand and for sure my take on this is non-ideal. Feel free to discuss this in the chat if you have problems with the fix or have ideas for improvement
