### ISSUE TITLE
Using custom Graphql server 

### ISSUE THREAD

**Issue by davidyin1212** [sysgears/apollo-universal-starter-kit#585]
Hey I know this question has been asked several times but it seems like the code base has been updated and no longer contains webpack.app_config.js as mentioned before to set the custom url. Where and how do we setup it up now?

**Comment by vlasenko** [comment]
@davidyin1212 Yes, now if you are using external backend - specify URL in .spinrc.json -> options -> backendUrl. You can also specify this option per-builder, in can if your web front-end and android/ios app use different backend urls

**Comment by davidyin1212** [comment]
@vlasenko ok so when I do that now I don't see the UI anymore all I see is a graphql playground is this expected?

**Comment by vlasenko** [comment]
@davidyin1212 You need to also turn `ssr` off and start checking web browser JavaScript console for errors

**Comment by claym** [comment]
a couple question - what does the SSR option do?

is it possible to specify the backendurl as a config variable?

**Comment by vlasenko** [comment]
@claym SSR - server side rendering
backendUrl is a config variable, `.sprinrc.json` config

**Comment by claym** [comment]
@vlasenko ok the SSR is what i thought

as far as config variable, i meant external, like through a heroku config variable. sorry, wasn't specific.

**Comment by vlasenko** [comment]
@claym You can use several configs now to feed different config during development and production to our build system - `spinjs`. This will be changed very soon, though, I'm going to roll out `.spinrc.js` support today or tomorrow, which will have maximum possible flexibility

**Comment by sakhmedbayev** [comment]
Is it possible to use custom backend url with SSR left ON?

**Comment by vlasenko** [comment]
@sakhmedbayev Yes, sure it is possible to do it, the way you describe

**Comment by sakhmedbayev** [comment]
Good! I just got confused by previous comments.
