### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by wojcikiewiczm** [sysgears/apollo-universal-starter-kit#588]
Is there any way to add svg support in less?

**Comment by wojcikiewiczm** [comment]
Yes sorry. I just want to use svg url in less files like this.

`
.edit-button {
  background-image: url('public/icons/edit_gray.svg');
}
`

But I'm getting error
`Module not found: Error: Can't resolve './public/icons/edit_gray.svg'`

**Comment by vlasenko** [comment]
@wojcikiewiczm Hmm, this should be supported out of the box. Are you sure the path to svg is correct what if you place test svg near less file and try to import it?

**Comment by vlasenko** [comment]
@wojcikiewiczm Let me try to reproduce this....

**Comment by wojcikiewiczm** [comment]
@vlasenko Ok again my fault 😄 path was wrong thanks for your time 👍

**Comment by vlasenko** [comment]
No problems!

**Comment by H1net** [comment]
I adore this kit! However I must admit that when I was getting going I had a few problems like this which killed a day of productivity for me and it would be helpful to put some more examples in the docs. I think the pattern of having a public folder where assets can go (or putting assets in module folders) and loading them through a library, is not clearly described too.
I also had a hell of a time trying to get icons to work. The two packages included for icons on native work fine on mobile but not web and I had a real headache getting others to work. I ended up just putting the cdn link to fontawesome in my middeware html.jsx
I get that the kit really focuses on the difficult integration issues that it solves (apollo, ssr, native...thanks for that!), but I still reckon it would really benefit from a couple of simple examples of getting the basics going.

**Comment by vlasenko** [comment]
Thank you for sharing your experience @H1net. I really appreciate it and agree with you on most your points. I have created the catch all issue where you can put your wishes for documentation. We will collect wishes there and will try to dedicate part of our efforts to documentation as well as working on code imrpovements. Please keep in mind that the simple things to document will highly likely be addressed first:
https://github.com/sysgears/apollo-universal-starter-kit/issues/589

**Comment by vlasenko** [comment]
@H1net Another problem that I see, is that somehow people miss that we have a chat where you can just shoot question and someone from users or contributors will answer it. No need for formalities - you will likely get help in real time:
https://gitter.im/sysgears/apollo-fullstack-starter-kit

I think people miss it somehow and we need to make it more prominent in the header of README.md
