### ISSUE TITLE
Help making login info persistent 

### ISSUE THREAD

**Issue by theRealFakeRock** [sysgears/apollo-universal-starter-kit#596]
Hi,
I apologize if this is the wrong place for this, I'm kinda new.
I have setup react native to have a login screen and hidden routes.
The only problem is that I am having a hard time finding a way to make the login persistent. 
Any help is appreciated.

**Comment by verdverm** [comment]
The main flow to auth is

1. Login
2. Get token back
3. Store token
4. Use token to make requests (also use embedded info for various client side things.
(5.) The token is actually refreshed every minute, so could be almost every request. It is passed around with `x-token` headers 

The way the token is stored is in a cookie (and/or?) local storage.

Look at these files to see what is going on, client side

- src/client/modules/user/containers/Login.jsx (stores first token in login response)

- src/client/modules/user/containers/Auth.jsx  (logout is here, it deletes the token in local storage)
- src/client/modules/user/index.web.jsx ( the "middleware" parts )
- https://github.com/sysgears/apollo-universal-starter-kit/blob/370a8b35d01286f031ad6cd1a4d8cb75d31347fa/src/client/app/Main.jsx#L60  (this gathers connectionParams for all connections, (how the token makes it into request)


Hope that helps get you headed the right directions

**Comment by theRealFakeRock** [comment]
Thank you
