### ISSUE TITLE
When using server side rendering Ant Design's Drawer Menu throws error, ServerError: document is not defined

### ISSUE THREAD

**Issue by adam-s** [sysgears/apollo-universal-starter-kit#608]
If the Drawer element is rendered when only in the client by navigating to the page the element is on, it works correctly. However, when the page is reloaded or updated and is one the route the element is on, it will throw and error, ServerError: document is not defined.

How do I insure that the module has access to `document` when rendered on the server?

ServerError: document is not defined
Drawer._this.setLevelDomTransform
at /home/adam/PhpstormProjects/joboty-admin/node_modules/rc-drawer-menu/lib/Drawer.js:215:9
Drawer._this.getChildToRender
at /home/adam/PhpstormProjects/joboty-admin/node_modules/rc-drawer-menu/lib/Drawer.js:247:15
Drawer.render
at /home/adam/PhpstormProjects/joboty-admin/node_modules/rc-drawer-menu/lib/Drawer.js:353:27
walkTree
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:36:32
walkTree
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:61:21
forEachSingleChild
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:858:8
traverseAllChildrenImpl
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:762:5
traverseAllChildrenImpl
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:778:23
traverseAllChildren
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:833:10
Object.forEachChildren
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:878:3
walkTree
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:59:22
walkTree
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17
walkTree
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17
walkTree
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17
walkTree
at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17

**Comment by vlasenko** [comment]
@adam-s Maybe its better to open issue on `rc-drawer-menu` instead? Why do you open it on the kit, how can we solve it here?

**Comment by vlasenko** [comment]
@adam-s In case `rc-drawer-menu` cannot be rendered on a server side, there is an example of approach how to render just this component on a client-side and not on the server:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/src/client/modules/subscription/components/SubscriptionView.web.jsx#L17-L23
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/src/client/modules/subscription/components/SubscriptionView.web.jsx#L57-L61

**Comment by adam-s** [comment]
This is probably something to add to the documentation. Everything is new to me so I'm not sure if when something goes wrong it is me, a third party module, or apollo univeral starter kit.

**Comment by vlasenko** [comment]
@adam-s You would have known this after having experience with React. The kit doesn't free you from studying React and Apollo and all the other technologies used inside it. But I agree with you that it would be nice to have documentation on the approaches like this that solve frequent common problems appearing in practice.

**Comment by adam-s** [comment]
How about a higher order component to wrap any component that should only be rendered on the client?


`client/modules/common/components/ClientOnly.jsx`
````
import React, { Component } from 'react';

const clientOnly = Comp => {
  return class ClientOnly extends Component {
    state = {
      client: !__SSR__ && !__TEST__
    };
    componentDidMount() {
      this.setState({ client: __CLIENT__ });
    }
    render() {
      return this.state.client && <Comp />;
    }
  };
};

export default clientOnly;

```

**Comment by vlasenko** [comment]
@adam-s Yes, that would work, feel free to create Pull Request
