### ISSUE TITLE
iOS build broken? "Can't find variable __DEV__ "

### ISSUE THREAD

**Issue by hanibash** [sysgears/apollo-universal-starter-kit#621]
Hi there, I got an error similar to the following on latest master (`0212f1f19492a31188c4e90a333b75a1b282aad6`) when attempting to open the iOS app via Expo:

```
Can't find variable __DEV__ in node_modules/spinjs/react-native-polyfills/react-native-polyfill-16.js
```

I just rolled back to `fe44d88885e0f83f08881cc31d73dad95e336d00` and its working fine.

https://github.com/sysgears/apollo-universal-starter-kit/compare/fe44d88885e0f83f08881cc31d73dad95e336d00...master

**Comment by chrisbull** [comment]
I'm getting a "Can't find variable: __DEV__" as well

![simulator screen shot - iphone 8 plus - 2018-01-21 at 21 13 19](https://user-images.githubusercontent.com/753112/35206215-eeee6346-feef-11e7-8ba3-f1caa96d9ca1.png)

**Comment by vlasenko** [comment]
@hanibash @chrisbull Sorry guys, should be fixed now. The error was in Webpack DLL generation for mobile platforms. You should fetch latest kit sources, remove `build` folder and start `yarn watch` again
