### ISSUE TITLE
starter kit not working on mobile (tested on android)

### ISSUE THREAD

**Issue by redrose218** [sysgears/apollo-universal-starter-kit#627]
this is what I have done:
-package.json
"watch": "cross-env DEBUG=spinjs spin watch"

-packages/mobile/.spinrc.js
config/builders/android/enabled: true

-command
yarn
yarn seed
yarn watch

-result
expo app freezes in splash
![screenshot_20180125-234124](https://user-images.githubusercontent.com/34869395/35418370-8ba89e20-023a-11e8-8b6f-5bb2e18c427b.png)

-logs
![untitled](https://user-images.githubusercontent.com/34869395/35418389-a0e06f7a-023a-11e8-8fec-1e027ab2b9be.png)
![untitled2](https://user-images.githubusercontent.com/34869395/35418396-a3965e00-023a-11e8-89af-3433a19357d6.png)

**Comment by vlasenko** [comment]
@redrose218 You see this error because you have `Hot Reload' enabled in Expo Client dev menu. We didn't implement support for Hot Reload for Expo yet, its a lot of work.

**Comment by vlasenko** [comment]
@redrose218 This should be fixed in `spinjs@0.4.87`, that version is used in master of the kit now

**Comment by vlasenko** [comment]
@redrose218 Please try latest master, a bunch of bug fixes with mobile asset handling on Windows have been pushed that should hopefully resolve this issue

**Comment by vlasenko** [comment]
Closing because of topic starter inactivity
