### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'font-awesome'

### ISSUE THREAD

**Issue by Morphexe** [sysgears/apollo-universal-starter-kit#634]
Some packages when added break the build, I can't  seem to add font-awesome for example since it breaks with that error.

Where should I define which packages should be bundled or not?

**Comment by vlasenko** [comment]
@Morphexe I plan to fix this class of issues today. The font-like dependency packages should not be included into a Webpack DLL, spinjs should detect this kind of dependencies and exclude them from DLL

**Comment by Morphexe** [comment]
@vlasenko Its not only font-awesome, there are a couple of other packages that break the bundle, for example react-selectize and few others that I have found out, so maybe instead of auto detecting  there should be a mechanism to handle it? =)

**Comment by vlasenko** [comment]
@Morphexe I have received your message in a notification, but can't find it here:
> @vlasenko Its not only font-awesome, there are a couple of other packages that break the bundle, for example react-selectize and few others that I have found out, so maybe instead of auto detecting there should be a mechanism to handle it? =)

Is autodetection mechanism fails on any of them?

**Comment by Morphexe** [comment]
I think I deleted the comment by mistake after posting sorry!
Yes it crashes in font-awesome, react-selectize with the same error message, I actually found quite a few modules that crashed the vendor. for example react-transition does too it seems.

Was your commit supposed to fix this? just asking because I am still finding the same thing happening right now with latest.

**Comment by vlasenko** [comment]
@Morphexe Yes, it should fix this. Have you installed new versions of dependencies after `git pull` via running `yarn` in the root of cloned repo?

**Comment by Morphexe** [comment]
@vlasenko  I should have slept more today it seems when I merged the commit I accidentally kept my old spin version which turned out to return the error!

Working perfectly now, thank you very much! =)

**Comment by vlasenko** [comment]
@Morphexe Great, thank you for letting know!
