### ISSUE TITLE
How to `npm/yarn link` local packages?

### ISSUE THREAD

**Issue by verdverm** [sysgears/apollo-universal-starter-kit#638]
While developing the connector-js library, it would be easier (standard?) to link the local package.

When I do this (at the root or in one of the workspaces) I get the following error:

```
Module build failed: ReferenceError: Unknown plugin "babel-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/tony/go/src/github.com/hofstadter-io/connector-js/lib"
```

I'm not exactly sure what is happening here.

I can add the module with `lerna add connector-js`   _if..._ published to npm.

**Comment by vlasenko** [comment]
@verdverm I think you are facing this issue:
https://github.com/webpack/webpack/issues/1866

The simplest workaround for now is to move `connector-js` directory inside `apollo-universal-starter-kit` dir, and re-link it again in this case I think using `yarn link`-ed `connector-js` will work.

**Comment by vlasenko** [comment]
@verdverm The better workaround is to add the following to `.spinrc -> options`:
```
webpackConfig: { resolve: { symlinks: false } }
```

**Comment by vlasenko** [comment]
@verdverm Maybe this approach should need to be integrated into `spinjs` as well:
https://github.com/webpack/watchpack/issues/61

**Comment by verdverm** [comment]
seems to be working, thanks!

**Comment by verdverm** [comment]
Welp, hit an issue with Babel and ES6 classes. There seems to be a couple of options to fix it. I'm just `yarn build`-ing in the linked module.

**Comment by vlasenko** [comment]
@verdverm What issue did you hit?

**Comment by verdverm** [comment]
I described it in the external-modules.md PR

**Comment by verdverm** [comment]
#646

**Comment by vlasenko** [comment]
@verdverm I think this is not an issue then. Why should we transpile yarn-linked modules?

**Comment by verdverm** [comment]
umm, my thoughts were

1. we shouldn't transpile, just need to figure out the babel setup I think. How application-specific does this get?
2. with transpiling, they are exactly the same as they come from npm after publishing. Extra dev work, but no need to conflate babel either

**Comment by vlasenko** [comment]
@verdverm I don't really understand you. When you have `npm-linked` your module to the kit. it is your responsibility to build it after changes. It is not kit's responsibility to run babel on `npm-linked` modules
