### ISSUE TITLE
Include React Primitives or React Native Web for portable components across mobile and web

### ISSUE THREAD

**Issue by adam-s** [sysgears/apollo-universal-starter-kit#652]
Consider using [React Primitives](https://github.com/lelandrichardson/react-primitives) or its parent [React Native Web](https://github.com/necolas/react-native-web) for portable components across different devices. 

Here is a [video](https://www.youtube.com/watch?v=hNwQPJy-XZY) by Leland Richardson at Airbnb about using React Primitives to create a truly cross-platform UI.

**Comment by verdverm** [comment]
I think it's being used already to some extent

https://github.com/sysgears/apollo-universal-starter-kit/blob/4977a97755245a3dff24eb319d510429999ad45c/packages/client/package.json#L76

https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/client/src/index.js

**Comment by verdverm** [comment]
spinjs is doing things as well, https://github.com/sysgears/spinjs/blob/master/src/plugins/ReactNativeWebPlugin.ts

I'm not familiar with how all the processing flows, but it does look to use 'react-native-web'

( I think the AUSK+spinjs is really cool, once #651 is a thing we will get another level of flexibility )

**Comment by adam-s** [comment]
Nevermind... I was thinking about having a third UI library but this is how the project works. React Native Web is becoming Portland, OR style hipster trendy so it might entice some trend setting developers to use this starter kit if they know it is built with / on it.
