### ISSUE TITLE
[Poll] Convert the kit to TypeScript while still supporting ES6 modules

### ISSUE THREAD

**Issue by vlasenko** [sysgears/apollo-universal-starter-kit#657]
This is the poll to gather opinions about converting this kit to TypeScript while still supporting the code written in ES6. 

The rationale for this change is that various GraphQL libraries have better adoption of TypeScript, rather then Flow.

We are going to drop Flow support, it shouldn't be a problem since it was not really supported well by Apollo libraries since the launch of Apollo 2.

Thumbs up for in favor and Thumbs down for not in favor.

**Comment by mairh** [comment]
I like supporting a static type checker. However, there is going to be a learning curve for me to understand TypeScript. We can drop Flow though since we hardly use it in the kit codebase. Note: I have still voted yes.

**Comment by xeoneux** [comment]
Programming in TypeScript is a lot better with the recent IDE/Editors support and would surely prefer that 👍

**Comment by sakhmedbayev** [comment]
Not sure about that. It seems that the whole vanilla javascript world (ES6 for instance) is going toward adopting a "TypeScript" paradigm.

**Comment by vlasenko** [comment]
@sakhmedbayev Yes, it seems so. Why do you vote against converting to TypeScript then?

**Comment by sakhmedbayev** [comment]
@vlasenko when I said: "adopting "TypeScript" paradigm", I meant that vanilla javascript will be there without "TypeScript". I just think that javascript world is already pretty crazy in terms variety standards :-) Why do we need to support it?!

**Comment by vlasenko** [comment]
@sakhmedbayev Ha-ha :) I agree that its crazy. With TypeScript we will get static type checking, which will help to make us more productive. This is the point of the kit to achieve the best productivity for developers using it

**Comment by sakhmedbayev** [comment]
Is not the kit already works pretty good in an IDE?

**Comment by vlasenko** [comment]
@sakhmedbayev I bet with TypeScript it should work even better in IDE

**Comment by sakhmedbayev** [comment]
All right! :-) I will keep to my decision. Let's see what other folks think.

**Comment by vlasenko** [comment]
@sakhmedbayev Yep, sure, thanks for sharing your thoughts!
