### ISSUE TITLE
Internet explorer support

### ISSUE THREAD

**Issue by t0x1c123** [sysgears/apollo-universal-starter-kit#659]
Hello how do I enable IE 11 support? I'm using antd 2 but I'm getting errors in IE console like
``Object vendor_web is not defined. and Syntax error``
And if I click on that error a get this https://ctrlv.cz/shots/2018/02/19/ltCw.png

Do I need to turn some babel polyfills on or something like that? I'm not sure if it's antd error or some other error. Because demo app on heroku is working but it's using bootstrap. So I'm not sure if it's antd error or some other error.

I really need to fix it please

Update: I also jumped to "single" branch and there is also problem with edge and IE 11 😢

**Comment by mairh** [comment]
Is it working fine on all other browsers?

Also, could you paste the terminal error?

**Comment by vlasenko** [comment]
@t0x1c123 @mairh I have checked IE 8 and when I switch from Boottstrap to AntD it works fine for me

**Comment by t0x1c123** [comment]
@vlasenko @mairh Thank's for reply. So the first scenario is that we're developing app that has to run in IE 11. So we developed app in chrome and then we tried it in IE 11 and this came up.

All errors ->
https://ctrlv.cz/shots/2018/02/20/1ZEQ.png
Error 1 detail -> https://ctrlv.cz/shots/2018/02/20/rb8f.png
Error 2 detail  ->https://ctrlv.cz/shots/2018/02/20/edwf.png
Spinjs version is 0.4.71

So then I thought that maybe we are using some bad package that dont support IE or something like that. So I pulled clean starter kit from branch "single" (because our app is based on it). And also got error in IE 11 and Edge but it's different error.

Error in console ->https://ctrlv.cz/shots/2018/02/20/PHcS.png
Error detail ->https://ctrlv.cz/shots/2018/02/20/sW8F.png

I didn't change nothing in webpack config. And yes in chrome and firefox everything runs good.

**Comment by vlasenko** [comment]
@t0x1c123 Thanks. So looks like you face this issue:
https://github.com/webpack/webpack-dev-server/issues/1084
Could you try some remedies from there, e.g. update webpack-dev-server to `2.11.1`?

**Comment by t0x1c123** [comment]
@vlasenko Nope that didn't help in any of the app.

**Comment by t0x1c123** [comment]
@vlasenko I managed to figure out that there is problem with subscriptions-transport-ws and apollo-link package.

**Comment by vlasenko** [comment]
@t0x1c123 Please check the latest code from `single` branch, it should fix IE 11 support for you
