### ISSUE TITLE
[Question] Integrate front end with laravel-mix

### ISSUE THREAD

**Issue by hunglmtb** [sysgears/apollo-universal-starter-kit#663]
Has anyone tried to integrate the the starter kit web front-end with laravel-mix yet or any suggestion to do this?
I need to do it for my laravel back-end and purpose  is reusing it for mobile front end.
I've tried it  by putting addition config in webpack.mix.js at laravel root directory

```
let mix = require('laravel-mix');
mix.webpackConfig( require('spinjs').createWebpackConfig(__dirname, '.spinrc.js', 'web'))
.webpackConfig({
    resolve: {
    	alias: {
    	      'react-native': 'react-native-web',
    	      'react-navigation': 'react-navigation/src/react-navigation.web.js'
    	    }
    },
    module: {
    	rules: [
                {
                    test: /\.(graphql|gql)$/,
                    exclude: /node_modules/,
                    use: ['graphql-tag/loader']
                }
            ]
    },
    target: 'node'
})
.react('packages/client/src/index.js', 'public/js');
```

 but when running with yarn

`cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

it shows many errors with loaders (graphqp, expo icons, native-base, native-navigation ... )
And is impossible to create a spinrc config for building this task to js resource as laravel-mix requirements?
Thanks

**Comment by vlasenko** [comment]
@hunglmtb How about posting the resulting Webpack config and all these errors here? We have lost all our magic balls to read your thoughts.

**Comment by vlasenko** [comment]
@hunglmtb It is very difficult to help you. You haven't provided how did you modify the kit to include `laravel` and you didn't provide the error messages that is being thrown. Both of these points are very important. I'm closing this question until this information will be provided
