### ISSUE TITLE
Integration with Dashboard / Admin Template

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#665]
How about this integration. When a user signs in successfully, a Dashboard is shown.

This dashboard is great and supports Bootstrap 4:
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/tree/master/React_Full_Project

For instance, the user profile details are shown by default.

**Comment by coooolers** [comment]
Pl. find attached the probable solution for this issue. The solution works for antd. It has the 4 files:

a. SideBar.jsx component which is displayed after the user is logged in successfully.
b. Modified PageLayout.jsx  which accepts an optional boolean named sideBar whose default value is false.
c. ProfileView.web.jsx where a call to the PageLayout component accepts the sideProp whose value is {true} when the user is logged in successfully.
d. Enable the antd and disable the bootstrap.

Hope the other contributors will refine it further and integrate the solution inside the kit.

Thanks


[SideBarAfterSuccessfulLogin.zip](https://github.com/sysgears/apollo-universal-starter-kit/files/1860798/SideBarAfterSuccessfulLogin.zip)

**Comment by coooolers** [comment]
Could you guys pl. tell me whether this feature will be incorporated in the kit or not? Great, if you do it!

If not, let us close this issue.

**Comment by vlasenko** [comment]
Let's close it. If anyone have plans to implement it - he can reopen this issue then
