### ISSUE TITLE
No way to delete item in list using swipe on android devices

### ISSUE THREAD

**Issue by sergei-gilevich** [sysgears/apollo-universal-starter-kit#667]
**Steps to reproduce:**
1) Open posts list 
2) Do swipe left on the post

**Expected result:**
A button appears for removing the item.
**Actual result:**
Switch to other tab.

**Comment by vlasenko** [comment]
@sergei-gilevich Sergey, is this still the case?

**Comment by sergei-gilevich** [comment]
@vlasenko No. This is fixed in #666.

**Comment by vlasenko** [comment]
@sergei-gilevich Yup, thanks!
