### ISSUE TITLE
Graphql TokenAftware Not Properly Updating Local Storage Cookie

### ISSUE THREAD

**Issue by dcurletti** [sysgears/apollo-universal-starter-kit#674]
Hi all-

The current graphql afterware function, [tokenAfterware](https://github.com/sysgears/apollo-universal-starter-kit/blob/dac7f3e06ed4e4af84136bb053b007c969702ccd/packages/client/src/modules/user/index.web.jsx#L25-L26), is not setting the correct cookie to localstorage. 

In its current iteration, it simply sets whatever cookie was sent in the request, which happens to be set by the function above it, [`tokenMiddleware`.](https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/client/src/modules/user/index.web.jsx#L18-L22)

The problem is noticeable when:
* A user sends an ajax request to the server, and the server responds with a set-cookie response
* The user tries to access an "auth route" which uses the function [checkAuth](https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/client/src/modules/user/containers/Auth.jsx#L20-L23) and they are rejected because the local storage token is no longer in sync with the cookies token.

I'm still deciding on how I'd prefer solving this:
* Adjust the `tokenAfterware` function to check cookies rather than options (probably requires importing a cookie parsing library)
* Only respect the token in the cookies, removing the use of the local storage token (this would mean removing [these lines](https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/client/src/modules/user/containers/Auth.jsx#L20-L23), which I'm okay with since there is duplicate work when checking both the cookie and local storage tokens, which also allows for one source of truth (cookies rather than local storage).

**Comment by vlasenko** [comment]
Thanks @dcurletti During this week I'm going to rework JWT auth support completely.

**Comment by dcurletti** [comment]
Awesome!

**Comment by vlasenko** [comment]
@dcurletti This should be resolved now in the master. We have separate support now for both authentication via server-side sessions and via JWT tokens. They can work in isolation, e.g. you can use only sessions for auth, only JWT or simultaneously. By default they both turned on, so they work simultaneously.
