### ISSUE TITLE
Login Error: Profile Page not displayed

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#679]
I am getting this error:
TypeError: Cannot read property 'indexOf' of undefined
Object.isSelected
at /home/cool/Project/apollo-universal-starter-kit/packages/server/node_modules/rc-menu/es/MenuItem.js:121:0
Object.render
at /home/cool/Project/apollo-universal-starter-kit/packages/server/node_modules/rc-menu/es/MenuItem.js:127:0
finishClassComponent
at /home/cool/Project/apollo-universal-starter-kit/packages/server/node_modules/react-dom/cjs/react-dom.development.js:7873:0

**Comment by vlasenko** [comment]
Where do you get this error? Is this the full stack trace? Have you recreated your DB after updating source code?

**Comment by mitjade** [comment]
@vlasenko This is the problem if you switch to `antd`. I already fixed it at my end. Will share the fix today.

**Comment by vlasenko** [comment]
@mitjade Oh, ok, thank you Mitja!

**Comment by mitjade** [comment]
Should be fixed with #680.

**Comment by coooolers** [comment]
Thanks. It has been fixed.
