### ISSUE TITLE
Pagination at client side

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#694]
Is it to possible to implement the "standard" pagination:

1. Let's say 55 posts are there in total. This means 6 icon buttons are displayed: 1, 2, and so on including the Next/Previous and First/Last Buttons.

2. Give the user a small drop down where he can select the number of rows to display in a page, let's say, 5, 10, 15, 20

Currently it shows all the 20 posts when the Next Page button is clicked which includes the first 10 posts that are already seen by the user causing unnecessary lengthy pages.

**Comment by vlasenko** [comment]
Added in #713
