### ISSUE TITLE
run on HTTPS rather than HTTP

### ISSUE THREAD

**Issue by workforcecity** [sysgears/apollo-universal-starter-kit#697]
Any can guide how to setup HTTPS rather than HTTP for this project ?

**Comment by vlasenko** [comment]
Should be straightforward, modify
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/server/src/server.js
to look like this:
https://stackoverflow.com/questions/11744975/enabling-https-on-express-js
