### ISSUE TITLE
Problem running the app in Android Studio

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#704]
I installed the Android Studio, then created an Android Virtual Device.

I ran this starter kit app: yarn watch

But it ran the web app only. It didn't run the Android app. Which step am I missing, kindly enlighten me. 

Thanks

**Comment by vlasenko** [comment]
Excerpt from `README.md`:
> For running Android or iOS you need to set in .spinrc.js builders.ios.enabled and/or builders.android.enabled field true.

**Comment by coooolers** [comment]
By default, they are already set to true in the packages/mobile/.spinrc.js false

if (process.env.NODE_ENV === 'production') {
  config.builders.android.enabled = true;
  config.builders.ios.enabled = true;
  config.options.defines.__API_URL__ = '"https://apollo-universal-starter-kit.herokuapp.com/graphql"';
  config.options.defines.__WEBSITE_URL__ = '"https://apollo-universal-starter-kit.herokuapp.com"';
  // Generating source maps for production will slowdown compilation for roughly 25%
  config.options.sourceMap = false;
}

But the environment is production.

**Comment by vlasenko** [comment]
`yarn watch` - is a development environment. You should set them to true for development environment.

**Comment by vlasenko** [comment]
@coooolers It is incorrect, you set wrong API_URL and WEBSITE_URL for development environment. Don't do this. Set android.enabled to true in the `config` object instead above.

**Comment by vlasenko** [comment]
@coooolers Another thing is that when you run `yarn watch` the `process.env.NODE_ENV` is `undefined`, not `development`

**Comment by coooolers** [comment]
Finally this error has been resolved. Thanks. 

But there is another error now:
webpack-for-android error Error running adb: No Android device found. 

In my .profile file under the home directory, I did this:
#Added this to get access to the Android Studio's adb command lying in the ~/Android/Sdk/platform-tools directory
if [ -d "$HOME/Android/Sdk/platform-tools" ] ; then
  PATH="$PATH:$HOME/Android/Sdk/platform-tools"
fi

The path to the adb tool is set correctly. But the problem is with configuring the Android Virtual Device.

Could you pl. help me setting the device correctly.

Note: There is no such option: Tools > Android > Android Virtual Device in the menu,

**Comment by vlasenko** [comment]
No, this is out of scope. Just google the way to set up Android Virtual Device

**Comment by coooolers** [comment]
Able to fix the error and AVD is running successfully now. What I did was I enabled the VT-x option in the machine's BIOS.

**Comment by vlasenko** [comment]
@coooolers Try to use x86-64 AVD, it should be much faster then ARM7 AVD
