### ISSUE TITLE
Starter kit doesn't work on windows

### ISSUE THREAD

**Issue by t0x1c123** [sysgears/apollo-universal-starter-kit#705]
Hi, I pulled of latest stable branch and after installing packages with yarn command and using yarn watch command I'm getting weird error.

> C:\dev\apollo-universal-starter-kit>yarn watch
yarn run v1.6.0
$ spin watch
System cannot find the path specified
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I'm running: Windows 10 yarn 1.6.0 (It was 1.3 but I tried to upgrade it to newes) and node v8.9.3

Thanks

**Comment by t0x1c123** [comment]
Nope didn't help. Getting error that spin command doesn't exist. But i figured it out. I look in spinjs.sh and found this:

```
@IF EXIST "%~dp0\/bin/sh.exe" (
  "%~dp0\/bin/sh.exe"  "%~dp0\..\spinjs\spin.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  /bin/sh  "%~dp0\..\spinjs\spin.js" %*
)
```

But in older versions was this

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\spinjs\spin.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\spinjs\spin.js" %*
)
```

So when I changed it to older version code it's working. So apparently problem is with sh.exe which is not in node_modules. Any idea why?

**Comment by vlasenko** [comment]
@t0x1c123 The problem is this commit:
https://github.com/sysgears/spinjs/commit/d4af4f9d5676caa04be25ee9d15fe8f792b4a085
I'm going to rollback it for now, unless someone finds the way to make it work cross-platform
