### ISSUE TITLE
Will this starter work with Statext and Unstated?

### ISSUE THREAD

**Issue by brianyang** [sysgears/apollo-universal-starter-kit#707]
Where can I see if this application is wrapped in a `Provider`? 

Will this work with tiny state management libs like [Statext](https://github.com/eldh/statext)?

**Comment by vlasenko** [comment]
@brianyang The starter kit is just normal React application, it should work with any React library. The client-side React tree root is here:
https://github.com/sysgears/apollo-universal-starter-kit/blob/ee7a7383fca6d71bebbd14f8037edbb3b2a24167/packages/client/src/app/Main.jsx#L83-L90
The server-side React tree root is here:
https://github.com/sysgears/apollo-universal-starter-kit/blob/ee7a7383fca6d71bebbd14f8037edbb3b2a24167/packages/server/src/middleware/website.jsx#L39-L48

**Comment by vlasenko** [comment]
@brianyang Btw, you can also manage state via Apollo Link State, which is the default strategy used inside this kit (but this is optional and up to you):
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/client/src/modules/post/containers/PostComments.jsx#L170-L179

**Comment by brianyang** [comment]
@vlasenko thanks for pointing this out. Apollo Link State is awesome! The application needs to save some state that won't persist, like text typed into a text field.

**Comment by vlasenko** [comment]
@brianyang I would have used built-in React state for this purpose
