### ISSUE TITLE
Switch from Enzyme to react-testing-library for React tests

### ISSUE THREAD

**Issue by larixer** [sysgears/apollo-universal-starter-kit#712]
We have many issues with using Enzyme >= 3. We need to consider other solutions for writing React tests that are more reliable. One of the candidates for evaluation, which looks promising is:
https://github.com/kentcdodds/react-testing-library

**Comment by Ashu135** [comment]
Hello @larixer, I think we can close this issue as it is resolved
Reference: https://github.com/sysgears/apollo-universal-starter-kit/commit/c05580fbe12c124910889dcf923128e47e002264

**Comment by cesarhenrq** [comment]
> Hello @larixer, I think we can close this issue as it is resolved Reference: [c05580f](https://github.com/sysgears/apollo-universal-starter-kit/commit/c05580fbe12c124910889dcf923128e47e002264)

Hello, @Ashu135. I think i can help you with this issue if you are still working on it!

**Comment by larixer** [comment]
Hi @cesarhenrq, thank you!
