### ISSUE TITLE
UglifyJs error while building (probably typescript error)

### ISSUE THREAD

**Issue by wojcikiewiczm** [sysgears/apollo-universal-starter-kit#725]
Hi I encountered a problem with build. I added https://www.npmjs.com/package/sequelize-typescript to my project and configured it properly. After trying to build it I'm getting error.I'm also getting error on client build (Also using typescript there)
```
server: [at-loader] Ok, 0.047 sec.
server: webpack-for-server Time: 10516ms
server: ERROR in index.js from UglifyJs
server: Unexpected token: operator (>) [index.js:457,56]
client:
client: [at-loader] Checking started in a separate process...
client:
client: [at-loader] Ok, 0.146 sec.
client: webpack-for-web Time: 23084ms
client: ERROR in index.781a1dcb6361b1bd2333.js from UglifyJs
client: Invalid assignment [index.781a1dcb6361b1bd2333.js:73742,67]
lerna success run Ran npm script 'build' in packages:
lerna success - client
lerna success - server
Done in 25.99s.
```
As I said I'm pretty sure that for this error is responsible typescript because I searched lines given in error and found out that it's typescript lines.

Thanks

**Comment by vlasenko** [comment]
@wojcikiewiczm Please could you either create a fork that reproduces this issue, or provide exact reproduction steps?

**Comment by vlasenko** [comment]
@wojcikiewiczm I believe the recipe to fix your issue is to modify `.babelrc`:
https://github.com/webpack/webpack/issues/2972#issuecomment-341953893
But I'm not 100% sure, need to reproduce your issue first

**Comment by wojcikiewiczm** [comment]
@vlasenko Ok I managed to fix it. I changed for some reason in tsconfig target from es5 to es6 (I think because of decorators or somehing like that) so after reversing it back to es5 it works perfectly. Thank you :+1:
