### ISSUE TITLE
Changing dev port doesn't work

### ISSUE THREAD

**Issue by wojcikiewiczm** [sysgears/apollo-universal-starter-kit#750]
Hi, I'm trying to change dev port from 3000 in spinrc config in server dir. I'm changing parameter __WEBSITE_URL__ to __WEBSITE_URL__: '"http://localhost:3001"' but when i start server port is still 3000. Thanks

**Comment by vlasenko** [comment]
@wojcikiewiczm `WEBSITE_URL` has nothing to do with dev port. Check `spinjs` docs:
https://github.com/sysgears/jsapp/tree/master/packages/spinjs#concepts
`webpackDevPort` - is the parameter you are looking for.

**Comment by wojcikiewiczm** [comment]
Oh.. In older version was enough to change url. Ok thanks :+1:

**Comment by vlasenko** [comment]
@wojcikiewiczm Yes, in older version you changed only url. But in newer version we continue to split concerns, to make the kit more flexible.
