### ISSUE TITLE
Session based auth

### ISSUE THREAD

**Issue by t0x1c123** [sysgears/apollo-universal-starter-kit#756]
Hello, I have a little problem. I want to use session based auth but I discovered that cookies are not included in any request to graphql. So I googled and found that in createHttpLink has to be 
credentials: 'same-origin' when I have API on same url (that's my case)(https://www.apollographql.com/docs/react/recipes/authentication.html). I found this parameter in createApolloClient.js so I changed it from 'include' to 'same-origin'. But that didn't help. Can you please help me? I'm really confused from that file.

**Comment by vlasenko** [comment]
@t0x1c123 Have you read about credentials: `include` first? Why are you trying to change it to `same-origin`, it does not make sense. Please read docs about `credentials` attribute:
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

**Comment by vlasenko** [comment]
@t0x1c123 It is very difficult to provide any help when the description of the problem is so vague. Please try to be as specific as possible. Add reproduction steps, screenshots, etc, or rather prepare minimal reproduction example
