### ISSUE TITLE
Expected Date of Completion

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#758]
Is there any expected date by which the implementation of this starter kit will finish?

**Comment by vlasenko** [comment]
@coooolers Yes - NEVER

**Comment by coooolers** [comment]
@vlasenko Experienced programmers working on this.. if we look from this perspective, it is really good to know that we'd be numerous features.

btw any roadmap?

**Comment by vlasenko** [comment]
@coooolers The roadmap is to look what is going on inside open Pull Requests
