### ISSUE TITLE
Question: Use other than most recent android SDK version

### ISSUE THREAD

**Issue by theWeird** [sysgears/apollo-universal-starter-kit#764]
The most recent version of the kit uses android SDK in version 27.0.0
Because only a very low amount of people owns a phone running the latest android version, I need to support phones with older android versions, too.
At least down to SDK 23, if possible even 19.

Is it possible to downgrade used packages to support these SDK versions?

I tried to downgrade sdkVersion in mobile/app.json (fresh repository clone).  
Result: Error message regarding a version missmatch of JavaScript (0.50) and React Native (0.55)

Tried to change package versions of react-native in client and mobile package.json.  
Error Message: Unsupported top level event type topTouchStart dispatched

**Comment by vlasenko** [comment]
@theWeird This is not Android SDK version, this is Expo SDK version
