### ISSUE TITLE
Unhandled promise rejection ... and other problems in FF ESR

### ISSUE THREAD

**Issue by axelmm** [sysgears/apollo-universal-starter-kit#767]
I noticed several problems on FF ESR 52.8.1.
Counter/main route results with SSR rendered view followed with red error screen:
> TypeError: e[n] is undefined
`nliftState
at http://192.168.10.101:3000/:2:30806
getState
at http://192.168.10.101:3000/:2:30882
runComponentSelector
at /usr/src/app/packages/server/node_modules/react-redux/es/components/connectAdvanced.js:26:0
initSelector
at /usr/src/app/packages/server/node_modules/react-redux/es/components/connectAdvanced.js:178:0`

'Posts' route looks ok but graphql queries are not working (no OPTIONS and POST). '/graphiql' works fine. It looks like apollo/cache/observable related problem.

Starting from other url ( f.e. /contact ) and navigating with menu Posts results with view locked on 'loading ...'. Navigating to 'Upload' results with no 'table headers' (loading state).

Button 'load more' results with:
> Unhandled promise rejection TypeError: missing argument 1 when calling function this.options.watch"
`vendor_web</OverrideCache.prototype.watch@http://192.168.10.101:3000/vendor_web_26f1485e788b547ba60a_dll.js:240799:37
vendor_web</QueryManager.prototype.updateQueryWatch@http://192.168.10.101:3000/vendor_web_26f1485e788b547ba60a_dll.js:208677:16
vendor_web</QueryManager.prototype.fetchQuery@http://192.168.10.101:3000,`

updateQueryWatch  ....   return this.dataStore.getCache().watch({ ... errors with cache blocks requests?

**Comment by vlasenko** [comment]
Confirmed. This is mainly a problem in `apollo-cache-router`, looking into fixing it

**Comment by axelmm** [comment]
Thanks, it fixed most errors.

The first one still exist and for what I found it's rehydration related - before red error screen I have an error in console:

> Warning: Did not expect server HTML to contain a < section > in < div >.
`printWarning http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:29382:7
	warning http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:29406:7
	warnForDeletedHydratableElement$1 http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:140018:5
	didNotHydrateContainerInstance http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:140709:7
	deleteHydratableInstance http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:144749:9
	popHydrationState http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:144971:7
	completeWork http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:146046:11
	completeUnitOfWork http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:147713:18
	performUnitOfWork http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:147890:12
	workLoop http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:147902:24
	renderRoot http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:147942:7
	performWorkOnRoot http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148560:22
	performWork http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148482:7
	performSyncWork http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148454:3
	requestWork http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148354:5
	scheduleWork$1 http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148218:11
	scheduleRootUpdate http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148785:3
	updateContainerAtExpirationTime http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148812:10
	updateContainer http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148839:10
	vendor_web</ReactRoot.prototype.render http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:149122:3
	legacyRenderSubtreeIntoContainer/< http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:149262:9
	unbatchedUpdates http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:148679:10
	legacyRenderSubtreeIntoContainer http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:149258:5
	vendor_web</ReactDOM.hydrate http://192.168.10.101:3000/vendor_web_9e9bdcaddd6b204dded2_dll.js:149314:12
	["./src/index.tsx"]/renderApp http://192.168.10.101:3000/index.71356ca5d6df7447abb7.js:6030:12
	["./src/index.tsx"] http://192.168.10.101:3000/index.71356ca5d6df7447abb7.js:6032:1
	__webpack_require__ http://192.168.10.101:3000/index.71356ca5d6df7447abb7.js:679:12
	hotCreateRequire/fn http://192.168.10.101:3000/index.71356ca5d6df7447abb7.js:89:20
	[0] http://192.168.10.101:3000/index.71356ca5d6df7447abb7.js:25210:18
	__webpack_require__ http://192.168.10.101:3000/index.71356ca5d6df7447abb7.js:679:12
	<anonimowa> http://192.168.10.101:3000/index.71356ca5d6df7447abb7.js:725:18
	<anonimowa>`

followed by

> The above error occurred in the <Connect(Apollo(Apollo(Apollo(Apollo(Counter)))))> component:
    in Connect(Apollo(Apollo(Apollo(Apollo(Counter))))) (created by Route)
    in Route
    in Switch
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Main)
    in DataRootComponent
    in Unknown (created by withApollo(DataRootComponent))
    in withApollo(DataRootComponent) (created by Main)
    in ApolloProvider (created by Main)
    in Provider (created by Main)
    in CookiesProvider (created by Main)
    in Main
> React will try to recreate this component tree from scratch using the error boundary you provided, Main.

**Comment by vlasenko** [comment]
@axelmm Hmm, I don't see any errors now. I'm using Firefox 5.8.1 ESR under Linux and I look at the counter page. I don't have any extensions installed. How can I reproduce these errors?

**Comment by vlasenko** [comment]
@axelmm Okay, good to hear. Thanks for letting know
