### ISSUE TITLE
Support for pdf reporting and importing data to Excel

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#771]

**Comment by mitjade** [comment]
I think this might be outside the scope of what this kit should provide. I needed both of this in one of my projects and ended up using http://pdfmake.org/ and https://sheetjs.com.

**Comment by vlasenko** [comment]
@mitjade It is not out of the scope of what kit should provide if the solution will use open source technologies. These tasks are pretty generic.

**Comment by vlasenko** [comment]
Implemented in #985
