### ISSUE TITLE
Authenticated tests using current auth mutations

### ISSUE THREAD

**Issue by theWeird** [sysgears/apollo-universal-starter-kit#775]
Some month ago my project used an authentication mechanism based on an (later) abandoned PR where I used the following solution to have authenticated tests (as discussed in #669)

Doing so, I ran into two different errors (expliation below).
1. It seems, in test mode the login resolver gets no req object passed and thus no t function to destruct from it as used in login resolver
2. It seems, at another place there is an object missing to derrive the session object from. Maybe in readSession as it also requires the req object to be passed

Do you have any idea for the reason there is no req object in test mode?  
After I get this up and running with the current code base, I'd place a PR to give examples for authenticated tests in the user module.

Turn the cookieParameter `httpOnly` to `!__TEST__` instead of always `true`, to be able to use session cookies without having an active browser
```javascript
httpOnly: !__TEST__,  // disable in test mode, enable anywhere else
```
Use the following login helpers in tests to login and logout (e.g. in before and after calls)
```javascript
import { getApollo } from './integrationSetup';

import LOGIN from '../../../client/src/modules/user/graphql/Login.graphql';
import LOGOUT from '../../../client/src/modules/user/access/session/graphql/Logout.graphql';

export const login = async (usernameOrEmail = 'admin', password = 'admin123') =>
  await getApollo().mutate({
    mutation: LOGIN,
    variables: { input: { usernameOrEmail, password } }
  });

export const logout = async () => await getApollo().mutate({ mutation: LOGOUT });
```

This produces some errors as follows.  
1 is produced by using the login mutation and 2 by using the logout mutation.

>   1) Step API works
>        Authenticated
>          "before all" hook for "Query steps works":
>      Error: GraphQL error: Cannot read property 't' of undefined
>       at new ApolloError (/home/quest/Projekte/JS/autark-kit/node_modules/src/errors/ApolloError.ts:56:5)
>       at Object.next (/home/quest/Projekte/JS/autark-kit/node_modules/src/core/QueryManager.ts:197:21)
>       at notifySubscription (/home/quest/Projekte/JS/autark-kit/node_modules/zen-observable/lib/Observable.js:126:18)
>       at onNotify (/home/quest/Projekte/JS/autark-kit/node_modules/zen-observable/lib/Observable.js:161:3)
>       at SubscriptionObserver.next (/home/quest/Projekte/JS/autark-kit/node_modules/zen-observable/lib/Observable.js:215:7)
>       at /home/quest/Projekte/JS/autark-kit/node_modules/apollo-link-schema/src/schemaLink.ts:56:22
>       at <anonymous>
> 
>   2) Step API works
>        Authenticated
>          "after all" hook:
>      Error: GraphQL error: Cannot read property 'session' of undefined
>       at new ApolloError (/home/quest/Projekte/JS/autark-kit/node_modules/src/errors/ApolloError.ts:56:5)
>       at Object.next (/home/quest/Projekte/JS/autark-kit/node_modules/src/core/QueryManager.ts:197:21)
>       at notifySubscription (/home/quest/Projekte/JS/autark-kit/node_modules/zen-observable/lib/Observable.js:126:18)
>       at onNotify (/home/quest/Projekte/JS/autark-kit/node_modules/zen-observable/lib/Observable.js:161:3)
>       at SubscriptionObserver.next (/home/quest/Projekte/JS/autark-kit/node_modules/zen-observable/lib/Observable.js:215:7)
>       at /home/quest/Projekte/JS/autark-kit/node_modules/apollo-link-schema/src/schemaLink.ts:56:22
>       at <anonymous>

The first error seems to be thrown by `server/src/modules/user/auth/password/resolvers.js` having no req object given to the login mutation resolver and thus cannot destruct a variable `t` from it.  
A small test shot by removing the destruction of `{ t }` from the parameter list and instead defining a `const t = token => token` inside the mutation handler ended up with just the same error as produced by the logout mutation.

**Comment by vlasenko** [comment]
@theWeird I don't see how we can help here. If you had described some approach that has issues with current code base we could look into it.

**Comment by theWeird** [comment]
The issue seems to be, that, triggered in test mode, the resolvers on server side don't get a request object passed.

I don't see any reason why this approach for authenticated tests shouldn't work when the login and logout mutations would work in test mode.

**Comment by vlasenko** [comment]
@theWeird So basically we should make `login` and `logout` work in the `master` for tests and that might help you solve issue that you are facing now?

**Comment by theWeird** [comment]
Exactly.  
If there is a solution to do those mutations to get a user session in test mode, I can provide some authenticated tests for user module.

**Comment by vlasenko** [comment]
@theWeird Okay, we will make this task a priority

**Comment by theWeird** [comment]
Do you have an idea yet what the problem could be?  
Might there be a connection to the missing context object in #796 ?

**Comment by vlasenko** [comment]
@theWeird No, #796 is a very new issue, that appeared after upgrade to Apollo Server 2
