### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by vjpr** [sysgears/apollo-universal-starter-kit#784]

**Comment by vlasenko** [comment]
Yes, it would be nice to upgrade. Though, I'm not sure whether it will be smooth

**Comment by vlasenko** [comment]
Seems Haul has added support for Babel 7 now:
https://github.com/callstack/haul/issues/411
We are still waiting for Babel 7 and React Native 0.57 support in Expo SDK, which could happen in Expo SDK 31, hopefully.

**Comment by vlasenko** [comment]
Added in https://github.com/sysgears/apollo-universal-starter-kit/pull/900
