### ISSUE TITLE
Cannot register for user account

### ISSUE THREAD

**Issue by QuentinCWG** [sysgears/apollo-universal-starter-kit#798]
Problem: Cannot register using /register.

Error given: 
```{"data":{"register":{"user":null,"errors":null,"__typename":"UserPayload"}},"errors":[{"message":"context is not defined","locations":[{"line":7,"column":5}],"path":["register","errors"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}]} <= register({"input":{"username":"Test","email":"test@gmail.com","password":"123456789"}})```

**Comment by vlasenko** [comment]
Commited several fixes. Right now registration process goes without error. But after successful Sign Up user is redirected to Sign In form, which is not an optimal flow. But at least now it works as before, so I'm closing this issue.

**Comment by vlasenko** [comment]
@tronin You have different error and hence different issue. Please open new issue and provide reproduction steps.
