### ISSUE TITLE
Get rid of 'updateQueries' mutation methods

### ISSUE THREAD

**Issue by lyzhovnik** [sysgears/apollo-universal-starter-kit#812]
The mutation method 'updateQueries' should be replaced  to the method 'update',  because 'updateQueries' method is gonna be deprecated - https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-mutation-options-updateQueries 

Good example for 'update' method implementation you can see in the Upload module.

**Comment by alekseyzadorozhniy** [comment]
The issue has been resolved in the #969 PR
