### ISSUE TITLE
Error on 'yarn tests' 

### ISSUE THREAD

**Issue by drockyy** [sysgears/apollo-universal-starter-kit#825]
Starting yarn tests following error appears:

> client: spin error { Error: spawn C:\Users\Dennis\Desktop\apollo-universal-starte                                                                                                                                                                                              r-kit\packages\client\node_modules\.bin\mocha-webpack ENOENT
client:     at _errnoException (util.js:992:11)
client:     at Process.ChildProcess._handle.onexit (internal/child_process.js:190                                                                                                                                                                                              :19)
client:     at onErrorNT (internal/child_process.js:372:16)
client:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
client:     at process._tickCallback (internal/process/next_tick.js:180:9)
client:     at Function.Module.runMain (module.js:695:11)
client:     at startup (bootstrap_node.js:191:16)
client:     at bootstrap_node.js:612:3
client:   code: 'ENOENT',
client:   errno: 'ENOENT',
client:   syscall: 'spawn C:\\Users\\Dennis\\Desktop\\apollo-universal-starter-ki                                                                                                                                                                                              t\\packages\\client\\node_modules\\.bin\\mocha-webpack',
client:   path: 'C:\\Users\\Dennis\\Desktop\\apollo-universal-starter-kit\\packag                                                                                                                                                                                              es\\client\\node_modules\\.bin\\mocha-webpack',
client:   spawnargs:
client:    [ '--webpack-config',
client:      'C:\\Users\\Dennis\\Desktop\\apollo-universal-starter-kit\\node_modu                                                                                                                                                                                              les\\spinjs\\webpack.config.js',
client:      '--include',
client:      'raf/polyfill',
client:      '-t',
client:      '10000',
client:      '--full-trace',
client:      '--exit',
client:      'src/**/*.spec.*' ] }

Environment: Windows 10

To reproduce this error:

`git clone https://github.com/sysgears/apollo-universal-starter-kit`
`yarn`
`yarn seed`
`yarn build`
`yarn tests`

I got this error for client, server and mobile

**Comment by vlasenko** [comment]
@drockyy The fix has been pushed into `master`, please check

**Comment by drockyy** [comment]
@vlasenko Thanks a lot, it works like a charm
