### ISSUE TITLE
Webpack development server live reload not working

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#834]
When I make a change in the code, Webpack development server is not compiling the code on-the-fly. As a consequence, both the browser and the Android mobile emulator are not getting refreshed automatically.

I am using the latest copy of the code.

Are you experiencing the same issue?

**Comment by vlasenko** [comment]
@coooolers I don't experience this issue

**Comment by coooolers** [comment]
When I run yarn, it generates this set of info and warnings which I believe is probably a source of error of the issue reported above:

warning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/traveling-fastlane-darwin@1.4.7: The platform "linux" is incompatible with this module.
info "@expo/traveling-fastlane-darwin@1.4.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-darwin-ia32@2.2.8: The platform "linux" is incompatible with this module.
info "@expo/ngrok-bin-darwin-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-darwin-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-darwin-x64@2.2.8: The platform "linux" is incompatible with this module.
info "@expo/ngrok-bin-darwin-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The platform "linux" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-freebsd-x64@2.2.8: The platform "linux" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The CPU architecture "x64" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm64@2.2.8: The CPU architecture "x64" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info "@expo/ngrok-bin-linux-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-sunos-x64@2.2.8: The platform "linux" is incompatible with this module.
info "@expo/ngrok-bin-sunos-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The platform "linux" is incompatible with this module.
info "@expo/ngrok-bin-win32-ia32@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-win32-x64@2.2.8-beta.1: The platform "linux" is incompatible with this module.
info "@expo/ngrok-bin-win32-x64@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-config-airbnb@16.1.0" has unmet peer dependency "eslint@^4.9.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@12.1.0" has unmet peer dependency "eslint@^4.9.0".
warning " > eslint-plugin-import@2.13.0" has unmet peer dependency "eslint@2.x - 5.x".
warning " > eslint-plugin-jsx-a11y@6.0.3" has unmet peer dependency "eslint@^3 || ^4".
warning " > eslint-plugin-mocha@5.1.0" has unmet peer dependency "eslint@>= 4.0.0".
warning " > eslint-plugin-react@7.10.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning " > heroku-babel-loader@7.1.2" has incorrect peer dependency "webpack@2 || 3".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > apollo-cache-router@1.1.6" has unmet peer dependency "apollo-cache@^1.1.0".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > apollo-client@2.3.7" has incorrect peer dependency "graphql@^0.11.0 || ^14.0.0".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > bootstrap@4.1.3" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > bootstrap@4.1.3" has unmet peer dependency "popper.js@^1.14.3".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > native-base@2.7.2" has incorrect peer dependency "react@>=16.4.1".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > native-base@2.7.2" has incorrect peer dependency "react-native@>=0.56.0".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > mocha-webpack@0.7.0" has incorrect peer dependency "mocha@^2.4.5 || ^3.0.0".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > mocha-webpack@0.7.0" has incorrect peer dependency "webpack@^1.12.13 || ^2.1.0-beta.15".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > mobile > haul@1.0.0-rc.7" has unmet peer dependency "babel-preset-react-native@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > antd > rc-editor-mention@1.1.7" has unmet peer dependency "immutable@^3.7.4".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > expo > react-native-maps@0.21.0" has incorrect peer dependency "react-native@^0.51 || ^0.52 || ^0.53 || ^0.54".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > expo > react-native-web-maps@0.1.0" has unmet peer dependency "react-native-web@*".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > expo > react-native-web-maps > react-google-maps@7.3.0" has incorrect peer dependency "react@15.5.4".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > expo > react-native-web-maps > react-google-maps@7.3.0" has incorrect peer dependency "react-dom@15.5.4".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > mobile > haul > react-hot-loader > redbox-react@1.6.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
warning "workspace-aggregator-2be0a50f-d08e-46b9-9426-e4e3f349cd43 > client > expo > react-native-web-maps > react-google-maps > react-prop-types-element-of-type@2.2.0" has incorrect peer dependency "react@^0.14.6 || ^15.0.0-0".
[########################-----------------------------------------] 29981/79[########################----------------------------------------] 30109/797[#[###########[###############[#[#############################[#########[#######[5/5] Building fresh packages...
$ opencollective postinstall

Kindly help me out.

**Comment by vlasenko** [comment]
@coooolers I don't think this is the cause for the issues you have, I see the same set of warnings

**Comment by vlasenko** [comment]
@coooolers I'm using Ubuntu 16.04 as well and I don't see any problem. Please check carefully this section of Webpack docs, maybe you have a problem with watchers:
https://webpack.js.org/configuration/watch/#troubleshooting

**Comment by coooolers** [comment]
Thank you, I will.

Could you pl. let me know the yarn, node, and npm versions? Mine are:

$ yarn -v
1.9.4
$ node -v
v10.9.0
$ npm -v
6.2.0

**Comment by vlasenko** [comment]
@coooolers `npm` is not used, the kit uses `yarn`
$ yarn -v
1.9.4
$ node -v
v10.3.0
$ npm -v
6.1.0
$ lsb_release -aNo LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by coooolers** [comment]
$ cat /proc/sys/fs/inotify/max_user_watches
8192

**Comment by vlasenko** [comment]
@coooolers Yes, it looks very low and might cause this issue for you.
On my machine:
$ cat /proc/sys/fs/inotify/max_user_watches
524288

**Comment by coooolers** [comment]
@vlasenko Thanks a lot. I followed the instructions stated in the document you shared with me and it is working perfectly now.

Thanks once again
