### ISSUE TITLE
Authorization in GPlayground/GraphiQL broken after Apollo Server 1 -> 2 upgrade

### ISSUE THREAD

**Issue by clodal** [sysgears/apollo-universal-starter-kit#842]
After upgrading from Apollo Server 1 to Apollo Server 2, user authorization token in GraphiQL seems to be broken.

## Repro
1. Checkout this commit where Apollo Server 2 was newly installed: `e84531451c273b5861c64837b8b62db8c4d9b02e`
2. Do `yarn; yarn seed; yarn watch`
3. Go to `http://localhost:3000/graphiql` and run the following mutation
```
mutation {
  login(input:{usernameOrEmail:"admin@example.com", password:"admin123"}) {
    user {
      id
    }
  }
}
```
4. Then check current user with currentUser query and find that you are not logged in
```
{
  "data": {
    "currentUser": null
  }
}
```

To see a working version, checkout the commit before the above commit, i.e. `d7542c3d7563844c008195d7da7a2e75094bc98a` and repeat steps 2, 3, 4. You will see currentUser is logged in.

**Comment by vlasenko** [comment]
@clodal This is the best issue report I have ever seen, thank you for full details! :)

**Comment by vlasenko** [comment]
@clodal It is really a GraphQL playground issue:
https://github.com/prisma/graphql-playground/issues/748

**Comment by clodal** [comment]
Awesome thanks, please feel free to close out issue if you like
