### ISSUE TITLE
Few scopes are not defined in the Server-Side User Module

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#848]
Module User at Server Side
1. resolvers.js: 

Its code snippets:

`addUser: withAuth(
      (obj, args, { User, user }) => {
        return user.id !== args.input.id ? ['user:create'] : ['user:create:self'];
      },`

`editUser: withAuth(
      (obj, args, { User, user }) => {
        return user.id !== args.input.id ? ['user:update'] : ['user:update:self'];
      },`

Two Questions/Suggestions:

1. ['user:create'], ['user:create:self'], ['user:update.self'] etc. are not defined in the scopes.js
`export default {
  admin: ['user:*'],
  user: ['user:view:self', 'user:update:self']
};`

2. In the resolvers.js, `return user.id !== args.input.id` <---- Whether it should be args.id or args.input.id ?

**Comment by vlasenko** [comment]
Not all the scopes must be defined. Please use issues for reporting issues, not for asking questions about the code.
