### ISSUE TITLE
Error: Schema must contain unique named types but contains multiple types named "a-type-name".

### ISSUE THREAD

**Issue by abhayca** [sysgears/apollo-universal-starter-kit#853]
In my server side schema.graphql, I defined a type named Tag as follows:
type Tag {
  id: Int!
  tagName: String!
  tagValue: String!
}
In the same file, this type is being referred at several places, like, for example,
type Customer {
  id: Int!
  ...
 tag: [Tag!]!
}

When I run yarn watch, I get this error:
Error: Schema must contain unique named types but contains multiple types named "Tag".

This type has been defined only once though.

Has anybody encountered such an error?

**Comment by lyzhovnik** [comment]
Hi, @abhayca. It means you defined Tag type several time. Check other modules if they have this type, because Kit merges all of the schemes (from every module) into one and there might be conflict.

**Comment by abhayca** [comment]
Hi

I am sure it is not defined anywhere else. This is because I have only one custom module named Customer and in its Graphql schema, there are two types named Customer and Tag.

I am reading this post:
https://github.com/graphql/graphql-js/issues/146

At one place it said:
_Maybe one place to look is if you're calling the "new GraphQLXType()" constructors more than once per type? Perhaps you're defining them within a function that's being called multiple times rather than just at the top level of a module?_

**Comment by lyzhovnik** [comment]
It describes issue what I've written above. Your types defined or imported twice.
Have you checked this solution https://github.com/graphql/graphql-js/issues/146#issuecomment-220402396?

**Comment by abhayca** [comment]
I checked this issue too. But sill no success. Will update once i get the answer.

**Comment by abhayca** [comment]
Error is when using a type as a member of an input. Input types can't have fields that are other objects. Solution is: Only an input can be member of an input.

type Tag {
  id: Int!
  tagName: String!
  tagValue: String!
}

#Input for addCustomer Mutation
input AddCustomerInput {
  ...
ERROR --->  tag: [Tag!]!
}

#Input for editCustomer Mutation
input EditCustomerInput {
  ...
ERROR --->  tag: [Tag!]!
}

SOLUTION:
input TagInput {
  id: Int!
  tagName: String!
  tagValue: String!
}

# Input for addCustomer Mutation
input AddCustomerInput {
  ...
  tag: [TagInput!]!
  ...
}

# Input for editCustomer Mutation
input EditCustomerInput {
  ...
  tag: [TagInput!]!
  ...
}

**Comment by vlasenko** [comment]
@abhayca Thank you for the update and solution. I guess we can close this now.
