### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_a.data.serverCounter')

### ISSUE THREAD

**Issue by abhayca** [sysgears/apollo-universal-starter-kit#855]
android-webpack info bundle is now VALID.
android-webpack info Time: 3460ms
Built at: 09/19/2018 1:35:12 PM
Entrypoint index [big] = index.mobile.bundle index.mobile.bundle.map
expo-for-android debug Running application "main" with appParams: {"initialProps":{"exp":{"initialUri":"exp://192.168.1.6:19000","manifest":{"isVerified":true,"hostUri":"192.168.1.6:19000","version":"1.0.0","slug":"apollo-universal-starter-kit","name":"Apollo Universal Starter Kit","iconUrl":"http://192.168.1.6:3010/assets/app.png","developer":{"tool":"crna","projectRoot":"/home/abhay/Project/apollo-universal-starter-kit/packages/mobile/.expo/android"},"xde":true,"sdkVersion":"27.0.0","id":"@anonymous/apollo-universal-starter-kit-e7755a65-6f6b-4ae4-a003-af5d2ede0133","mainModuleName":"index.mobile","packagerOpts":{"dev":true,"lanType":"ip","hostType":"tunnel","minify":false},"ios":{"bundleIdentifier":"com.sysgears.apollokit"},"bundleUrl":"http://192.168.1.6:3010/index.mobile.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=%2Fhome%2Fabhay%2FProject%2Fapollo-universal-starter-kit%2Fpackages%2Fmobile%2F.expo%2Fandroid%2Fnode_modules%2Fexponent%2Ftools%2FhashAssetFiles","orientation":"default","android":{"package":"com.sysgears.apollokit"},"primaryColor":"#023C69","logUrl":"http://192.168.1.6:19000/logs","loadedFromCache":false,"icon":"app.png","env":{"EXPO_PORTS":"{\"android\":19000}"},"debuggerHost":"192.168.1.6:3010"},"shell":false}},"rootTag":31}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
expo-for-android debug frontend info Connecting to GraphQL backend at: http://192.168.1.6:8080/graphql
expo-for-android debug frontend debug {} <=e serverCounterQuery
expo-for-android debug frontend debug {} <=e currentUser
expo-for-android debug TypeError: TypeError: TypeError: undefined is not an object (evaluating '_a.data.serverCounter')

This error is located at:
    in Query
    in Unknown (created by I18n)
    in I18n (created by Translate(Component))
    in Translate(Component)
    in RCTView (at View.js:60)
    in View
    in Unknown (created by I18n)
    in I18n (created by Translate(Component))
    in Translate(Component) (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:563)
    in RCTView (at View.js:60)
    in View (at StackViewLayout.js:562)
    in RCTView (at View.js:60)
    in View (at StackViewLayout.js:561)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)

Any clue?

**Comment by abhayca** [comment]
This error occurs when yarn watch is run. This error is preceded by another error ...

/home/abhay/Project/apollo-universal-starter-kit/node_modules/react-native-keyboard-spacer/KeyboardSpacer.js:4
import React, { Component } from 'react';
       ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)

**Comment by vlasenko** [comment]
@abhayca Please provide full log, not just some part of the log

**Comment by vlasenko** [comment]
@abhayca Your server code tries to import `react-native-keyboard-spacer`. Looks like your `ThingForm.jsx` uses `react-native` components and then this `ThingForm.jsx` is required by client code. This is wrong. If `ThingForm.jsx` uses `react-native` it should be imported only by `mobile` code

I'm closing this issue - because it is not issue in the kit, but rather in your code

**Comment by abhayca** [comment]
Looks like there is an error in my .jsx file. Pl. do not spend too much time,

**Comment by abhayca** [comment]
Yes correct
