### ISSUE TITLE
Clarification of intended usage of 'exp' script in project

### ISSUE THREAD

**Issue by haysclark** [sysgears/apollo-universal-starter-kit#878]
**Describe the bug**
It is unclear if the _exp_ script is intended to be used with the project.

**To Reproduce**
1. Go to _scripts_ section of [_package.json_](https://github.com/sysgears/apollo-universal-starter-kit/blob/stable/package.json#L15) 
2. See script: ```"exp": "yarn --cwd packages/mobile exp",```
3. Go to [Available-Scripts](https://github.com/sysgears/apollo-universal-starter-kit/wiki/Available-Scripts) documentation.
4. See that _exp_ is not mentioned in the _yarn <script>_ column.

**Expected behavior**
It seems that the script should either be added to the documentation if supported or removed from _package.json_ if unsupported.

**Additional context**
Part of my confusion about using _exp_ with the _apollo-universal-starter-kit_ was due to the fact that it is included [in _package.json_](https://github.com/sysgears/apollo-universal-starter-kit/blob/stable/package.json#L15), yet it not mentioned in the [Available-Scripts](https://github.com/sysgears/apollo-universal-starter-kit/wiki/Available-Scripts) documentation. 
I think this minor tweak might help users like myself who are new to the project, and are used to using Expo for commands like ```exp start```, ```exp ios```, ```exp android```, etc.

**Comment by AndSviat** [comment]
Thank you for the remark. We'll update this part of documentation shortly.

**Comment by AndSviat** [comment]
We've improved the documentation for available scripts: https://github.com/sysgears/apollo-universal-starter-kit/wiki/Available-Scripts
The usage of `exp` and `exp-publish` scripts is clarified.
