### ISSUE TITLE
Hot reload stops working if error happens on SSR

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-universal-starter-kit#894]
**Describe the bug**
If you have an error in certain files like `packages/client/src/utils/FieldAdapter.jsx` and start the the kit, you get and error when this code executes while SSR is going on. Then If you fix the error, page reloads, but error is still there. You have to restart it with no errors, to make it work again.

**To Reproduce**
1. Check out branch `https://github.com/sysgears/apollo-universal-starter-kit/tree/hot-reload-error`
2. Start kit `yarn watch`.
3. Navigate to `http://localhost:3000/post/20`
4. You get the error in `packages/client/src/utils/FieldAdapter.jsx`.
5. Now if you fix the error hot reload is called, but error remains.
6. If you hit this page, you have to fix the error before you restart the app.

**Expected behavior**
Hot reload should reload correctly in this case if error happens on SSR. 

**Additional context**
Set `openBrowser: false` in `packages/client/.spinrc.js`, so you do not first load homepage where there is no error.

**Comment by mitjade** [comment]
Step 6. to fix the error just remove:
```
70:    const values = 1;
71:    const bla = values.keys();
72:    console.log(bla);
```

**Comment by vlasenko** [comment]
@mitjade What do you mean in `Step 5` - kill the app and start again, kill and restart `yarn watch`?

**Comment by mitjade** [comment]
```
Ctrl C
yarn watch
```
