### ISSUE TITLE
Ignore Case when searching users 

### ISSUE THREAD

**Issue by abhayca** [sysgears/apollo-universal-starter-kit#901]
**Describe the issue**
Currently, the comparison when searching for a particular set of users is case sensitive. Ideally speaking, it should be case insensitive.

**To Reproduce**
Steps to reproduce the behavior in the mobile app:
1. Go to Users option
2. Click on Filter icon at the top right
3. In the Search field, enter the string, Admin (note A should be capital)
4. Users Not Found is displayed.

**Expected behavior**
The admin user should be displayed, 

**Answer**
Instead of knex 'like', use 'ilike' in the /server/.../user/sql.js file as follows:

```
async getUsers(orderBy, filter) {
      ...
      if (has(filter, 'searchText') && filter.searchText !== '') {
        queryBuilder.where(function() {
          this.where('u.username', 'ilike', `%${filter.searchText}%`)
            .orWhere('u.email', 'ilike', `%${filter.searchText}%`)
            .orWhere('up.first_name', 'ilike', `%${filter.searchText}%`)
            .orWhere('up.last_name', 'ilike', `%${filter.searchText}%`);
        });
      }
    }
    return camelizeKeys(await queryBuilder);
  }
```
At least this solution works for the PostgreSQL db, I don't know about the other dbs.

**Comment by evgenijolshanskij** [comment]
The issue resolved in the #972 PR.
