### ISSUE TITLE
Unhandled promise rejection when trying to logout from a mobile device

### ISSUE THREAD

**Issue by abhayca** [sysgears/apollo-universal-starter-kit#902]
**Steps to reproduce the behavior:**
1. Login as admin, or probably as an ordinary user
2. Click Users - List of Users is displayed
3. Click Logout
4. Error is reported: console.error: "Unhandled promise rejection", {"line":14637,"column":36,"sourceURL":"http:/ /192.168.1.6:3010/index.mobile.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=%2Fhome%2Fcool%2FProject%2Fapollo-universal-starter-kit%2Fpackages%2Fmobile%2F.expo%2Fandroid%2Fnode_modules %2Fexponent%2Ftools%2FhashAssetFiles","graphQLErrors":[{"extensions":{"code":"UNAUTHENTICATED"}}],"networkError":null,"message":"GraphQL error: undefined"}
error

**Comment by vlasenko** [comment]
@abhayca I cannot reproduce this for the latest code in the `master` by following your steps

**Comment by vlasenko** [comment]
@abhayca Oh, looks like it happens sometimes, was able to face this error

**Comment by mitjade** [comment]
Steps to reproduce on web:
1. Login as admin, or probably as an ordinary user
2. Click Users - List of Users is displayed
3. Refresh page
4. Click Logout

**Comment by mitjade** [comment]
@vlasenko After the error happens, you can reproduce it every time without step 3.
