### ISSUE TITLE
Error when running Scala app

### ISSUE THREAD

**Issue by AndSviat** [sysgears/apollo-universal-starter-kit#957]
**Describe the bug**
When running the Scala backend instead of Node.js, the client crashes with `TypeError: _a.data is undefined`.

**To Reproduce**
1. Clone Apollo Universal Starter Kit.
2. Go into the project and install dependencies with `yarn`
3. Seed the data with `yarn seed`
4. Run **only the client application** with `yarn watch-client`.
5. In a different terminal window, go into `packages/server-scala` and run `sbt run`.
6. See the error 

```
TypeError: _a.data is undefined
at ServerCounterWithQuery/< (<!DOCTYPE html>
at undefined:undefined:undefined
```

**Expected behavior**
No error, I suppose.

**Screenshots**
Screenshot: [https://prnt.sc/lutjdf](https://prnt.sc/lutjdf)

**Additional context**
If you build the Node.js backend (by running `yarn watch` from the root of the project), the application works just fine.

**Comment by tverdokhlebd** [comment]
This bug has already fixed - (A stub graphql query "currentUser" was absent).
